### ISSUE TITLE
Reduce default tadfactor value

### ISSUE THREAD

**Issue by amjjbonvin** [haddocking/haddock3#1000]
## **Desired feature/enhancement**

During the torsion angle dynamics in the `flexref` module, the time steps are increased by a factor defined by `tadfactor` for the rigid body stages of the protocol.  This in combination with fully flexible segment definitions might lead to failures (the MD becomes unstable and crashes). In haddock2.X those cases were handled by the python code and the model was rerun with a smaller factor.

The `flexref` CNS code should automatically detected the presence of fully flexible segments and reduce the `tadfactor` from the default value of 8 to e.g. 4.

## **Motivation**

This will cause less model failures and more stable runs.

**Comment by Shadi201711** [comment]
try this
https://gofile.io/d/yMHabA
select the desired compiler in the installer

**Comment by amjjbonvin** [comment]
Best to implement this once issue #969 has been solved/merged.

**Comment by amjjbonvin** [comment]
Will add an integration test once the integration-tests branch is merged, using the test_flexref.py as basis.
