### ISSUE TITLE
Clustering failure:  KeyError

### ISSUE THREAD

**Issue by wrmartin** [haddocking/haddock3#102]
I am running the alpha1 version of haddock3.  After completing it0, it1, and itw (1000, 100, and 100 iterations, respectively), clustering fails with the following:

+ Calculating HADDOCK score for 100 structures
+ Clustering with cutoff: 0.6 and threshold: 4

```
Traceback (most recent call last):
  File "/home/martinw3/beegfs/haddock3-3.0.alpha1/haddock/run_haddock.py", line 249, in <module>
    run_analysis(water_refinement_complexes)
  File "/home/martinw3/beegfs/haddock3-3.0.alpha1/haddock/run_haddock.py", line 173, in run_analysis
    ana.cluster(cutoff=0.60, threshold=4)
  File "/home/martinw3/beegfs/haddock3-3.0.alpha1/haddock/modules/analysis/ana.py", line 211, in cluster
    self.structure_dic[cluster_center_name][f"cluster-{cutoff}-{threshold}_name"] = c.name
KeyError: 'water_refinement/complex_itw_100.pdb'
```

The error makes sense; the file doesn't exist.  However, I can't sort why it's looking for a 101st file (or why it's not complex_itw_000100.pdb).  Even more puzzling, this doesn't happen with the sample protein-protein system but does with all of my other runs.  It appears, unless I'm missing something, that all of the normal output files are generated outside of the cluster_0.6_4.out and scoring.stat files.

**Comment by joaomcteixeira** [comment]
Hi @wrmartin 
During the next few days we will be implementing [FCC]() in HADDOCK3 `main` branch. Also accepting many of the pending PRs. We are currently given very few support to `alpha1`. Please stay tuned we will inform when this is done. Please read also here, as it may help you meanwhile: https://github.com/haddocking/haddock3/issues/101#issuecomment-955690736
