### ISSUE TITLE
Modify `less_io` parameter name to `debug`

### ISSUE THREAD

**Issue by VGPReys** [haddocking/haddock3#1033]
## **Desired feature/enhancement**

It would be easier for user to understand the word `debug` more than `less_io`.

## **Motivation**

Make it simpler to explain and more intuitive: `debug = true` will correspond to dumping intermediate and stdout files.

## **Description**

Modify the parameter name `less_io` to `debug`.
Must also invert all the conditions evaluating the parameter, as `less_io = true` == `debug = false` and vice versa.

**Comment by sverhoeven** [comment]
In https://github.com/haddocking/haddock3/pull/1071 the debug value was inverted. Does this mean when I use `mode="batch"` that must set `debug = true` or can debug parameter be absent in cfg file?

Need to know so I can create correct JSON schema at https://github.com/i-VRESSE/workflow-builder/blob/2e0acda8e27c7dd836c96d69ed99a3a523689b42/packages/haddock3_catalog/public/catalog/haddock3.easy.yaml#L168-L183

**Comment by amjjbonvin** [comment]
Yes - with batch mode debug must be set to true
