### ISSUE TITLE
Update minimal python version

### ISSUE THREAD

**Issue by rvhonorato** [haddocking/haddock3#1040]
## **Desired feature/enhancement**

Update minimal python version to a recent release

## **Motivation**

Currently the recomended python version is 3.9, which is already a quite old version and [it's marked as legacy](https://www.python.org/downloads/release/python-390/) and it's end-of-life is due 2025. Here we should be using the most recent version - 3.12

## **Description**

Developing code based on an old python interpreter might cause plenty of issues as the new code can use features that are deprecated in newest versions, as well as blocks in the dependencies.

## **Additional context**

The "simplest" way to do this update is to try to install and run the tests on 3.12 and see what are the incompatibilities.

**Comment by sverhoeven** [comment]
My Ubuntu 24.04 ships with Python 3.12.3 would be nice if that version was supported.

**Comment by rvhonorato** [comment]
Indeed, mine as well. Just updated the issue text
