### ISSUE TITLE
Parameter `debug` is incompatible with `mode=batch`

### ISSUE THREAD

**Issue by paoloc03** [haddocking/haddock3#1070]
## **Question**

Hi! I'm trying to use haddock3 in **batch** mode but it keeps returning this error:

Parameter `debug` is incompatible with `mode=batch`

When I run it in **local** mode it runs without any problems. 
Can you help me? 
## **Additional context**

I'm using the config files provided in the examples and in the tutorial but the problem persist.

**Comment by amjjbonvin** [comment]
set: `debug = true` in your configuration file.

**Comment by paoloc03** [comment]
Thank you for your quick answer! I tried to add to my .cfg file 'debug = true' but it doesn't seem to work. 
Here below the general settings of my cfg file:

# directory name of the run
run_dir = "run1"
# compute mode
mode = "batch"
# batch system
batch_type = "slurm"
# queue name
queue = "short"
# number of concurrent jobs to submit to the batch system
queue_limit = 100
# number of models to produce per submitted job
concat = 10

# Self contained rundir
self_contained = true

# Post-processing to generate statistics and plots
postprocess = true

# Cleaning
clean = true

#debug 
debug = true


While here below I attach the error log:

##############################################
#                                            #
#                 HADDOCK 3                  #
#                                            #
##############################################

!! Some of the HADDOCK3 components use CNS (Crystallographic and NMR System) which is free of use for non-profit applications. !!
!! For commercial use it is your own responsibility to have a proper license. !!
!! For details refer to the DISCLAIMER file in the HADDOCK3 repository. !!

Starting HADDOCK 3.0.0 on 2024-10-01 06:25:00

Python 3.9.12 (main, Apr  5 2022, 06:56:58)
[GCC 7.5.0]

[2024-10-01 06:25:24,479 libutil ERROR] Parameter `debug` is incompatible with `mode=batch`.
Traceback (most recent call last):
  File "/home/pc674299/.local/lib/python3.9/site-packages/haddock/libs/libutil.py", line 335, in log_error_and_exit
    yield
  File "/home/pc674299/.local/lib/python3.9/site-packages/haddock/clis/cli.py", line 150, in main
    params, other_params = setup_run(
  File "/home/pc674299/.local/lib/python3.9/site-packages/haddock/gear/prepare_run.py", line 281, in setup_run
    validate_parameters_are_not_incompatible(general_params)
  File "/home/pc674299/.local/lib/python3.9/site-packages/haddock/gear/prepare_run.py", line 1083, in validate_parameters_are_not_incompatible
    raise ValueError(
ValueError: Parameter `debug` is incompatible with `mode=batch`.
[2024-10-01 06:25:24,481 libutil ERROR] Parameter `debug` is incompatible with `mode=batch`.
[2024-10-01 06:25:24,481 libutil ERROR] An error has occurred, see log file. And contact the developers if needed.
[2024-10-01 06:25:24,481 libutil INFO] Finished at 01/10/2024 06:25:24. For any help contact us at https://github.com/haddocking/haddock3/issues. Adiós! Agur! La revedere!!

**Comment by amjjbonvin** [comment]
Make sure to have the most recent version as the code is still evolving fast.

If it still does not work, then we have an issue to fix.

**Comment by paoloc03** [comment]
I downloaded the code today at 11:30 CET from the github page, so it should be updated.
Thank you for all your help anyways!

**Comment by rvhonorato** [comment]
The solution for this is held by #991

**Comment by amjjbonvin** [comment]
Please update the haddock3 version - should be working now (you still need to set debug=true though )

**Comment by paoloc03** [comment]
I updated the haddock3 version but the error seems to remain, even though now is slightly different:

ValueError: Parameter `debug` with value `True` is incompatible with `mode=batch`

**Comment by amjjbonvin** [comment]
Ok - should now be fixed!

Do update the code first.

**Comment by paoloc03** [comment]
It works! Thank you so much!
