### ISSUE TITLE
wrong numbers in capri_clt

### ISSUE THREAD

**Issue by mgiulini** [haddocking/haddock3#1081]
## **Module/Workflow/Library affected**
caprieval capri_clt files

## **Expected behavior**
the capri_clt files should be consistent with the capri_ss files

## **Actual behavior**
when debug = false (default settings) haddock3 gives wrong numbers in capri_clt files

technically, the capri jobs are not being merged properly here https://github.com/haddocking/haddock3/blob/97dfc828312908e9dc234be1f0fc8f4733589c14/src/haddock/modules/analysis/caprieval/__init__.py#L144-L149 and this causes this other function to mix up things https://github.com/haddocking/haddock3/blob/97dfc828312908e9dc234be1f0fc8f4733589c14/src/haddock/modules/analysis/caprieval/capri.py#L1020-L1021

## **Steps to reproduce the behavior**

1. Go to the docking-protein-glycan/ example directory
2. Run the following command: `haddock3 docking-protein-glycan-test.cfg`
3. open the capri_ss file `head run1-test/2_rigidbody/capri_ss.tsv`
4. open the capri_clt file `head run1-test/2_rigidbody/capri_clt.tsv`
5. realise the numbers do not match at all

## **Suggestions on how to fix it**
jobs have to be merged properly in caprieval! otherwise the zipping fails

**Comment by rvhonorato** [comment]
> jobs have to be merged properly

is not very descriptive, what is the actual issue @mgiulini, is it order? ranking?

**Comment by mgiulini** [comment]
> > jobs have to be merged properly
> 
> is not very descriptive, what is the actual issue @mgiulini, is it order? ranking?

the `debug=true` mode merges the data https://github.com/haddocking/haddock3/blob/5abc1a3668fb3ada6c7d4e7e30cf5169b9b5e9e3/src/haddock/modules/analysis/caprieval/__init__.py#L160 while the other mode doesn't, leading to models and capri objects being mismatched in here https://github.com/haddocking/haddock3/blob/97dfc828312908e9dc234be1f0fc8f4733589c14/src/haddock/modules/analysis/caprieval/capri.py#L1020-L1021
the cluster ids and corresponding quantities are assigned randomly (by the zip function), thus messing up the capri_clt table

**Comment by rvhonorato** [comment]
?

zip is not random, it uses the underlying iterators. Both are using lists, and even tho lists keep their order, they are not ordered types. So the difference comes from the order in which the elements are being read - namely how the `jobs` are retrieved.

The problem is actually that this `jobs` variable is being shadowed without being re-ordered, From the code I assume they should be ordered by `CAPRI.identificator`

**Comment by rvhonorato** [comment]
> ## **Steps to reproduce the behavior**
> 1. Go to the docking-protein-glycan/ example directory
> 2. Run the following command: `haddock3 docking-protein-glycan-test.cfg`
> 3. open the capri_ss file `head run1-test/2_rigidbody/capri_ss.tsv`
> 4. open the capri_clt file `head run1-test/2_rigidbody/capri_clt.tsv`
> 5. realise the numbers do not match at all

Is this correct?
```
head: cannot open 'run1-test/2_rigidbody/capri_ss.tsv' for reading: No such file or directory
```

Changing it to `head run1-test/02_caprieval/capri_ss.tsv`

What I get is:

```
$ head run1-test/02_caprieval/capri_ss.tsv
model   md5     caprieval_rank  score   irmsd   fnat    lrmsd   ilrmsd  dockq   rmsd    cluster_id      cluster_ranking model-cluster_ranking   air     angles  bonds   bsa     cdih     coup    dani    desolv  dihe    elec    improper        rdcs    rg      sym     total   vdw     vean    xpcs
../01_rigidbody/rigidbody_18.pdb        -       1       -41.375 5.426   0.167   12.678  12.679  0.183   3.959   -       -       -       63.919  0.000   0.000   1002.430        0.000    0.000   0.000   -2.235  0.000   0.218   0.000   0.000   0.000   0.000   34.165  -29.973 0.000   0.000
../01_rigidbody/rigidbody_3.pdb -       2       -39.608 5.429   0.167   12.682  12.683  0.183   3.960   -       -       -       66.601  0.000   0.000   1064.950        0.000   0.000    0.000   -0.972  0.000   0.211   0.000   0.000   0.000   0.000   37.949  -28.863 0.000   0.000
../01_rigidbody/rigidbody_4.pdb -       3       -38.346 2.885   0.467   6.910   6.911   0.427   2.127   -       -       -       34.387  0.000   0.000   829.169 0.000   0.000   0.000    -0.493  0.000   -0.417  0.000   0.000   0.000   0.000   4.483   -29.488 0.000   0.000
../01_rigidbody/rigidbody_8.pdb -       4       -38.197 2.897   0.500   6.953   6.955   0.437   2.138   -       -       -       33.501  0.000   0.000   802.477 0.000   0.000   0.000    1.238   0.000   -0.255  0.000   0.000   0.000   0.000   1.755   -31.491 0.000   0.000
../01_rigidbody/rigidbody_9.pdb -       5       -35.089 5.796   0.267   14.219  14.222  0.198   4.286   -       -       -       170.592 0.000   0.000   907.170 0.000   0.000   0.000    0.786   0.000   -2.173  0.000   0.000   0.000   0.000   142.083 -26.337 0.000   0.000
../01_rigidbody/rigidbody_17.pdb        -       6       -35.073 4.994   0.133   11.715  11.713  0.187   3.649   -       -       -       38.895  0.000   0.000   752.533 0.000   0.000    0.000   1.435   0.000   -1.153  0.000   0.000   0.000   0.000   9.523   -28.219 0.000   0.000
../01_rigidbody/rigidbody_1.pdb -       7       -34.480 4.966   0.133   11.644  11.641  0.188   3.628   -       -       -       227.812 0.000   0.000   785.911 0.000   0.000   0.000    1.636   0.000   -1.004  0.000   0.000   0.000   0.000   197.278 -29.530 0.000   0.000
../01_rigidbody/rigidbody_5.pdb -       8       -33.589 5.603   0.200   13.121  13.117  0.187   4.087   -       -       -       112.505 0.000   0.000   868.690 0.000   0.000   0.000    -2.159  0.000   -1.521  0.000   0.000   0.000   0.000   88.636  -22.348 0.000   0.000
../01_rigidbody/rigidbody_16.pdb        -       9       -33.012 2.425   0.467   6.269   6.275   0.464   1.837   -       -       -       231.200 0.000   0.000   810.196 0.000   0.000    0.000   2.399   0.000   -2.045  0.000   0.000   0.000   0.000   201.579 -27.576 0.000   0.000
```

and checking `cat run1-test/02_caprieval/capri_clt.tsv` - instead of `head`

I get:

```bash
$ cat run1-test/02_caprieval/capri_clt.tsv
########################################
# `caprieval` cluster-based analysis
#
# > sortby_key=score
# > sort_ascending=True
# > clt_threshold=4
#
# NOTE: if under_eval=yes, it means that there were less models in a cluster than
#    clt_threshold, thus these values were under evaluated.
#   You might need to tweak the value of clt_threshold or change some parameters
#    in `clustfcc` depending on your analysis.
#
########################################
cluster_rank    cluster_id      n       under_eval      score   score_std       irmsd   irmsd_std       fnat    fnat_std        lrmsd   lrmsd_std       dockq   dockq_std       ilrmsd   ilrmsd_std      rmsd    rmsd_std        air     air_std bsa     bsa_std desolv  desolv_std      elec    elec_std        total   total_std       vdw     vdw_std caprieval_rank
-       -       20      -       -39.382 1.275   4.728   1.087   0.242   0.132   11.107  2.476   0.246   0.105   11.106  2.475   3.456   0.784   49.602  15.690  924.756 111.553 -0.616   1.245   -0.061  0.281   19.588  16.551  -29.953 0.971   1
```

> realise the numbers do not match at all

There is a whole bunch of numbers here, what should be matching what?

**Comment by mgiulini** [comment]
everything is wrong in that file, the irmsd value for example should be the average over the top 4 elements of capri_ss.tsv, namely (5.426+5.429+2.885+2.897)/4 = 4.15925 != 4.728. same goes for all the other quantities (fnat, dockq, etc.)

it would be even more clear by checking `run1-test/06_caprieval/capri_ss.tsv` and `run1-test/06_caprieval/capri_clt.tsv`, which possess cluster-based information

**Comment by rvhonorato** [comment]
Ok figured it out - it has nothing to do with `extract_data_from_capri_class` 

It's indeed because of this:

> The problem is actually that this jobs variable is being shadowed without being re-ordered, From the code I assume they should be ordered by CAPRI.identificator

So by changing the type of `CAPRI.identificator` to an integer (no idea why this was a string), the list of results coming from the scheduler can be ordered - still weird why the following functions need this to be ordered but ok heh

For prosperity, it's important that this identificator is an integer because:

```python
>>> x = [str(i) for i in range(11)]
>>> y = [i for i in range(11)]
>>> x.sort()
>>> y.sort()
>>> print(x)
['0', '1', '10', '2', '3', '4', '5', '6', '7', '8', '9']
>>> print(y)
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
```
