### ISSUE TITLE
Offering an option too run in one command both setup and execution

### ISSUE THREAD

**Issue by amjjbonvin** [haddocking/haddock3#11]
It would be nice to be able to run the setup and execution of haddock in one python command instead of having to give first the setup command, change to the run dir and then run haddock.

**Comment by joaomcteixeira** [comment]
I this still intended? After merging `beta1` this option disappeared. We partially address this option with the current:

https://github.com/haddocking/haddock3/blob/4af09f1081f9fd9756274c23adfa907ec2f2b74f/src/haddock/gear/prepare_run.py#L16-L40

However, we don't do the equivalent to the previous "Recipe preparation". Should we look forward adding it back again?

**Comment by amjjbonvin** [comment]
Isn’t that setting up the entire directory structure for a run with all the various stages of the workflow?

**Comment by rvhonorato** [comment]
> I this still intended? After merging `beta1` this option disappeared. We partially address this option with the current:
> 
> https://github.com/haddocking/haddock3/blob/4af09f1081f9fd9756274c23adfa907ec2f2b74f/src/haddock/gear/prepare_run.py#L16-L40
> 
> However, we don't do the equivalent to the previous "Recipe preparation". Should we look forward adding it back again?

good catch, yes it should still exist.

**Comment by joaomcteixeira** [comment]
> Isn’t that setting up the entire directory structure for a run with all the various stages of the workflow?

Yes, but some features in alpha are not implemented. Currently, only structures, ambig files and folders are created. The quality of the configuration file is also inspected.
