### ISSUE TITLE
Messed up examples for z-restraints

### ISSUE THREAD

**Issue by VGPReys** [haddocking/haddock3#1100]
## **Module/Workflow/Library affected**

Examples in `examples/docking-protein-surface/` are wrong.

## **Expected behavior**

Should be functional with the current implementation

## **Actual behavior**

`gen_beads.sh` is not functional.

**Comment by rvhonorato** [comment]
"Examples in examples/docking-protein-surface/ are wrong." is not desctiptive, could you please explain what is the issue?

**Comment by VGPReys** [comment]
"`gen_beads.sh` is not functional"
