### ISSUE TITLE
cns is linked to extra libs

### ISSUE THREAD

**Issue by sverhoeven** [haddocking/haddock3#1114]
The cns that is installed with haddock3 is linked to libquadmath on linux/amd64 and libgfortran5 on linux/arm64.

## **Module/Workflow/Library affected**

any cns powered module

## **Expected behavior**

cns is not linked to libquadmath 
## **Actual behavior**

Without libquadmath installed cns cannot be run.
```
ldd /venv/lib/python3.9/site-packages/haddock/bin/cns
        linux-vdso.so.1 (0x00007ffc5cd20000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f54d403c000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f54d3e5b000)
        libquadmath.so.0 => /lib/x86_64-linux-gnu/libquadmath.so.0 (0x00007f54d3e14000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f54d411f000)
```

## **Suggestions on how to fix it**

recompile cns

## **Version**

main branch

## **Additional context**

In haddock3-webapp I did
https://github.com/i-VRESSE/haddock3-webapp/blob/802bfeeeac21679e2fbd53ea7f7754cb815b4b3d/deploy/Dockerfile.bartenderhaddock3#L78-L89

**Comment by amjjbonvin** [comment]
No access to a Linux/arm64 system to recompile it at this time...

**Comment by rvhonorato** [comment]
You don't need hardware access to do this for Linux, just do it inside a container:

```bash
$ export DOCKER_DEFAULT_PLATFORM=linux/arm64 
$ docker run --rm ubuntu uname -i
aarch64
$ export DOCKER_DEFAULT_PLATFORM=linux/arm64 
$ docker run --rm ubuntu uname -i
x86_64
```

You do need a machine for MacOS since the software is not open 😉

**Comment by amjjbonvin** [comment]
Is the OSX version  also an issue?

But to recompile CNS on a Linux arm64 system and test it we do need access to some hardware

**Comment by sverhoeven** [comment]
Dunno, but for running Docker container on OSX you need linux/arm64 binary.

**Comment by amjjbonvin** [comment]
Ok -  recompiled and updated - please try again
