### ISSUE TITLE
Add OpenMM to the Dockerfile

### ISSUE THREAD

**Issue by rvhonorato** [haddocking/haddock3#1115]
## **Desired feature/enhancement**

Add OpenMM installation to the dockerfile

## **Motivation**

Currently we provide haddock3 as package https://github.com/haddocking/haddock3/pkgs/container/haddock3 but with a very minimal setup;
https://github.com/haddocking/haddock3/blob/ccb3aea581e0a0a930c21f36d135edf1bbdaad06/Dockerfile#L2-L7

Ideally this package should contain the "full" suite, including extra dependencies such as OpenMM.

## **Description**

We can use https://github.com/i-VRESSE/haddock3-webapp/blob/main/deploy/Dockerfile.bartenderhaddock3 as a reference point

**Comment by sverhoeven** [comment]
In the webapp I ran openmm successfully before haddock3 required numpy=2 (on 4 oct), so image https://github.com/i-VRESSE/haddock3-webapp/pkgs/container/bartender/284614460?tag=v0.3.8 would be the image that still had working openmm.

**Comment by VGPReys** [comment]
Also now can be installed using `pip install openmm` !

**Comment by sverhoeven** [comment]
On https://pypi.org/project/OpenMM/#files there is no wheel for linux arm, 

```shell
docker run -ti --rm --platform=linux/arm64 --entrypoint bash python:3.12
root@64dc900ff4cc:/# pip install openmm
ERROR: Could not find a version that satisfies the requirement openmm (from versions: none)
```

So if you want a make a Docker image that can run on arm you will still need to compile openmm.
