### ISSUE TITLE
The parameter block 'fle1_*_1_*' is not a valid expandable parameter

### ISSUE THREAD

**Issue by zillmerhanne** [haddocking/haddock3#1166]
Hey, I'm currently trying to run the ensemble generation using the mdref-glycans-sf400x16.toml file and the following command: 
haddock3 mdref-glycans-sf400x16.toml
However, I get the following the error message:
![image](https://github.com/user-attachments/assets/baab1c11-c812-4db9-beca-516ef33fea5d)
I installed haddock3 following the instructions in the haddock3 docs on GitHub. Any idea on how to solve this problem?
Thank you for your help! 
Best, 
Hanne

**Comment by rvhonorato** [comment]
Thanks for reporting @zillmerhanne, seems like @amjjbonvin changed this definition but forgot to make it backwards compatible https://github.com/haddocking/haddock3/pull/969, that is why you are getting this error.

**Comment by zillmerhanne** [comment]
Thank you for prompt response! After changing the parameters, it works.

**Comment by amjjbonvin** [comment]
And the toml files in the protein-glycans repo have now been corrected.
