### ISSUE TITLE
number of core determination :: potential overcommit

### ISSUE THREAD

**Issue by EricDeveaud** [haddocking/haddock3#1168]
Hello,

haddock3 use `os.cpu_coun()` in `libutil.py` in `parse_ncores` function. this may cause problems in some environment, eg: taskset, batch system like slurm, etc...

python `os.cpu_count()` returns the number of physical cores available on the computer it runs on. BUT this is not the number of **AVAILABLE** cores for the running process.
eg in slurm allocation, you can run on a node with 96 cores, but only have access to **n** cores regarding the allocation.

I would suggest to use `len(os.sched_getaffinity(0))` instead of `os.cpu_count()`

a demo worth all the words.

```
# slurm allocation with 4 cores
maestro-submit:~ > srun -c 4 python3  -c "import os; print(os.cpu_count(),  len(os.sched_getaffinity(0)))"
96 4
```

means you may have for example  a job submitted on a 96 cores HPC nodes, in a single core slurm allocation: 
you will have more  threads fighting for the usage of this core.

regards

Eric

**Comment by amjjbonvin** [comment]
Indeed - but what would happen if there is no batch system? I.e. you run locally.

Our idea was that the users should be smart and define the proper number of core to be used in the config file. May-be expecting too much...

Your solution seems a good one, but should only be applied if haddock3 is executed within a batch/slurm job and this should thus be checked.

**Comment by amjjbonvin** [comment]
PS: You are welcome to contribute :-)

**Comment by EricDeveaud** [comment]
> Indeed - but what would happen if there is no batch system? I.e. you run locally.

if you run locally you will get all the available cores on the machine 

in any case you will get ALL the cores your process CAN have. 

modification will be "transparent" 
you can try on your own, and see that it won't affect the number of workers yield by haddock

```
build [rpm]:home/gensoft > nproc
64
build [rpm]:home/gensoft > python3  -c "import os; print(os.cpu_count(),  len(os.sched_getaffinity(0)))"
64 64
```


Eric

**Comment by amjjbonvin** [comment]
Thanks Eric! We will implement it.
