### ISSUE TITLE
Double logging when running jobs

### ISSUE THREAD

**Issue by joaomcteixeira** [haddocking/haddock3#117]
When running HADDOCK3 jobs after #106 on SLURM we have that the standard output is saved on both `#SBATCH -o file.out` and the `log` file. What would be your preference?

1. Keep it this way?
2. Save only in the `log` file and ignore `#SBATCH -o`
3. Make `#SBATCH -o` the `log` file, but that would be a bit against #106 in the first place.

I vote for `2`.

**Comment by amjjbonvin** [comment]
I vote for 2 as well - but I guess the queueing system logging will always be there

**Comment by joaomcteixeira** [comment]
Yes. But I can try to disable sending messages there.

**Comment by rvhonorato** [comment]
Has this been addressed?
