### ISSUE TITLE
Implement CAPRI metrics calculations

### ISSUE THREAD

**Issue by rvhonorato** [haddocking/haddock3#121]
It would be beneficial to have analysis modules capable of calculating the CAPRI metrics in the workflow; `I-RMSD`, `L-RMSD`, `I-L-RMSD` and `fnat`. 

Thinking about the usage: all metrics should be evaluated by the same module, but in a scenario in which the user does not need all of them, it should have an option to select which are going to be evaluated and which are skipped.

How could we name this module? `capricalc`, `caprieval`? Open to suggestions.

**Comment by joaomcteixeira** [comment]
`calccapri` or `caprieval` sound nice. `capricalc` sounds strange to me.
`caprimetrics` is also good.

However, having all CAPRI metrics in the same module reduces modularity, despite using the flags. we could we this opportunity to have higher-level modules that control several modules. But for the time being, we can implement all that in one module and then we can think of that further improvement. Let's start with the easiest setup first.

**Comment by amjjbonvin** [comment]
I would have all metrics into the same module with possible flag options (default should be `-all`) to select specific ones.

And for a name I would vote for `caprieval`

But we might need different modules for different types of complexes/metrics, e.g. protein-protein, protein-peptide…

And even think of giving as configuration option the cutoffs to define a given quality.

**Comment by joaomcteixeira** [comment]
Closed by #130
