### ISSUE TITLE
Definition of input PDB files in the CNS scripts

### ISSUE THREAD

**Issue by amjjbonvin** [haddocking/haddock3#126]
The current implementation of defining the input PDB files in the CNS script directly calls the coordinate file, e.g.:

```coor @@/Users/abonvin/haddock_git/haddock3/examples/docking/run1/01_rigidbody/rigidbody_0.pdb
```
This is problematic for when random removal of restraints is turned on (currently not working) since we also need to read a corresponding seed file.
It would be better for all modules to encode first the PDB file into a variable which can subsequently be used in the CNS script, e.g. something like:

```
evaluate ($input_pdb_filename="/Users/abonvin/haddock_git/haddock3/examples/docking/run1/01_rigidbody/rigidbody_0.pdb")
cool @@$input_pdb_filename
```

This will allow to define later in the script the seed file to be read as:
```
evaluate ($fileseed=$input_pdb_filename - ".pdb" + ".seed")
```
```

**Comment by rvhonorato** [comment]
Does this also apply to the other CNS-based modules `flexref` and `mdref`?

**Comment by amjjbonvin** [comment]
Yes - applies to all modules - but already implemented something :-)  Learning my way through the python code.
So wait before doing anything
