### ISSUE TITLE
Refactor `clustfcc` to use fccpy

### ISSUE THREAD

**Issue by rvhonorato** [haddocking/haddock3#133]
`clustfcc` needs to be refactored to use fccpy before we can update the install instructions.

_Originally posted by @rvhonorato in https://github.com/haddocking/haddock3/pull/131#pullrequestreview-813388060_

**Comment by joaomcteixeira** [comment]
Well spotted!!!!

**Comment by rvhonorato** [comment]
Take also this one please @joaomcteixeira (:

**Comment by rvhonorato** [comment]
The idea of this is to remove the hard dependency os compiling C++ binaries so that haddock3 can be executed;

https://github.com/haddocking/haddock3/blob/0320d5add2bbd6c9483ea4603e1cd9d3c267b80c/docs/INSTALL.md?plain=1#L29-L32

and fccpy uses a python implementation instead of c++ code, however its not yet ready for integration and this migration might be quite disruptive since we'll need to confirm that the results match and possible make changes to the source of fccpy.
