### ISSUE TITLE
`HETATM` lines are removed before creating topologies

### ISSUE THREAD

**Issue by joaomcteixeira** [haddocking/haddock3#151]
`HETATM` lines are removed before creating topologies.

Find where and correct :relaxed:

**Comment by joaomcteixeira** [comment]
Also, https://github.com/haddocking/haddock3/pull/156#issuecomment-981112605

**Comment by amjjbonvin** [comment]
Must have been solved by @rvhonorato  since the protein-ligand example is running fine

**Comment by rvhonorato** [comment]
Yes, fixed with https://github.com/haddocking/haddock3/pull/156/commits/5dbeca5ca16fa9751c0093cd0772f71f94e2ef9e
