### ISSUE TITLE
Fault tolerancy

### ISSUE THREAD

**Issue by joaomcteixeira** [haddocking/haddock3#160]
We discussed this in the last group meeting:

Implement fault tolerance when running modules so that the run don't break if some (user-defined percentage) of models fails. The run should continue without breaking.

Also, sometimes, models fail because of the initial seed number. In those cases, HADDOCK3 should change the seed number and relaunch the subprocess.

**Comment by amjjbonvin** [comment]
This one has been implemented - closing
