### ISSUE TITLE
Do not write empty parameter to CNS input

### ISSUE THREAD

**Issue by rvhonorato** [haddocking/haddock3#162]
We need to refactor the config gears to not write empty parameters to the CNS input files.

_Originally posted by @rvhonorato in https://github.com/haddocking/haddock3/issues/161#issuecomment-981648329_

and we need of course to define what is the standard way of defining empty parameters in the `defaults.cfg`

I vote for `variable = None`, which should be used for booleans, string, integers and floats.

**Comment by joaomcteixeira** [comment]
The only thing you need to NOT write variables to the CNS file is to filter out the `None`s in this loop:

https://github.com/haddocking/haddock3/blob/09505863e8747bc379d33ea49059201cd1be87e9/src/haddock/libs/libcns.py#L32

Writing `variable = None` is the most pythonic way to do it.

**Comment by amjjbonvin** [comment]
A Boelean should be either true or false and never none 

A string can be empty, I.e. “”

Number could be None

Then when you look at the default file you know what is expected

**Comment by joaomcteixeira** [comment]
Okay. So we need to add some type checking also. Will do that in #163.

**Comment by joaomcteixeira** [comment]
Question. Does CNS handle scientific nomenclature in numbers? "13E-14" for example.

**Comment by amjjbonvin** [comment]
Not that I am aware of

**Comment by joaomcteixeira** [comment]
I had misunderstood the requirements. Empty strings `""` **must** be written to the CNS file.
