### ISSUE TITLE
Add multibody support to `caprieval`

### ISSUE THREAD

**Issue by rvhonorato** [haddocking/haddock3#164]
We can align on chain A and calculate the metrics or simply produce all combinations of interfaces; `A_BC, B_AC, C_AB`, ligands; `A_BC, B_AC, C_AB, AB_C, AC_B, BC_A` etc. 

Which should I implement @amjjbonvin ?

**Comment by amjjbonvin** [comment]
I would go for aligning on A and calculating on the other chains. Not perfect anyway

But the issue of permutations of chains when doing the comparisons is more important as the order of chains might be different than the reference, even if the overall 3D structure is the same

**Comment by rvhonorato** [comment]
Since are starting from scratch in this module, I can also look into implement some chain-matching algorithm here

**Comment by rvhonorato** [comment]
related to #179
