### ISSUE TITLE
Review absolute/relative paths

### ISSUE THREAD

**Issue by joaomcteixeira** [haddocking/haddock3#165]
> > 2. Question 1: When adding paths to the CNS files, do you want them to be absolute or relative to the CWD or where the config file is?

> It could be defined with respect the MODDIR variable (this of course assumes that all data are within the user directory where haddock3 is called from

Not really. But I need to review this calmly.

_Originally posted by @amjjbonvin in https://github.com/haddocking/haddock3/issues/163#issuecomment-983592767_

**Comment by amjjbonvin** [comment]
@joaomcteixeira isn't this one solved?

**Comment by joaomcteixeira** [comment]
Yes. Currently, there are no additional ideas referring to paths. All paths are treated relative to the current directory. The current directory changes to the modules' dir at each step. Also the `self_contained` option is working.
