### ISSUE TITLE
Add `nan` to `None` options.

### ISSUE THREAD

**Issue by joaomcteixeira** [haddocking/haddock3#172]
https://github.com/haddocking/haddock3/blob/f21787624358f192b69f75f64fceede699adb2ff/src/haddock/gear/config_reader.py#L49

Integration with https://github.com/i-VRESSE/workflow-builder/pull/1

**Comment by joaomcteixeira** [comment]
@sverhoeven if you decide on any different name/word just let me know here.

**Comment by sverhoeven** [comment]
I had a look at the toml spec and repo. There are some closed issues to add null type to toml like using `{}` or `somekey = ` as null. Which you could also add?

In the js toml library (https://www.npmjs.com/package/@ltd/j-toml) I am using, I can read/write `somekey = null` with `{xNull: true}` option. So I think I will use that library option over using `nan`.

**Comment by joaomcteixeira** [comment]
that's perfect. `null` is supported already by our configuration file reader.

**Comment by joaomcteixeira** [comment]
FYI, when using the haddock3's configuration file reader, `value = nan` is converted internally to `float('nan')` in Python. Accepts also any caps variation of `nan` (`NaN`, etc). While `value = None` or `value = null` are converted to python `None`.
