### ISSUE TITLE
Implement chain-matching/check in `caprieval`

### ISSUE THREAD

**Issue by rvhonorato** [haddocking/haddock3#179]
Currently there's no check if the chains of the reference matches the model, we should implement a chain-matching subroutine.

**Comment by rvhonorato** [comment]
Closing this for now because there's no simple way of doing the chain-matching without adding a sequence/structural alignment dependency (as far as I know).

**Comment by joaomcteixeira** [comment]
On the contrary, leave it open, otherwise, I forget it exists. :relaxed:

**Comment by rvhonorato** [comment]
Partially addressed in #230

**Comment by rvhonorato** [comment]
has this been addressed @mgiulini ?

**Comment by mgiulini** [comment]
hi @rvhonorato, I somehow missed this message. 
Nope, it's still an open issue. I can take care of this, but maybe it's better to have a chat on the best way to solve the problem.
