### ISSUE TITLE
Add sampling parameter to refinement modules

### ISSUE THREAD

**Issue by rvhonorato** [haddocking/haddock3#186]
Should be similar to what is done for `rigidbody`

**Comment by rvhonorato** [comment]
Should we add this parameter per-model or in total @amjjbonvin? 

To me it makes more sense to do it per-model:
`samping_factor = 20` would sample each conformation 20 times etc

Can quickly explode but we can also add a limiter specially since it might not make too much sense to sample 1 conformation 1000 times?

**Comment by amjjbonvin** [comment]
Per model makes indeed more sense.

But would that possibly also affect the regular docking workflow?
You don’t want to have the number of `rigidbody` models increased by that factor.
Or the default should be 1

**Comment by rvhonorato** [comment]
yes we can set the default to 1 so it would not affect anything, but then we can get creative with it and try some sort of "supersampling" protocol 😄 

`rigidbody > select top 10 > refine with factor 10`

**Comment by amjjbonvin** [comment]
We have now much more flexibility indeed! Nice

Or cluster after rigid body and then refine
