### ISSUE TITLE
Make `libcns` use all supported restraints

### ISSUE THREAD

**Issue by rvhonorato** [haddocking/haddock3#208]
Currently `libcns` supports various restraints but only `ambig` is written via the `prepare_cns_input` function, we should thus refactor this function to take all possible restraints into account when preparing the `.inp`.

Here they should use full paths.

**Comment by rvhonorato** [comment]
In the modules I see:
```
ambig_fname = ""
unambig_fname = ""
hbond_fname = ""
```

There is no
```
rdc_fname = ""
pcs_fname = ""
dan_fname = ""
dihe_fname = ""
```

Should these also be defined and used in the `.inp` @amjjbonvin ?

**Comment by amjjbonvin** [comment]
Yes better be ready for the rdc and other restraints even if not currently supported.

Also dihedral_fname should be included (I need to also add it to the relevant modules)

**Comment by joaomcteixeira** [comment]
I think after #219 this issue will be solved. I made quite drastic changes there.

**Comment by joaomcteixeira** [comment]
Actually, yes. any `_fname` you send in the configuration file will be converted to path and copied to `run_dir/data/` by `prepare_run` and will be used by `prepare_cns_input` function.
