### ISSUE TITLE
Add rank to the `caprieval` module output

### ISSUE THREAD

**Issue by amjjbonvin** [haddocking/haddock3#212]
The current `capri.tsv` generated output file would benefit from adding a rank column, either as first or second column.

**Comment by rvhonorato** [comment]
What should the ranking be based on, the same value that is being used to do the sorting or should it be another parameter?

**Comment by amjjbonvin** [comment]
The HADDOCK rank, i.e. based on the scoring function. 
Now you have to get the line number - 1 to figure out the rank.
Having the rank in the file makes it easier to analyse the data

**Comment by rvhonorato** [comment]
So the rank should always be the score? Probably also good to have a something there to handle situations in which the score should be ranked descending/ascending.

**Comment by amjjbonvin** [comment]
> So the rank should always be the score?
> 
It should be the order in the capri.tsv file since we can specify something else than the score for the sorting (the `sortby` parameter).
The default is the score
> Probably also good to have a something there to handle situations in which the score should be ranked descending/ascending
> 

Already there since it is a parameter in the `default.cfg` file (`ascending = true`) - but what happens if set to `false`? will it be descending then?
