### ISSUE TITLE
Make `libhpc` use `/tmp`

### ISSUE THREAD

**Issue by rvhonorato** [haddocking/haddock3#217]
We discussed that this is done to reduce I/O. 

What should we use `tmp` for? Should the `.out`, `.inp`, `.pdb` or what else?

How should we handle the moving these files back to the working directory, in the `.job` (via bash) or in the python-shell? Should this moving also be one HPC job?

**Comment by amjjbonvin** [comment]
The complete run dir should be created and run under /tmp and only at the end moved back to its original location.

If we use relative environment variables this should be rather simple. 
The input data can reside on the original dir in principle since not read that often.
Or all input data should be copied to the run and the modules adapted to read from the local directories (as is the case in 2.4)

**Comment by rvhonorato** [comment]
> The complete run dir should be created and run under /tmp and only at the end moved back to its original location.

This would be the case when sending the haddock process to the queue and running it on multiprocessing, right? How about for the batch-jobs in which each one could be in a different node, then the `.out` should go to `/tmp`?

**Comment by amjjbonvin** [comment]
> The complete run dir should be created and run under /tmp and only at the end moved back to its original location.
> 
> This would be the case when sending the haddock process to the queue and running it on multiprocessing, right? How about for the batch-jobs in which each one could be in a different node, then the .out should go to /tmp?
> 
Yes indeed. Creating a unique ID dir first where the files are written as we might have multiple runs generating similar outputs.

Haddock2.5 uses for example:

```
                    if [ -e /tmp ]; then
                        export TMPDIR=/tmp/`uuidgen`
                    else
                        export TMPDIR=./`uuidgen`
                    fi
```

**Comment by amjjbonvin** [comment]
PS: And of course those tmp dirs must be deleted once the output has been moved back

**Comment by joaomcteixeira** [comment]
To contribute to the discussion:

After #219:

* files referred in the configuration file as `molecules` or any parameter ended with `_fname` are copied to the `data/` directory inside the `run_dir`. 
* All modules then take the input data from that `data/` directory using **relative** paths.
* All modules take the required data from previous modules using relative paths.
* On top of that, if we use the `self_contained=true` general flag in the config file, also the `cns` executable, the `toppar` library and the per module's `cns/` files will be copied to the corresponding places in the `run_dir`. Making the `run_dir` absolutely self-contained.
* if `self_contained=true`, an `envvars` file is created in each module's folder. If you `source envvars` from inside the module's folder you can safely run `../cns < in > out`.

**Comment by amjjbonvin** [comment]
This will be more for debugging purpose.

For a real run on a remote node using /tmp, we would still call haddock3, but then all files and paths would be relative to the rundir residing on /tmp


> 
> if self_contained=true, an envvars file is created in each module's folder. If you source envvars from inside the module's folder you can safely run ../cns < in > out.

**Comment by rvhonorato** [comment]
Bump!

I see on 2.5 that the tmp dir is used to save the `.out` file, its quite simple to implement here, just need to change the header of the batch script. Maybe putting the files that a single `.inp` will need in the tmp directory will speedup the computation, but there might be some tradeoff in the transfer of files, have you ever measures the impact of running it on or off /tmp? (this is not specifically related to haddock3, but with the host system )

**Comment by amjjbonvin** [comment]
I see you are already trying things outs.

Two points:

1) If we were speaking of only one job writing over the network if would not matter much. But it will when hundreds of jobs are writing simultaneously.

2) The amount of data transfered will be reduced when using /tmp if you first gzip the files
