### ISSUE TITLE
Ensemble docking not working for protein-peptide example

### ISSUE THREAD

**Issue by amjjbonvin** [haddocking/haddock3#221]
While the protein-protein example is working fine starting from an ensemble of models for molecule2, the same scenario does not work for the protein-peptide example with only one model being used...

Strange. Could it be due to the length of the filename?

Even after running `pdb_tidy` on the ensemble and adding the chain (is currently missing, but the segid is present) the same issue remains.

**Comment by amjjbonvin** [comment]
Or something is fishy about that PDB ensemble as even `pdb_splitmodel` does not work properly. But nothing obvious to me.

**Comment by rvhonorato** [comment]
The error is not HADDOCK related, it happens because of the `MODEL` records of `data/DAIDALSSDFT_3conformations.pdb` are not formatted correctly `pdb-tools.splitmodel` extracts the identifier from position `10:14` in the MODEL line, as per PDB standard:

```
COLUMNS        DATA  TYPE    FIELD          DEFINITION
---------------------------------------------------------------------------------------
 1 -  6        Record name   "MODEL "
11 - 14        Integer       serial         Model serial number.
```

However for this conformation the `1` is not in the correct position
```python
>>> peptide_model_line = 'MODEL 1'
>>> line[10:14].strip()
''
>>> expected_model_line = 'MODEL        1                                                             '
>>> line[10:14].strip()
'1'
```

Anyway we should detect that the PDB is not properly formatted and raise an error.

**Comment by amjjbonvin** [comment]
I recreated the ensemble with `pdb_mkensemble` and now it is working. Could it the the model number was not at the right column?  I guess none of the pdb-tools check for that.

**Comment by rvhonorato** [comment]
@amjjbonvin we replied at the same time 😄

**Comment by rvhonorato** [comment]
> Anyway we should detect that the PDB is not properly formatted and raise an error.

But this probably goes into #144, so closing this one.

**Comment by amjjbonvin** [comment]
Shouldn’t may-be pdb_tidy report that error?
I.e a pdb-tools issue?

**Comment by rvhonorato** [comment]
Indeed `pdb_tidy` should fix this, will open an issue over at `pdb-tools`

**Comment by joaomcteixeira** [comment]
The new `pdb_tidy` version corrects model index position, model numbering and `ENDMDL` lines.
