### ISSUE TITLE
Add documentation on how to build CNS

### ISSUE THREAD

**Issue by antonkulaga** [haddocking/haddock3#222]
There is an ancient relict that haddock3 depends on called CNS that I understand you, unfortunately, cannot remove yet ( at least according to https://github.com/haddocking/haddock3/issues/82 ). 
Building it is a total nightmare as it has a lot of errors after the build, like:
```
%SETFPEPS increase value of MXFPEPS2 and recompile
 %SETFPEPS error encountered: Could not determine machine epsilon
```
In haddock2 you had some patches to compile CNS properly, however, there is zero information on how to build CNS for haddock3 master.

**Comment by rvhonorato** [comment]
> however, there is zero information on how to build CNS for haddock3 master.

As we have written in the project's `README`
*WARNING: The main branch is not production-ready*

We are still in the process of making sure the modules are doing what they should, once this is done we will move on to prepare the build documentation. 😉

**Comment by antonkulaga** [comment]
Sorry for the stupid question, but I am trying to find 2.4 version of modified CNS compilation files (to use them to build CNS for haddock 3) but could not locate version 2.4 on github. I filled a website form to get 2.4 distribution because of that.

**Comment by amjjbonvin** [comment]
2.4 is not freely available from GitHub.

You can request it via bonvinlab.org/software

**Comment by antonkulaga** [comment]
I see. I filled the google form for haddock 2.4 What I really need there is CNS build fixes. Maybe it makes sence to put them somewhere, as asking for permission to use haddock 2.4 in order to recompile CNS in public haddock3 is a bit overkill

**Comment by amjjbonvin** [comment]
As already explained haddock3 is  
in heavy developttmw d 
=================================
 Prof. A.M.J.J. Bonvin | Faculty of Science
 Scientific Director Bijvoet Centre
 Utrecht University | bonvinlab.org 
 ***@***.*** | T: +31 30 2533859 
=================================

**Comment by amjjbonvin** [comment]
As already explained haddock3 is in heavy development and not yet a production version… better use 2.4 for the time being

**Comment by antonkulaga** [comment]
>better use 2.4 for the time being

Ok, waiting for the access for non-profit distribution of haddock 2.4 then...

**Comment by antonkulaga** [comment]
Thanks for the download access.
So far I am totally blocked by CNS 
```
%SETFPEPS Machine epsilon determined to be  0.494-323
%SETFPEPS error encountered: Machine epsilon value is too small
```
I have tried recipes at https://ask.bioexcel.eu/t/cns-errors-before-after-recompilation/54 but nothing worked so far.
My OS is Linux Mint 20.02

**Comment by rvhonorato** [comment]
done with #469
