### ISSUE TITLE
Allow runs to continue in case of a few failures

### ISSUE THREAD

**Issue by amjjbonvin** [haddocking/haddock3#227]
Currently the workflow will stop if one model fails. This is quite commonly happening (e.g. exploding models in the flexible refinement). HADDOCK2.4 has a mechanism to deal with that, restarting the job and only doing an EM step.

A simple alternative for the time being would be to allow a run to continue if less than a user-defined percentage fails (e.g. 5% as default). At least the workflow will complete in most cases, unless there is something seriously wrong and most models fail.

**Comment by joaomcteixeira** [comment]
Scheduled to implement after #219

**Comment by rvhonorato** [comment]
It seems to me the best way to implement this is per-module, for examples some models not being generated in `rigidbody` is fine, but all models must be generated by `topoaa`.

**Comment by amjjbonvin** [comment]
Yes indeed


A simple solution for now it to define a threshold at which the workflow would stop, e.g. if more than 5% of the models fail.

And later we can implement fixes and try to rerun the failing models, but the fix will depend on the module, e.g.:

- rigidbody docking:  change random seed and try again
- flexref: run only EM
- mdref: run only EM
