### ISSUE TITLE
Run executes despite `tbl` files are not found

### ISSUE THREAD

**Issue by joaomcteixeira** [haddocking/haddock3#228]
While developing #219 I found that, for example, in `rigidbody` when calling `prepare_cns_input`, even if the `self.params["ambig_fname"]` file does not exist, the run proceeds without any error.

What is the behaviour we should implement? Should the python shell check for that, or should it be handled by CNS?

**Comment by amjjbonvin** [comment]
Doesn’t have to be present.
What we should check is if any file defined by the user in the config file does exist

**Comment by joaomcteixeira** [comment]
Okay. :+1:
