### ISSUE TITLE
Accept ProFit definitions in `caprieval`

### ISSUE THREAD

**Issue by rvhonorato** [haddocking/haddock3#229]
For comparison purposes with 2.4, we should make sure `caprieval` can accept `.izone` and `.lzone` files and define the regions accordingly.

**Comment by rvhonorato** [comment]
Is this still relevant @amjjbonvin ?

**Comment by amjjbonvin** [comment]
Not a high priority feature - now you can not manually define the fitting regions which might make comparison with 2.4 a bit difficult (but in principle we follow the same CAPRI rules).

So can be closed
