### ISSUE TITLE
Protonation state is never read

### ISSUE THREAD

**Issue by joaomcteixeira** [haddocking/haddock3#231]
https://github.com/haddocking/haddock3/blob/0e1eec71ff00f506081aca107c30125f805c28c9/src/haddock/modules/topology/topoaa/__init__.py#L120-L126

No parameters are passed to `protonation`, never. In `libcns` we have a function that writes the `CNS` header to accommodate the `protonation` state of the run. https://github.com/haddocking/haddock3/blob/0e1eec71ff00f506081aca107c30125f805c28c9/src/haddock/libs/libcns.py#L228

But this function is always called with `protonation=None`, meaning it always returns an empty string. This function is  (expected) used for `topoaa`, `rigidbody`, and the `refinement` modules.

This function is new to me. Can you tell me when do we need this function so that I can think about how to pass the parameters properly, and when?

Cheers,

**Comment by amjjbonvin** [comment]
Used for topoaa - when manually defining the protonation state of HIS (I assume).

The protein-protein example does define the HIS manually:

```
[topoaa]
autohis = false
[topoaa.input.mol1]
nhisd = 0
nhise = 1
hise_1 = 75
[topoaa.input.mol2]
nhisd = 1
hisd_1 = 76
nhise = 1
hise_1 = 15
```

**Comment by joaomcteixeira** [comment]
I thought that, but I was not sure. Therefore, I think those parameters are never used in CNS or at least they do not go through the `load_protonation_state` function. I will inspect this.

**Comment by joaomcteixeira** [comment]
Old function that is not used anymore. will be removed with #219

**Comment by amjjbonvin** [comment]
So this is not really a bug but rather unused code...
