### ISSUE TITLE
`caprieval` does not take the best ranked model as reference

### ISSUE THREAD

**Issue by amjjbonvin** [haddocking/haddock3#232]
When using the `caprieval` module without specifying a reference it should take the best ranked model according to the HADDOCK score. Instead it uses model #1. See the following example taken from the protein-ligand example:

```
(haddock3) bash-3.2$ more capri.tsv
          model                 rank     score     irmsd      fnat     lrmsd    ilrmsd
04_flexref/flexref_3.pdb           1  -168.214     0.290     0.938     0.915     0.865
04_flexref/flexref_1.pdb           2  -166.237     0.000     1.000     0.000     0.000
04_flexref/flexref_4.pdb           3  -145.566     0.574     1.000     1.662     1.662
04_flexref/flexref_5.pdb           4  -128.032     0.602     0.812     1.385     1.248
04_flexref/flexref_2.pdb           5   -98.824     0.444     0.938     0.832     0.756
```

The reference used should have been `flexref_3.pdb`

**Comment by rvhonorato** [comment]
This happens because it expects that the previous output was sorted. Will add a patch to sort by score regardless of the previous model sorting.

**Comment by amjjbonvin** [comment]
> This happens because it expects that the previous output was sorted. Will add a patch to sort by score regardless of the previous model sorting.
> 
> 

Which is never the case it seems… Shouldn’t we then sort the sampling and refinement module output according to the haddock score by default?
