### ISSUE TITLE
CYA ion

### ISSUE THREAD

**Issue by joaomcteixeira** [haddocking/haddock3#242]
https://github.com/haddocking/haddock3/blob/96eb94108fee3c4785bf532b38cdd351c2c33910/src/haddock/cns/toppar/hemes-allhdg.top#L528-L534

should this be in `ion.top` instead together with the multi-atom ions?

**Comment by amjjbonvin** [comment]
Nope - CN can bind to heme groups (and actually kill you) so it logically belongs here.

**Comment by joaomcteixeira** [comment]
Right you are. Perfect :-)
