### ISSUE TITLE
Implement a module-based restart 

### ISSUE THREAD

**Issue by rvhonorato** [haddocking/haddock3#259]
Based on @amjjbonvin comment on the module execution:

Our current implementation is based on the stage, would be beneficial if we could have a way to **also** restart based on the module: Let's say you are running a very large sampling on `rigidbody` and its taking hours, and for some reason the execution is halted (queue time, some CNS errors, power failure), we'd then need to start again and loose all the models generated.

**Comment by joaomcteixeira** [comment]
Duplicated with https://github.com/haddocking/haddock3/issues/118
