### ISSUE TITLE
Numbers should be numbers

### ISSUE THREAD

**Issue by joaomcteixeira** [haddocking/haddock3#278]
https://github.com/haddocking/haddock3/blob/e3bc51b87d9d383393bb2c3700433de16eac05ed/examples/docking-protein-homotrimer/docking-protein-homotrimer.cfg#L41-L42

How does CNS read these?
Currently, numbers provided in the HADDOCK3 configuration file are written in CNS as:

`eval ($param = 1)`

However, the above example is written as:

`eval ($ncs_end1_1="128" )`

Is there any difference for CNS about the `""` around numbers? Are those different as in Python? As long as numbers are expected to behave as numbers, we should write numbers in the haddock3 configuration files, it helps much the whole parsing and validations. Likewise with strings. But if `ncs_end1_1` is actually a string, let me know. PRs like #274 and #277 will be much facilitated if we are exact about this.

Also, strings like `"N.A."` in the defaults configs should be converted to `nan` (#172), it will help parse and validate the parameters.

**Comment by amjjbonvin** [comment]
Cns has a decoder / encoder for string to number conversion

If we remove all quotes from the numbers all cns scripts must be updated…

And nan is not something cns will understand

**Comment by joaomcteixeira** [comment]
So, our CNS scripts need numbers between quotes, for example: "129". Is that correct? If so, I need to update `libcns` to add quotes to numbers. After we can use real numbers in user configs to distinguish them from strings at the python shell level (remember we need max, min, etc).

We can write `"N.A."` to the CNS, but I suggest we have `nan` written by the user to distinguish from string values. The python will then convert it to `"N.A."`.

Do you agree?

**Comment by amjjbonvin** [comment]
No - it is script-dependent… 

We can loose the quotes for the numbers but this will require changing some cns scripts

**Comment by amjjbonvin** [comment]
The N.A. Should not be written to the cns input 

If not defined then it should not be needed 
> We can write "N.A." to the CNS, but I suggest we have nan written by the user to distinguish from string values. The python will then convert it to "N.A.".
> 
> Do you agree?

**Comment by joaomcteixeira** [comment]
Currently the "N.A." are written following the python shell. but I will
correct that.

For the numbers we should normalize the behaviour. Best would be:

1. In haddock user config, numbers should be numbers
2. in the user haddock config, numbers that are not defined and hence
should NOT be written to CNS should have the `nan` value
3. numbers written to CNS can have (or not) the quotes ", as you prefer.
But the same behaviour should apply to all cns scripts

This would be a clean implementation in my opinion. Right now we have
expexted numbers defined as `""` (empty strings) in the defaults.

**Comment by amjjbonvin** [comment]
In order to start cleaning the `default.cfg` files and adapt if needed the cns scripts I need to be able to run the example.
Is there already a branch allowing for the `nan` definition for numbers? 

I tried both N.A and nan and both are not accepted.

> 2. in the user haddock config, numbers that are not defined and hence
> should NOT be written to CNS should have the `nan` value

**Comment by joaomcteixeira** [comment]
Added in https://github.com/haddocking/haddock3/pull/280
```
git checkout main
git pull
git checkout default_clean
```
