### ISSUE TITLE
`alascan` for analysis module.

### ISSUE THREAD

**Issue by joaomcteixeira** [haddocking/haddock3#290]
It is a nice analysis module!

_Originally posted by @amjjbonvin in https://github.com/haddocking/haddock3/issues/272#issuecomment-1021993275_

**Comment by mgiulini** [comment]
hi @rvhonorato are you going to take care of this? if not, can I implement it?

**Comment by rvhonorato** [comment]
This is on the bottom of my list, please go ahead if you have time now @mgiulini. My first implementation was here: https://github.com/haddocking/haddock3/pull/272
