### ISSUE TITLE
Implement a default method for clustering.

### ISSUE THREAD

**Issue by joaomcteixeira** [haddocking/haddock3#30]
Implement a default method for clustering at: `haddock/modules/clustering/default.py`

**Comment by amjjbonvin** [comment]
Based on the HADDOCK clustering methods? I.e. either RMSD or FCC?

**Comment by rvhonorato** [comment]
We can set the default to FCC and implement it directly. Would it be a viable option? Similar to what it was in the alpha: https://github.com/haddocking/haddock3/blob/alpha1/haddock/modules/analysis/fcc.py

We will still need RMSD clustering based on the moleculetype; for that I'd suggest we improve on the PROFIT wrapper I made for gdock: https://github.com/rvhonorato/gdock/blob/master/modules/profit.py

**Comment by amjjbonvin** [comment]
In principle RMSD calculations in haddock2.4/5 are handled by CNS - and there are many reasons for that (e.g. defining the interface for fitting and such).
It does take quite some time, but is doing the job.

We are clustering based on what we call the  ligand interface RMSD, i.e. fitting on the interface of the 1st molecule and calculating the RMSD on the interface of the other molecules.

And those interfaces are defined automatically by analysis first all models and identifying residues in the interface.

Not sure the same can be done easily with profit…
Will also need to handle or filter out ligands, shapes, tensors…

**Comment by rvhonorato** [comment]
I see in the code that this is done with [protocols/rmsd.inp](https://github.com/haddocking/haddock/blob/a53d5becc08edd4356b90197091b0b5a8fd36413/protocols/rmsd.inp), based on our modular philosophy this would need to become its own standalone independent module, none of the analysis (in alpha1) was done in CNS since it was ported to python (was not an easy task 😅).

When the time comes we should think of what will be simpler to do, transform CNS-RMSD into a standalone module (we need to handle the reading of the coordinates/topology and output), implement another solution or find a brave volunteer to do a pure-python rmsd calculation.

**Comment by amjjbonvin** [comment]
> When the time comes we should think of what will be simpler to do, transform CNS-RMSD into a standalone module (we need to handle the reading of the coordinates/topology and output), implement another solution or find a brave volunteer to do a pure-python rmsd calculation.
> 
> 

A standalone module sounds good - there wasn’t any clustering implemented thus in the alpha version?

Reading in the files should not be an issue, this is also happening for other modules.

**Comment by rvhonorato** [comment]
> A standalone module sounds good - there wasn’t any clustering implemented thus in the alpha version?

Think so too, the previous had only FCC

**Comment by amjjbonvin** [comment]
OK- so two different clustering modules then :-)


The RMSD one is required for small ligands and peptides for example

**Comment by rvhonorato** [comment]
@joaomcteixeira the default clustering technique can change based on the molecule type, RMSD for small ligands, peptides, glycans and FCC for proteins, nucleics.

Does it still make sense to have a default method?

**Comment by joaomcteixeira** [comment]
No it doesn't. Also, after our discussion yesterday, we have discarded the concept of a "default" method *per se*.
