### ISSUE TITLE
Add description for `run_dir` and `molecules`

### ISSUE THREAD

**Issue by joaomcteixeira** [haddocking/haddock3#304]
After #274 and https://github.com/i-VRESSE/workflow-builder/pull/22

> Main problem is, that I have to define molecules and run_dir parameters myself. I would like to fetch the type/title/description from haddock3. @sverhoeven

I will add those. It is not straightforward that those parameters should be in the `modules/defaults.yaml` file or in another one. Because these are parameters without defaults and mandatory. Well, `run_dir` could have a default, but not `molecules`.

**Comment by sverhoeven** [comment]
For reference I defined them at https://github.com/i-VRESSE/workflow-builder/blob/9732c9e9403826a701bff9126f8a38aa6ac20f00/util/generate_haddock3_catalog.py#L206-L223
