### ISSUE TITLE
Never use split on PDBs

### ISSUE THREAD

**Issue by rvhonorato** [haddocking/haddock3#309]
As discussed elsewhere, we must never use split on PDB files. So we should replace the following asap:

https://github.com/haddocking/haddock3/blob/d5f5cd8be6fa7e35fdb18f69ddf37479354979c3/src/haddock/gear/haddockmodel.py#L20

**Comment by amjjbonvin** [comment]
What is this? If we input an ensemble of models it must be split for haddock to process it (e.g. scoring scenario). Or are we speaking about another split here?

**Comment by joaomcteixeira** [comment]
This does not apply because line is `REMARK`.
