### ISSUE TITLE
Re-implement basic features

### ISSUE THREAD

**Issue by rvhonorato** [haddocking/haddock3#32]
We dropped the `alpha` development branch in favor of a more robust code and development direction, however it currently does not have the basic features that were present in the `alpha`. 

This set us back quite a bit since we need to re-implement the features in the new code; to put it back in line I've split the basic modules between `implemented`, `tested` (covered by unit tests) and the workflows between `implemented` and `benchmarked`

* * *
## Core Modules Implemented

- [X] Topology generation
- [x] Rigid body sampling (`rigidbody`)
- [x] Semi-flexible refinement (`flexref`)
- [x] Water refinement (`mdref`)
- [x] Final EM (`emref`)
- [x] Analysis (`clustfcc`)
- [x] Analysis (`caprieval`)
- [X] Scoring

## Core Modules Tested

- [ ] Topology generation
- [ ] Rigid body sampling (`rigdock`)
- [ ] Semi-flexible refinement (`flexref`)
- [ ] Water refinement (`mdref`)
- [ ] Final EM (`emref`)
- [ ] Analysis (`clustfcc`)
- [ ] Analysis (`caprieval`)
- [ ] Scoring

***

## Core Workflows Implemented

- [x] Docking
- [X] Scoring

**Comment by joaomcteixeira** [comment]
Very nice @rvhonorato Thanks for putting it in a task list form.
I believe @amjjbonvin had considered renaming it0, it1, and itw.

**Comment by amjjbonvin** [comment]
> I believe @amjjbonvin <https://github.com/amjjbonvin> had considered renaming it0, it1, and itw.
> 
> 

Yes indeed! The old naming very much implies a sequential and fixed protocol.

I would rather name those:

- rigid-docking, eg.g rigdock 
- flexible refinement, e.g. flexref
- water refinement, e.g. water
- final EM, e.g. EMref

Then we can mix and match to create custom protocols

**Comment by rvhonorato** [comment]
Change the names to match the new naming!

> - final EM, e.g. EMref

This name implies (at least for me) that this module could only be used in the last step of the workflow, is that it?

**Comment by amjjbonvin** [comment]
No EMref is generic in principle - but it is currently the final stage in haddock2.4

**Comment by rvhonorato** [comment]
Full docking possible again after #67  🥳

**Comment by rvhonorato** [comment]
We wrap this one up with #177
