### ISSUE TITLE
Error running example configs

### ISSUE THREAD

**Issue by jordantwells42** [haddocking/haddock3#329]
Hello,

I am getting an error across my own config files and the example config files in the topology and rigidbody modules.

For topoaa I get the following error:

[2022-02-17 13:18:38,065 __init__ INFO] [topoaa] CNS jobs have finished
[2022-02-17 13:18:38,072 libutil ERROR] 100.00% of output was not generated for this module and tolerance was set to 0.00%.
Traceback (most recent call last):
  File "/mnt/c/Users/jorda/desktop/projects/haddock3/src/haddock/libs/libutil.py", line 320, in log_error_and_exit
    yield
  File "/mnt/c/Users/jorda/desktop/projects/haddock3/src/haddock/clis/cli.py", line 148, in main
    workflow.run()
  File "/mnt/c/Users/jorda/desktop/projects/haddock3/src/haddock/libs/libworkflow.py", line 27, in run
    step.execute()
  File "/mnt/c/Users/jorda/desktop/projects/haddock3/src/haddock/libs/libworkflow.py", line 100, in execute
    module.run(**self.config)
  File "/mnt/c/Users/jorda/desktop/projects/haddock3/src/haddock/modules/base_cns_module.py", line 48, in run
    self._run()
  File "/mnt/c/Users/jorda/desktop/projects/haddock3/src/haddock/modules/topology/topoaa/__init__.py", line 206, in _run
    self.finish_with_error(_msg)
  File "/mnt/c/Users/jorda/desktop/projects/haddock3/src/haddock/modules/__init__.py", line 186, in finish_with_error
    raise RuntimeError(reason)
RuntimeError: 100.00% of output was not generated for this module and tolerance was set to 0.00%.
[2022-02-17 13:18:38,082 libutil ERROR] 100.00% of output was not generated for this module and tolerance was set to 0.00%."

If I set the tolerance to 100% I then get this error, showing that no models were being generated in the topoaa step.

[2022-02-17 13:19:31,112 base_cns_module INFO] Running [rigidbody] module
[2022-02-17 13:19:31,115 __init__ INFO] [rigidbody] crossdock=true
[2022-02-17 13:19:31,115 libutil ERROR] division by zero
Traceback (most recent call last):
  File "/mnt/c/Users/jorda/desktop/projects/haddock3/src/haddock/libs/libutil.py", line 320, in log_error_and_exit
    yield
  File "/mnt/c/Users/jorda/desktop/projects/haddock3/src/haddock/clis/cli.py", line 148, in main
    workflow.run()
  File "/mnt/c/Users/jorda/desktop/projects/haddock3/src/haddock/libs/libworkflow.py", line 27, in run
    step.execute()
  File "/mnt/c/Users/jorda/desktop/projects/haddock3/src/haddock/libs/libworkflow.py", line 100, in execute
    module.run(**self.config)
  File "/mnt/c/Users/jorda/desktop/projects/haddock3/src/haddock/modules/base_cns_module.py", line 48, in run
    self._run()
  File "/mnt/c/Users/jorda/desktop/projects/haddock3/src/haddock/modules/sampling/rigidbody/__init__.py", line 47, in _run
    sampling_factor = int(self.params["sampling"] / len(models_to_dock))
ZeroDivisionError: division by zero
[2022-02-17 13:19:31,122 libutil ERROR] division by zero

This occurs both with a local installation and installation in a Docker container. I've included the relevant lines of the Docker container below if that might help debug an error in my installation.

COPY cns_solve_1.3 cns_solve_1.3

RUN git clone --recursive https://github.com/haddocking/haddock3.git && \
    cd haddock3 && \
    cd src/fcc/src && \
    chmod u+x Makefile && \
    make && \
    cd ../../../ && \
    python3.9 -m pip install -r requirements.txt && \
    python3.9 setup.py develop --no-deps && \
    mkdir -p bin/ && \ 
    ln -s /dependencies/cns_solve_1.3/intel-x86_64bit-linux/source/cns_solve-1111091055.exe bin/cns

**Comment by joaomcteixeira** [comment]
If the topologies are not getting generated is (likely) because the PDB file has errors. Do you know our `pdb-tools` python package? Could you run `pdb_validate` on your input PDBs to see the outcome? I would ask you for your PDB files to inspect them personally, but I believe those are private data, so we respect that.

We are currently working on a PDB pre-processing stage to clean PDBs before running haddock. These are the checks we are implementing. Do you adventure yourself to see manually if you PDB complies with those checks? -> https://github.com/haddocking/haddock3/issues/143

**Comment by jordantwells42** [comment]
Ah okay, that seems to be the case. I ran pdb_validate.py on e2a-hpr_1GGR.pdb in the examples/docking-protein-protein/data directory and several lines come up with the following type of error:

Line XYZ is short: 76 < 80

I am using windows subsystem for Linux, could this be an issue with the EOL character?

**Comment by joaomcteixeira** [comment]
Scuse me, are you having problems with the `examples` folder? All the examples have been running and are running on our site. Are you sure you haven't modified any file by mistake? Are you running the `-test.cfg` examples?

**Comment by jordantwells42** [comment]
I am running the examples! Sorry for the miscommunication, I should have been clearer.

I showed the commands I'm using to install Haddock3 into a Docker container in the first post. The installation appears to work fine and CNS also works locally. The only slightly strange thing that occurs is that numba requires numpy<=1.22.2 so I reinstall numpy as 1.22.1 later on.

I've been running the docking-protein-protein-test.cfg recipe from the examples/docking-protein-protein directory using the command: haddock3 docking-protein-protein-test.cfg. I've attached the full log file if that would be helpful.
[log.txt](https://github.com/haddocking/haddock3/files/8092044/log.txt)

And absolutely! We are aware that things are not production ready, and are ready for any sort of changes that may come with that. 

And I will try it in a virtual machine soon and let you know if that changes things! Usually WSL is VM-like enough for things to work but this could very well be the issue.

**Comment by amjjbonvin** [comment]
This is not the problem - the same files / examples run on our side

**Comment by jordantwells42** [comment]
The cns executable (from haddock3/bin directory) appears to work and brings up the CNSsolve> prompt, as well as typing cns or cns_solve from the cli (once .cns_solve_env_sh has been run).

I checked the 00_topoaa directory and the e2ap_1F3G.out file ends as follows. I'm not sure what the MXRTT parameter is, if its memory based it could be an issue with WSL not being allocated enough RAM.
 %AUTOAN error encountered: exceeded MXRTT (RTF) parameter --> recompile program
   (CNS is in mode: SET ABORT=NORMal END)
 *****************************************************
 ABORT mode will terminate program execution.
 *****************************************************
 Program will stop immediately.
          ============================================================
           Maximum dynamic memory allocation:     8201488 bytes
           Maximum dynamic memory overhead:           208 bytes
           Program started at: 16:14:01 on 17-Feb-2022
           Program stopped at: 16:14:01 on 17-Feb-2022
           CPU time used:       0.0437 seconds
          ============================================================

I've also attached the full file here if that helps
[e2aP_1F36.txt](https://github.com/haddocking/haddock3/files/8092625/e2aP_1F36.txt)

Thanks for the help y'all, it is much appreciated.
.

**Comment by amjjbonvin** [comment]
Ah!

You need to recompile CNS. You can download a set of routines to add to the standard version from the following link:

	https://www.dropbox.com/s/wliubqovuusqdvr/cns.tgz?dl=0

These are distributed with haddock2.4 but we should add them to haddock3 as well or provide clear instructions.
Check the README file in that dir. You basically have to copy the files into the main source directory of your cns installation and recompile.

**Comment by joaomcteixeira** [comment]
Hi @jordantwells42 
We hope you have been able to solve the problem after recompiling CNS. I am closing this *issue* but feel free to reopen it if you have any further questions or if you could not actually solve the problem.
Cheers,

**Comment by jordantwells42** [comment]
Sorry for the late reply! I just confirmed that it worked after recompilation! Thank you for all of the help. Thank you for closing the issue as well.

**Comment by amjjbonvin** [comment]
Thanks Jordan

We clearly need to provide the modified CNS source code and clear instructions to recompile CNS.
