### ISSUE TITLE
Tests for `yaml` files

### ISSUE THREAD

**Issue by joaomcteixeira** [haddocking/haddock3#333]
`yaml` files are large and contain interconnected information. Below is a list of the tests that are already implemented to assert the quality of the `defaults.yaml` files. Tests are written in the `test/` folder and can be executed using `tox -e py39`. Which other tests would you suggest? Add to the list, as new ideas come by:

- [x] test all `default.yaml` files are parseable 
- [x] test `default` value is of the specified type in `type` after direct parsing with `pyyaml`
- [x] test all contain `title`, `short`, `long`, `group` and `explevel` keys
- [x] test each type has its expected specific keys, for example, `min`, `max`, `maxitems`. (`file` and `boolean` are not considered here)
- [ ] test all `explevel` are the expected values: (`easy`, `expert`, `guru`, `hidden`)
- [ ] ~~test `groups` have more than one parameter (@amjjbonvin is this a good test?)~~
- [ ] test the `choices` field: https://github.com/haddocking/haddock3/issues/487

**Comment by amjjbonvin** [comment]
Would not add this one. A given param might not fall under another group. Would make things confusing for finding the right info (thinking of ivresse here)
> 
> test groups have more than one parameter ***@***.*** is this a good test?)
