### ISSUE TITLE
Expandable parameters with two indexes do not work

### ISSUE THREAD

**Issue by amjjbonvin** [haddocking/haddock3#337]
So far in our examples we never expanded parameters (except for the topoaa module). Taking the `docking-protein-peptide` example and defining two flexible segments instead of one by changing the config file to:
```
# Define peptide as fully flexible
nfle2 = 2
flesta2_1 = 1
fleend2_1 = 5
flesta2_2 = 6
fleend2_2 = 11
```

The following error occurs when checking the cfg file:
```
haddock.core.exceptions.ConfigurationError: The following parameters do not match any expected parameters for module 'flexref': fleend2_2, flesta2_2.
[2022-02-24 19:34:37,297 libutil ERROR] The following parameters do not match any expected parameters for module 'flexref': fleend2_2, flesta2_2.
Traceback (most recent call last):
  File "/trinity/login/abonvin/haddock_git/haddock3/src/haddock/libs/libutil.py", line 320, in log_error_and_exit
    yield
  File "/trinity/login/abonvin/haddock_git/haddock3/src/haddock/clis/cli.py", line 121, in main
    params, other_params = setup_run(recipe, restart_from=restart)
  File "/trinity/login/abonvin/haddock_git/haddock3/src/haddock/gear/prepare_run.py", line 101, in setup_run
    validate_modules_params(modules_params)
  File "/trinity/login/abonvin/haddock_git/haddock3/src/haddock/gear/prepare_run.py", line 45, in wrapper
    return func(*args, **kwargs)
  File "/trinity/login/abonvin/haddock_git/haddock3/src/haddock/gear/prepare_run.py", line 192, in validate_modules_params
    raise ConfigurationError(_msg)
haddock.core.exceptions.ConfigurationError: The following parameters do not match any expected parameters for module 'flexref': fleend2_2, flesta2_2.
[2022-02-24 19:34:37,298 libutil ERROR] The following parameters do not match any expected parameters for module 'flexref': fleend2_2, flesta2_2.
```

**Comment by joaomcteixeira** [comment]
Expandable parameters do not work for those cases. You need to define parameters in this fashion:

```
flesta2_need_something_here_1 = 1
fleend2_need_something_else_here__1 = 5
flesta2_need_something_here__2 = 6
fleend2_need_something_else_here__2 = 11
```

I can implement that behaviour you are looking for also. But it is another kind of behaviour. It's different from the original expandable parsing.

**Comment by joaomcteixeira** [comment]
Otherwise do, 

```
fle_sta2_1 = 1
fle_end2_1 = 5
fle_sta2_2 = 6
fle_end2_2 = 11
```

**Comment by amjjbonvin** [comment]
Need to correct all default yaml and the cns code then - something went wrong in the communication about this along the way. 

Probably the confusion comes from the topoaa module which has expandable parameters that do not follow that convention (the hisd and hise params)

**Comment by joaomcteixeira** [comment]
It is not a problem to implement a new (another) expandable convention, as is best for your and the CNS maintenance.

**Comment by amjjbonvin** [comment]
Need to change the expandable logic because of the way CNS handles variables. The current definition with e.g. `rair1_sta_1` does not work in CNS.  At the CNS level we need to loop of the molecule (the index after `rair` and the number of segments for that molecule, the last number in `rair1_sta_1`.   The current notation leads to an error:

``` 
CNSsolve>            do (store5 = $nchain1) ( resid $rair$nchain1_sta_$fcounter : $rair$nchain1_end_$fcounter
 %SYMIDX-WRN: index-symbol $NCHAIN1_STA not found.
 %WDSUB-ERR: symbol not found:
             do (store5 = $nchain1) ( resid $rair$nchain1_sta_$fcounter
                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

CNS interprets thus $nchain1_sta as one string. For things to work we thus need a notation like: `rair_sta_1_1` or `rairsta_1_1`, i.e. the indexes over which we loop must be separated from the remaining of the string.

**Comment by joaomcteixeira** [comment]
Addressed in #338. Need to clean the code before closing this issue

**Comment by sverhoeven** [comment]
In the docs at https://github.com/haddocking/haddock3/blob/e324b9cbd4c9c76ea1df6ce874e8ba5317486218/src/haddock/gear/expandable_parameters.py#L1-L47 there is no mention of the `Number of ...` parameter like  `nfle1` or `numc2sym`. 

Any thoughts about how to deal with them?

**Comment by joaomcteixeira** [comment]
Now. For now, those parameters have to be defined manually by the user. The user needs to understand how many groups in `fle` she/he added in the config and configure the `nfle1` accordingly. We have discussed the other day about removing these parameters and having them filled automatically from the user input.

**Comment by joaomcteixeira** [comment]
The new module can be used to extract all expandable parameters from the default configuration files. I will see for what is missing for that and add it. So that @sverhoeven can use it.
