### ISSUE TITLE
Shared default parameters accross modules

### ISSUE THREAD

**Issue by joaomcteixeira** [haddocking/haddock3#349]
Currently, each module defines its own parameters in its `default.yaml` file. However, modules of the same category share several parameters. We could create higher-level `default.yaml` files containing those parameters that are shared by all modules of a category. This would enhance DRY. See for example #347 

@sverhoeven would this be a problem for the interface anyhow?

**Comment by joaomcteixeira** [comment]
https://github.com/haddocking/haddock3/pull/347#issuecomment-1057117933

**Comment by sverhoeven** [comment]
No, it should not be a problem. In the interface the form is rendered for each module, which requires all (category+module specific) the defaults in the same place. 

What happens with the order of parameters when combining the shared and module specific parameter defaults. Should the category parameters always come first?

Also I am wondering if having parameters shared by all modules of a category can restrict the possibilities of a module. For example a deep learning based module might need very different parameters while it still belongs to a category with more heuristic modules.

**Comment by joaomcteixeira** [comment]
If we don't want to make it too complex, a way to do it is to define *category parameters*  only those that are shared by **all** the modules. For example, `param_1` should be defined per **module** if there are 5 modules in the category and the `param_1` is only shared by 4 of them. Otherwise, we create too complex hierarchies. Better something than nothing.

**Comment by amjjbonvin** [comment]
Again, there are very few parameters that need to be shared between modules (otherwise we loose flexibility).

The ones I can think of at this time are:

- verbosity
- ligand param and topo files 

It is not because modules share the same parameters that those will have per se the same values in the respective modules.
> If we don't want to make it too complex, a way to do it is to define category parameters only those that are shared by all the modules. For example, param_1 should be defined per module if there are 5 modules in the category and the param_1 is only shared by 4 of them. Otherwise, we create too complex hierarchies. Better something than nothing.
>

**Comment by joaomcteixeira** [comment]
That's right. And if there are not that many parameters, implementing this may just add unnecessary complexity. Closing for now, until we feel the need for it.

**Comment by amjjbonvin** [comment]
We already have a number of shared parameters, like the running mode (hpc, local, mpi).
Could we use that also for the verbosity for example? In principle they could all be written to the CNS input files (even if not used) if it simplifies things.

Also the haddock3-cfg cli should also have an option to list those global parameters (now missing).
