### ISSUE TITLE
Make modules independently executable

### ISSUE THREAD

**Issue by joaomcteixeira** [haddocking/haddock3#364]
Currently, as of https://github.com/haddocking/haddock3/commit/c6c0b91e2aac9b139ada772cb2d1bb213729ff21, we can restart haddock3 run from a given step with the option `--restart`. This demonstrates modularity because any module can continue forward to the current state if all previous files already exist. You can also run any module separately by creating a config that executes `topoaa` and the desired module. However, preparing a folder to execute just a single module *per se* is not trivial because there is **not** a human configurable way to pass files from one module to another.

Suggestion:

After all the developments we did in the past months, I think it is possible to replace the `ModuleIO` by our configuration file system such that if we want to run only `flexref` we can give it a configuration file pointing to the topologies and all needed files and execute just that module. We can make modules write these files so it becomes easy to transfer one folder to another place and continue forward.

Finally, we can create module specific CLIs in the for of sub clis of `haddock3` -> `haddock3 MODULE`.

I will explore this concept. I think it is feasible.

This is not a required feature for the `3.0.0-stable` release.

**Comment by rvhonorato** [comment]
This was discussed before and if I remember well we opted not to follow this route and it was exactly why `ModuleIO` exists now. 

I have explored this in the alpha1 version and you could just "pipe" all the module, its a very easy way to plug haddock3 into already consolidated workflow managers even easier if we just used CWL, @brianjimenez had very good reason not to do that and its precisely the reason for the ontology to be implemented as it is now.

So maybe its best if we go forward instead of backwards?

**Comment by amjjbonvin** [comment]
I would agree with @rvhonorato here

What could be useful however would be a way to add modules to an existing workflow, specifying which step should be the input. E.g. say you have done  `ridibody` + `flexref` + `emref` but did not run the `caprieval` module after each step.  Would it be possible to add those to the current workflow at the end and specify to which stage they should be applied?

**Comment by joaomcteixeira** [comment]
Hmm.. interesting. I was not thinking of "piping" modules, actually. That looks like a nice idea, but the fact that modules take time to execute and they have many parameters, it loses sense.

What I was referring to is the capacity to run single modules by creating `cfg` files that would simulate the current `ModuleIO`. But actually, that could become too confusing of an option. 

Maybe it is better to extend the current functionalities and make sure we can copy+paste step folders in haddock3 runs and create new runs from there. For example, ake `00_topoaa` and `05_flexref` from one run and make a new run starting from there. I will use this PR to make sure such functionality works properly.

**Comment by amjjbonvin** [comment]
That would be indeed a useful option to have.


> Maybe it is better to extend the current functionalities and make sure we can copy+paste step folders in haddock3 runs and create new runs from there. For example, ake 00_topoaa and 05_flexref from one run and make a new run starting from there. I will use this PR to make sure such functionality works properly.

**Comment by joaomcteixeira** [comment]
Done in #392, #425, #428, and #429
