### ISSUE TITLE
Implement `haddock3-score`

### ISSUE THREAD

**Issue by rvhonorato** [haddocking/haddock3#365]
Port this CLI from [rvhonorato/haddock3@calc_score](https://github.com/rvhonorato/haddock3/tree/calc_score) to here and also add option to: display components, parsed structure and take ensemble as input.

**Comment by joaomcteixeira** [comment]
The `haddock3-score` CLI is ready to be tested. See -> https://github.com/haddocking/haddock3/pull/510

I am finalizing some tests to ensure the edits I needed to do in `topoaa` do not perturb the rest of the workflows. But the CLI is ready to be tested. Give it a try and let me know.

@rvhonorato @amjjbonvin @mgiulini
