### ISSUE TITLE
Have fuzzy matching on user supplied parameters and paths

### ISSUE THREAD

**Issue by douweschulte** [haddocking/haddock3#373]
In the `prepare_run.py` when a user supplied parameters is not correct it would be very nice if the parameter is matched against all possible parameters and the closest one is given back to the user as a suggestion.

It could look like the following example:
```
Error 01: Receptor file not found

    |  ~/project_01/files/receptor.pdb

help= the folder 'project_01' does not live in '~' did you mean 'project-01'?
```

Discussed with @joaomcteixeira.

**Comment by joaomcteixeira** [comment]
Great,
here should it go :wink:

https://github.com/haddocking/haddock3/blob/d5011e030da48891c3f6e97d6fc6fd48fae5979c/src/haddock/gear/prepare_run.py#L221

for modules:

https://github.com/haddocking/haddock3/blob/d5011e030da48891c3f6e97d6fc6fd48fae5979c/src/haddock/gear/prepare_run.py#L387

and for files:

https://github.com/haddocking/haddock3/blob/d5011e030da48891c3f6e97d6fc6fd48fae5979c/src/haddock/gear/prepare_run.py#L313

**Comment by rvhonorato** [comment]
Is this just for looks or does it actually change the path on the fly?

**Comment by joaomcteixeira** [comment]
It warns the user before exiting the run during the "preparation phase". It does not change anything automatically. I would not change anything automatically because the consequences of that are unpredictable.
