### ISSUE TITLE
RMSD clustering implementation

### ISSUE THREAD

**Issue by mgiulini** [haddocking/haddock3#380]
Clustering structures with the RMSD matrix can be beneficial in certain situations, for example when a small molecule is considered as a ligand.

There could be two modules for it:

1. a RMSD matrix calculation module
2. a clustering module, with some flexibility on the clustering algorithm and on the thresholds

Discussed with @joaomcteixeira and @amjjbonvin

**Comment by joaomcteixeira** [comment]
Yes, two modules are better than one. We can keep the RMSD matrix and use in different modules as input.

What I suggest is for you to prepare a python script that does everything you need to calculate the RMSD matrix. That python script should have a function that receives a list of paths to PDB files. This function will be the entry point for haddock3.

I suggest doing the implementation in pure python (numpy, scipy, etc). Don't worry at first with the performance. Once this is working, we will work with the performance using [Numba](https://numba.pydata.org/).

Finally, we will organize your code into the haddock3 code, but most likely it will all remain inside the RMSD module.

Have a look around if you need any functions from HADDOCK3 already.

Once everything is working in your computer, we will work to add it as a module :wink:
Welcome!

**Comment by amjjbonvin** [comment]
Possibly with different options on how to perform the fitting and RMSD calculations (i.e. molecule/residue selection)

> What I suggest is for you to prepare a python script that does everything you need to calculate the RMSD matrix. That python script should have a function that receives a list of paths to PDB files. This function will be the entry point for haddock3
>

**Comment by rvhonorato** [comment]
The rmsd calculation is implemented in `caprieval` with kabsch, you should then pass all the atoms instead of the only the interface - it handles different numbering and all that and small molecules

This is the one Joao ordered me to make it from scratch. Unless he also told you to re-do it from scratch id suggest you take the functions from there!

**Comment by rvhonorato** [comment]
> Possibly with different options on how to perform the fitting and RMSD calculations (i.e. molecule/residue selection)

This is how the capri class handles it, the fitting is based on either the interface, ligand, etc - could also change it to pass a numbering selection

**Comment by amjjbonvin** [comment]
> Possibly with different options on how to perform the fitting and RMSD calculations (i.e. molecule/residue selection)
> 
> This is how the capri class handles it, the fitting is based on either the interface, ligand, etc - could also change it to pass a numbering selection
> 
> 
Will be needed to ensure the FIT / RMSD are calculated on the same set of residues since we need to compare all models vs all models.

**Comment by rvhonorato** [comment]
yep, the way the rmsd is calculated in the capri module is by using the interface/ligand/interface-ligand atoms from the receptor/lowest scoring structure, would just be a matter of passing a list of numbers instead.

**Comment by rvhonorato** [comment]
would be great actually to see how it would work with https://github.com/biopython/biopython/pull/3849 - since biopython is one of the allowed dependencies

**Comment by mgiulini** [comment]
Yes, that seems interesting, especially in terms of performance with respect to the fully pythonic code. If you agree, I will try to implement the clustering procedure using these biopython routines to calculate the pairwise rmsd matrix.

**Comment by rvhonorato** [comment]
Thanks for the clarification @JoaoRodrigues !

**Comment by mgiulini** [comment]
@amjjbonvin I found the `cluster_struct .cpp` (https://github.com/haddocking/haddock/blob/b311dd900a5c62d66b727be196a40e9b6fa7d994/tools/cluster_struc.cpp) script used in haddock2.4. Do we want to adapt it in order to add the new desired functionalities? Or it's better to rebuild it from scratch in python? At a first glance I would go for the first option

**Comment by amjjbonvin** [comment]
We can integrate it in haddock3 - it is in principle our own code

**Comment by joaomcteixeira** [comment]
If you make it python with numba I will :heart: you. But if that's too much work, we can go with the `cpp`. I can help you on anything you need.

**Comment by mgiulini** [comment]
I need to think a bit about it..the optimal implementation from scratch of the various methods is not difficult, except for the labeling routines, which are tricky.

**Comment by amjjbonvin** [comment]
Note that cluster_struc only does the clustering and not the calculation of the RMSD matrix.

**Comment by mgiulini** [comment]
Yes indeed!
