### ISSUE TITLE
Check if the path is a softlink and then display both

### ISSUE THREAD

**Issue by joaomcteixeira** [haddocking/haddock3#384]
Would be cool if it could check if the path is a softlink and then display both (this is usually the cause of issue when running things in the hpc centers) and also check if the path you are referring is mounted somewhere else. 

Now it just handles typos, right?

_Originally posted by @rvhonorato in https://github.com/haddocking/haddock3/issues/381#issuecomment-1091261237_

Do you want to give it a try @douweschulte ?

@rvhonorato any additional details on the rationale behind this?

Cheers!

**Comment by rvhonorato** [comment]
Stale and not relevant at the moment since we don't have a way to test it
