### ISSUE TITLE
Add a `separate_molecule` parameter to the refinement modules

### ISSUE THREAD

**Issue by rvhonorato** [haddocking/haddock3#388]
We discussed that by adding this parameter we can do refinement before sampling, analogous to what we do for v2.4 - removing clashed and improving bad models.

**Comment by joaomcteixeira** [comment]
Yes. To clarify our discussion. The `separate_molecule` parameter would split the PDB into its multiple chains (if PDBs have more than one), such that these can be refined by some `refinement` module before attempting `rigidbody`. In the case of the input, PDBs contain only one chain, this parameter would be ignored, or simply won't have an effect.

The `separate_molecule` parameter should go to the `topology` module. Was that it? Or should it go to the `refinement` modules? If we had the parameters to the refinement modules, is it easy to separate also the topology?

**Comment by amjjbonvin** [comment]
What kind of refinement are we speaking about? With explicit solvent?

In that case splitting the models would make sense.

But if only EM, all models can be refined at the same time, simply turning off intermolecular interactions.
