### ISSUE TITLE
What to do when config does not match the available options

### ISSUE THREAD

**Issue by joaomcteixeira** [haddocking/haddock3#39]
I think *excluding* a module from the execution when it does not exist is **NOT** a good approach because this can facilitate passing silent errors because of typos or mistakes. In my opinion if a module specified by the user is not present we should **abort** the execution, and report the error to the user.

_Originally posted by @joaomcteixeira in https://github.com/haddocking/haddock3/pull/38#discussion_r675989280_

General discussion: how should we approach these situations? As I said, I vote for aborting the run and inform the user.

**Comment by amjjbonvin** [comment]
Makes sense to me

**Comment by rvhonorato** [comment]
Closed in #38, if a given module does not exist it raises a `ConfigurationError` and the code exists.
