### ISSUE TITLE
run scoring modules after modules other than topoaa

### ISSUE THREAD

**Issue by mgiulini** [haddocking/haddock3#394]
Currently, it is impossible to run scoring modules after modules other than topoaa. 

The following error appears:
```
File "haddock3/src/haddock/modules/scoring/mdscoring/__init__.py", line 93, in _run
    original_name = pdb.topology.file_name.replace('.psf', '.pdb')
AttributeError: 'list' object has no attribute 'file_name'
[2022-04-11 17:48:34,152 libutil ERROR] 'list' object has no attribute 'file_name'
```

**Comment by amjjbonvin** [comment]
In principle the emref module without any restraints and a decreased number of EM steps would do the same as the emscoring

**Comment by joaomcteixeira** [comment]
Yes. This bug reflects that we need some function/classes that control certain parts of the module's preparation steps and not let each module do that on themselves. I will look into that. Meanwhile, good job finding this bug, and good luck solving it. Let me know if you need any help :+1:
