### ISSUE TITLE
Add `WAT` to the list of residues to be ignored by `caprieval`

### ISSUE THREAD

**Issue by rvhonorato** [haddocking/haddock3#398]
I added the two tests as requested. It is important to underline that it is currently impossible to run `caprieval` after `mdscoring`, as the latter produces a pdb file with some water inside

_Originally posted by @mgiulini in https://github.com/haddocking/haddock3/pull/397#issuecomment-1096726979_

**Comment by amjjbonvin** [comment]
Does mdscoring keeps waters in the PDB file?

Should not (or needs to be changed). 

In principle the solvent could be discarded in the caprieval module.

**Comment by rvhonorato** [comment]
> Does mdscoring keeps waters in the PDB file?

Apparently it does! Opened an issue about it - #400! 🎉
