### ISSUE TITLE
Discussing layer architecture and current names

### ISSUE THREAD

**Issue by joaomcteixeira** [haddocking/haddock3#40]
# HADDOCK3 hierarchic names and general architecture:

## Current configuration

[The current configuration at the time of writing is](https://github.com/haddocking/haddock3/tree/ab01731628ea937298c7a42159296cf7aa490f18):

1. A `workflow`: contains all operations and is somehow managed by the `class WorkflowManager`
2. `class Workflow`is assigned as a `self.recipe` inside `class WorkflowManager`. So, a `recipe` is a `workflow` within the `WorkflowManager` context.
3. a `stage` is an operation done in the workflow. Examples of `stages` are: `topology`,`scoring`, `clustering` . `stages` are controlled by the `class Workflow`. And `stages` do nothing, they simply refer to the concept of the operation.
4. `stages` have different `steps` - `class Step`.
5. `steps` are the actual operations defined by the python modules within each `stage`'s folder, like `default.py`.
6. `steps` are also named `mode` inside the `class Step`.
7. And the `stage` is named `module` inside the `class Step`.

## Comments

In the configuration file, and in the code, on top of the *haddock module* layer there is the `stage` layer. But I don't see more than one `stage` item in the `[stage]` layer. Is it? Even looking to the original @brianjimenez  examples I see no more than one `stage` item. There are many `modules` inside the `stage` layer, but not *another* stage. So, why we need the concept `stage`?

`class WorkflowManager` manages nothing and it can be refactored to a simpler function named, for example, `run_haddock()`.

## My suggestions

So, I suggest refactoring to:

**A general `Workflow` that contains a sequence of `modes`.** Nothing more.

In this way, we refactor from 5 conceptual layers to only 2. The fact that `modes` are contained within `modules` does not mean that a `module` *per se* is a conceptual or organizational layer; it is just a category, a tag, organizing the `modes`. Well, it happens to be a folder serving code organization purposes.

If we refactor from 5 layers to 2 layers as I am proposing, we will decouple the `stages` and the user can freely compose the workflow considering only the `modes`:

```python
order = [
    "topology"
    "scoring"  # this would give the default
    "clustering.fcc"
    "analysis.whatever"
    "scoring.megascore"
]
```

Yes, we can currently do:

```python
order = ["topology", "scoring.1", "scoring.2"]
```

but we have to assign `mode=""` assuming this is `default` and also using integers for ordering is suboptimal because if we want to reorder we need to change every integer in the list. Furthermore, there is this concept of `stage` in the code and the configuration file for which I don't see a purpose. **Note:** if there exists a reason for having several `stages` it is not reflected in the current definition of the `order`pameter, not the code itself.

In https://github.com/haddocking/haddock3/blob/ab01731628ea937298c7a42159296cf7aa490f18/src/haddock/workflow.py#L92 we read `self.module` to refer to conceptual `haddock3`modules and `self.mode` to refer the actual operations. I suggest we find another name for "haddock modules" because *modules* refer to `*.py` files in a project, and creates confusion.

If we remove the `stage` and `module` layers, we can also rename `mode` because mode refers to a mode of a module and we would not separate them anymore in the configuration file. Maybe we can have `action`?

-------

@amjjbonvin @rvhonorato, what do you think? If you agree, I can work on this refactor.

**Comment by rvhonorato** [comment]
> In the configuration file, and in the code, on top of the _haddock module_ layer there is the `stage` layer. But I don't see more than one `stage` item in the `[stage]` layer.

Yes there are no nested stages if that's what you mean

> `class WorkflowManager` manages nothing and it can be refactored to a simpler function named, for example, `run_haddock()`.

If I'm not mistaken this class is meant to be further developed to handle the multiple submission modes (HPC/Grid) and also asynchronous execution such as below in 2

![Untitled Diagram](https://user-images.githubusercontent.com/9445814/126950977-b61bac02-c0fb-4f9f-8774-0926aac9b747.png)

**Comment by rvhonorato** [comment]
> **A general `Workflow` that contains a sequence of `modes`.** Nothing more.

If you could also pass the parameters, I really like this idea and from what you describe I think it should be a relevant simplification, +1! 

> I suggest we find another name for "haddock modules" because modules refer to *.py files in a project, and creates confusion.
> 
> If we remove the stage and module layers, we can also rename mode because mode refers to a mode of a module and we would not separate them anymore in the configuration file. Maybe we can have action?

Agreed! How about `method`? `action` is also good.

**Comment by joaomcteixeira** [comment]
Wrapping up what @amjjbonvin  @rvhonorato and I discussed today and answering @rvhonorato  previous comments:

> [Yes there are no nested stages if that's what you mean](https://github.com/haddocking/haddock3/issues/40#issuecomment-886456442)

So, if there are no nested `stages` we can definitively remove that layer and go straight to an architecture of only two layers: 1) the workflow manager and 2) the executed modules.

> [If I'm not mistaken this class is meant to be further developed to handle the multiple submission modes (HPC/Grid) and also asynchronous execution such as below in 2](https://github.com/haddocking/haddock3/issues/40#issuecomment-886456442)

I am becoming an FP-dev1l; the need for an HPC/Grid submission routine is not crucial to enforce a `WorkflowManager`. We might have it if that API is needed but should not encode any logic inside.

> [If you could also pass the parameters, I really like this idea and from what you describe I think it should be a relevant simplification, +1!](https://github.com/haddocking/haddock3/issues/40#issuecomment-886460246)

I prefer programming in layers where each layer/unit is independent of its "parent" units. For example, if B uses A, A should be independent of B. I like to pass parameters down the line. I have over-used kwargs sometimes for this matter, not sure yet if that is the best approach or if it is best to have parameter namespaces for that. But passing parameters down the line should be our aim, IMHO.

> [Agreed! How about method? action is also good.](https://github.com/haddocking/haddock3/issues/40#issuecomment-886460246)

@amjjbonvin, which nomenclature do you prefer? `module`, `method`, `action`, `recipe`, others? I guess `recipe` was the name in the `beta1`, and the name can stand on its own. On the other hand, the problem with `module` is that there are also *python modules*, and haddock modules are, in fact, python packages. It may become confusing. I like `action`.

:robot: Which **actions** do you want to do?
:technologist: I want to do rigid docking, than analysis, than clustering...

`operation` can be another alternative.

If at the end of the day `module` keeps sounding better, lets give a try to `package` to be in-line with the python nomenclature.

In today's meeting, we decided that haddock3 `modules` (maybe renamed to `actions` or other) should be kept where they are:

`src/haddock/modules`

Inside `modules/`, different folders will refer to each module's *conceptual* category. For example: `analysis`, `clustering`, `sampling`, `refinement`.

**A novelty from today's meeting**, the different `modules` (a.k.a. `actions`) will exist in the form of a **subfolder/** instead of a `*.py` file as it is currently the case (for example: `default.py`). Inside each `module` there will be a `cns/` folder, an `__init__.py` and a `run.py` file with a `run()` function. Names can still be changed, but we should ensure polymorphism. An example is:

```
|scr/
    |haddock/
        |modules/
            |analysis/
 		|...
            |sampling/
                |rigidock/
                    cns/
		    __init__.py                     
                    run.py
                |lighdock/
		    ...
```

The `toml` config file can therefore be updated to (as described previously):

```python
order = [
    "topology"
    "scoring"  # this would give the default
    "clustering.fcc"
    "analysis.whatever"
    "scoring.megascore"
]
```

Regarding the *defaults*, there should not be a module named `default`. We can have defaults, but those must be specified by some parameter and not by a module name. For example, in the `order = [...]` above, using `"scoring"` can point to the default scoring method. **However**, that creates a reproducibility problem if the default changes in future versions. So maybe we should enforce specifying the action altogether and have the suggested defaults explained in the documentation.

Pull Request #47 is a dummy PR that we can use to draft and write ideas on the necessary actions (modules) and their categories. Use `__init__.py` docstrings in modules categories to describe and document that category. Use `__init__.py` in modules subfolders to document them.

I will work towards refactoring the config to the execution engines considering the new layering and module structure discussed here.
