### ISSUE TITLE
PDB traceback module

### ISSUE THREAD

**Issue by amjjbonvin** [haddocking/haddock3#402]
Currently it is very cumbersome to trace back the origin of a PDB file along the workflow.

This is particularly relevant for the scoring workflows where the initial models can be very different. 
All refined models get the same name and it becomes difficult (but not impossible) to figure out what was the original model.

In case of a multistep docking workflow this is even trickier since the numbering might change from step to step.

It would therefore be handy to have a PDBtraceback module that gives the correspondence of the PDB files all the way back to the topoaa and initial models given to HADDOCK.

Again, useful in scoring, but also to know for example when using ensembles of starting models, which specific starting model combination led to a given model.

**Comment by rvhonorato** [comment]
> It would therefore be handy to have a PDBtraceback module that gives the correspondence of the PDB files all the way back to the topoaa and initial models given to HADDOCK.

Would it be useful to run this PDBtraceback at points of the workflow that is not the end? 

If not, then I guess it would make more sense for it to be part of a "finalization" routine together with cleaning the unnecessary, thus only executed at the end (could be triggered with a parameter).

Does that make sense?

**Comment by amjjbonvin** [comment]
> Would it be useful to run this PDBtraceback at points of the workflow that is not the end?
> 
> If not, then I guess it would make more sense for it to be part of a "finalization" routine together with cleaning the unnecessary, thus only executed at the end (could be triggered with a parameter).
> 
> Does that make sense?
> 
> 
In principle yes - but you might need it also in cases where something goes wrong and the workflow does not complete (or if a step gives an error, the “finalisation” module should still be run if defined).

**Comment by joaomcteixeira** [comment]
Currently input PDB are taken from `self.previous_io.retrieve_models()` which returns a list. I think `retrieve_models` should return some kind of object that provides the input and keeps a record of the original PDBs. The information can be stored in `io.json` likely. In order not to need to edit the modules for this. As @rvhonorato did in #405, a table at some points should be written. but don't know if one per file. maybe we can provide a CLI that generates this table by taking the information from the `io.json`. Thus the extra file is written only on demand.

**Comment by mgiulini** [comment]
hi @amjjbonvin, I am having a look at this: we should be able to retrieve all the necessary information. Analogously to the haddock3-analyse CLI, the haddock3-traceback could be a CLI acting on any haddock3 run:
`haddock3-traceback PATH_TO_RUN
`
The output could be a **traceback** folder containing the name (and rank) of the file at every (except for the analysis) step of the workflow:
```
original_name 01_rigidbody_name 01_rigidbody_rank 06_flexref_name 06_flexref_rank ...
original1.pdb rigidbody_6.pdb   1                 flexref_1.pdb   9
...
original2.pdb rigidbody_1.pdb   578               -               -
```
This approach would make immediate to trace back all the models, including those (rigidbody_1.pdb in the example above) that do not reach the end of the workflow.
would this work for you? we could also add this as a part of the analyse CLI, but I wouldn't do that, better to keep things separate
