### ISSUE TITLE
implement model-wise sequence alignment in caprieval

### ISSUE THREAD

**Issue by mgiulini** [haddocking/haddock3#403]
Currently, the CAPRI class, when instantiated, performs a single sequence alignment between the reference and the first input model. This is wrong, as the set of input models might have different alignments. Therefore, we must do every reference-model sequence alignment at the beginning of the CAPRI module.

Discussed with @rvhonorato

**Comment by amjjbonvin** [comment]
Could be a parameter in principle - defining if the ensemble is consistent or heterogeneous.

to avoid unnecessary computations

**Comment by mgiulini** [comment]
Yes. I would not leave it to the user, but rather implement it as a function (`get_consistent(input_models)` ?) at the beginning of `caprieval`. Does it make sense?

**Comment by rvhonorato** [comment]
Yes I agree, better to have it as a function so we can handle the distribution more effectively. Like that we can prioritize that models from the same ensemble end up in the same core.
