### ISSUE TITLE
Writing down a copy of the module's parameters

### ISSUE THREAD

**Issue by joaomcteixeira** [haddocking/haddock3#407]
I know we want to write to the disk the less possible files. But I think it is useful that each module writes a file with all the parameters it used, that is, the defaults updated with the user parameters.

This will facilitate reporting and quick traceability. Maybe we can write this information somewhere inside another already used file, `io.json`?

What are your thoughts?

**Comment by amjjbonvin** [comment]
One more file per module is peanuts

I would then rather write is as a cfg file - simpler for users

**Comment by joaomcteixeira** [comment]
Exactly, I agree. Like the `haddock3-cfg` is outputting. Just for that particular module.
