### ISSUE TITLE
Review integration tests

### ISSUE THREAD

**Issue by joaomcteixeira** [haddocking/haddock3#408]
> IMHO the integration tests should be as complex as possible (to cover the wider range of features) not variations of the same. So in this specific case, I'd change `docking-antibody-antigen-ranairCDR-test.cfg` to use `mdscoring` (and later even `caprieval`) and add specific tests for the modules; `test_module_emscoring` and `test_module_mdscoring`.

_Originally posted by @rvhonorato in https://github.com/haddocking/haddock3/issues/397#issuecomment-1096830492_

I agree with @rvhonorato. We are using `*-test.cfg` more and more. Any time we can, we should review these examples in order to reduce the number of calculations needed while increasing the complexity of the tests cases in order to cover the most cases possible with the least computational time.

Related also with #396

**Comment by amjjbonvin** [comment]
What is this issue about???

**Comment by joaomcteixeira** [comment]
We have created the `*-test.cfg` examples a while back, and we have improved many things since then. Moreover, we started using `*-test.cfg` heavily as integration tests. I am just saying at some point we should review them to make sure they are updated and test the most diverse possibilities. I am not referring to the protein systems, but to the configuration files and the modules defined.

**Comment by joaomcteixeira** [comment]
Already in different situations, @amjjbonvin and @rvhonorato suggested moving the `*-test.cfg` to a different folder. You have a point here. My considerations are:

- I believe the `tests/` folder should be just for unit tests. 
- we can create a new folder `integration_tests/` for the `*-test.cfg`. However, the `*-test.cfg` are tightly related to the examples: `data` files, the structure of the folders, and the workflow per see. `*-test.cfg`  configs are basically the same as the examples but with less sampling. Moving to a different folder would require additional efforts to keep both places updated and synchronized.

Is it really worth moving `*-test.cfg` to a different folder?

I think for now and until the integration tests (`*-test.cfg`) mature a bit more, it is fine to leave them in the `examples/`.

What are your thoughts?

**Comment by amjjbonvin** [comment]
Probably a good point indeed - avoids data duplication
