### ISSUE TITLE
amend threshold behavior in clustfcc

### ISSUE THREAD

**Issue by mgiulini** [haddocking/haddock3#411]
analogous to #386 but for clustfcc: when saving the output to `clustfcc.txt` the average score is calculated as the sum of the first `threshold` scores divided by `threshold`, which is not correct when the population of the cluster is lower than `threshold` https://github.com/haddocking/haddock3/blob/2a92beeac96cd1af4f5c7b795b357e62f879b276/src/haddock/modules/analysis/clustfcc/__init__.py#L157

**Comment by rvhonorato** [comment]
I think this is the correct behaviour; this is related to the ranking of the clusters, a cluster may have 100 elements but its score the score is given to it based on the topN (`threshold`).

**Comment by mgiulini** [comment]
In that case (`pop > threshold`) it is certainly correct, but when `pop < threshold` (example: `threshold` = 4 and `pop` = 3, with scores = [1,2,3]) the above code gives an average score equal to 6/4, which is not the true average score of the cluster (6/3)

**Comment by rvhonorato** [comment]
Oh yes, good catch, I think that for haddock 2.x I think the clusters with less elements than the threshold were not considered, here we consider then nonetheless (since they come out of fcc anyway). Should we @amjjbonvin ?

**Comment by joaomcteixeira** [comment]
> In that case (pop > threshold) it is certainly correct, but when pop < threshold

Don't forget to implement also the equality `pop == threshold`.

**Comment by amjjbonvin** [comment]
It is an option to consider those, right (which by default should be false)?

But it considered then the correct average value should be reported.

**Comment by rvhonorato** [comment]
> It is an option to consider those, right (which by default should be false)?

I agree.

So two things then:

* Add option a parameter to `clustfcc` (true, false) to consider clusters with pop < threshold
* When pop < threshold, if present, present the correct average
