### ISSUE TITLE
Increase test coverage for clustfcc module

### ISSUE THREAD

**Issue by joaomcteixeira** [haddocking/haddock3#416]
> Since this PR corrects a 🐛, can you add at least one test that proves the new implementation is correct? If the unittest is too complex, can you explain here how this new implementation changes the `capri` tables in the `examples/*-test.cfg`?
> 
> Cheers!

I agree and think this raises issue of increasing the test coverage for https://github.com/haddocking/haddock3/blob/6b696ca0e8b7228cc9362a222fa857a151f79755/src/haddock/modules/analysis/clustfcc/__init__.py, which is quite low at the moment. I suggest we create another issue for this, in which such checks are implemented (in some `test_module_clustfcc.py`). What do you say?

_Originally posted by @mgiulini in https://github.com/haddocking/haddock3/issues/415#issuecomment-1109833185_

**Comment by mgiulini** [comment]
@rvhonorato I created the branch `test_module_clustfcc` for this issue. I started implementing some basic dummy tests, feel free to add others
