### ISSUE TITLE
problems running non-cns modules after topoaa

### ISSUE THREAD

**Issue by mgiulini** [haddocking/haddock3#417]
Currently it's impossible to run non-cns modules such as `caprieval` and `clustfcc` immediately after `topoaa`. This could be useful, especially when submitting large ensembles of models for validation/analysis purposes. The error is the following:

`
AttributeError: 'tuple' object has no attribute 'rel_path'
` 

for `topoaa->clustfcc` and `topoaa->caprieval` .cfg files. This is due to the fact that `topoaa` produces a tuple instead of a PDBFile object. This should be an easy fix.

**Comment by mgiulini** [comment]
@rvhonorato do you remember we discussed about this issue some time ago? I was able to correct it using the `individualize` parameter when retrieving models. At the beginning we thought that it was a bit too simplistic as a solution, but looking at it now it does not sound too bad: it's reasonable that modules like `clustfcc`, `caprieval`, `rmsdmatrix` treat each molecule as an individual entity, what do you think?

**Comment by rvhonorato** [comment]
serendipity! let me test a few scenarios also

**Comment by mgiulini** [comment]
Yes! let me know :)

**Comment by mgiulini** [comment]
Hi @rvhonorato, should I proceed to incorporate this implementation in the main code? it can be adjusted later
