### ISSUE TITLE
Non-existing chains in `rmsdmatrix` and `caprieval`

### ISSUE THREAD

**Issue by joaomcteixeira** [haddocking/haddock3#422]
`rmsdmatrix` and `caprieval` modules use `resdic_*` parameter to define chain IDs, for example, `resdic_A`.

What is the behavior of the modules if the chain ID defined in `resdic_*` does not exist in the run? For example, `resdic_Z`?

In case it is silently ignored. Should we implement a verification to ensure all chains defined in `resdic_*` actually exist in the run molecules? If so, we need to implement this at both `prepare_run` stage and at the module level.

@mgiulini @rvhonorato asking for your help here :relaxed:

**Comment by rvhonorato** [comment]
Most modules need chain information to be defined, not only these two.
