### ISSUE TITLE
Implement the geometry library

### ISSUE THREAD

**Issue by joaomcteixeira** [haddocking/haddock3#426]
> Very good! Very nice PR and interaction 😉 I think it's fine. You can continue working on the docs as much as you want, when you are happy with it, merge it 👍 🚀

Thank you, I will merge it! I deem the documentation sufficient for now, it can be improved with further use/when we implement the geometry library

_Originally posted by @mgiulini in https://github.com/haddocking/haddock3/issues/414#issuecomment-1117142640_

:wink:

**Comment by mgiulini** [comment]
you anticipated me by few seconds ;)

**Comment by joaomcteixeira** [comment]
![luckyluke](https://user-images.githubusercontent.com/2901810/166670473-484ca173-100e-421d-8050-652115d12293.png)
