### ISSUE TITLE
Accepted and ignored residues

### ISSUE THREAD

**Issue by joaomcteixeira** [haddocking/haddock3#432]
#431 handles acceptable and non-acceptable residues. As so do #144, which rewrites a big deal of how `haddock.top` files are read and stored.
We should find a way to converge both. Or make `libalign` use the new definitions in `core.supported_molecules` defined in #144.

**Comment by mgiulini** [comment]
I definitely think that `libs/libalign` should import the supported and unsupported residues from somewhere else, like `core.supported_molecules`. `libs/libalign` is a library dedicated to the alignments, and it should import all the "core" parameters rather than redefining them.

**Comment by joaomcteixeira** [comment]
Perfect, we will take care of that once both PRs are accepted.

**Comment by mgiulini** [comment]
@joaomcteixeira is this still relevant? both PR have been merged, should we take care of this as well?

**Comment by joaomcteixeira** [comment]
I believe it is still relevant.

The residues defined manually here:

https://github.com/haddocking/haddock3/blob/d19bbf6e5bb15aa4440e2af7ba16a0540ef93b1f/src/haddock/libs/libalign.py#L36-L61

should be imported from `core.supported_residues`

For example, supported amino acids are defined in:

https://github.com/haddocking/haddock3/blob/d19bbf6e5bb15aa4440e2af7ba16a0540ef93b1f/src/haddock/core/supported_molecules.py#L426

And supported nucleic acids (also counting RNA): 

https://github.com/haddocking/haddock3/blob/d19bbf6e5bb15aa4440e2af7ba16a0540ef93b1f/src/haddock/core/supported_molecules.py#L396

And here: https://www.bonvinlab.org/haddock3/reference/core/supported_molecules.html

Same for solvents or other types. Atoms are **not** specified in `supported_molecules` module.

I hope I am not missing any point. If the alignment is strict to standard residue names that, or we foresee this to be unmutable, so maybe we can ignore this issue as a whole.

**Comment by mgiulini** [comment]
Understood! I will take care of it in the coming days, thanks!

**Comment by mgiulini** [comment]
I chatted a bit with @rvhonorato and checked the data. It is more complicated than what we thought, as the `supported_aminoacids_resnames` are many, and some of them do not have all the backbone atoms (think for example of the capping residues NME and ACE). Nevertheless, currently if the residue name is not found, all the atoms are employed in the structural alignment, which is something I would avoid. That's why I would proceed with this issue and, in case many problems arise, simply solve them with the creation of an alternative `supported_aminoacids_resnames_capri` in `core.supported_residues`. What do you think?

**Comment by amjjbonvin** [comment]
If not supported, I would simply ignore

And the capping residues are indeed special cases.

**Comment by mgiulini** [comment]
they are supported, in the sense that they are part of the `src.haddock.cns.toppar.*top` files. We could limit the structural alignment to any backbone atom (C,O,N,CA) found in this big set of residues. Or just keep the current implementation.
