### ISSUE TITLE
output files in step folders

### ISSUE THREAD

**Issue by joaomcteixeira** [haddocking/haddock3#447]
Currently, each step folder has lots of files of different types: `pdb`, `psf`, `in`, `out`. Would it be valuable to store these files in respective subfolders? For example:

```
0_topoaa/
    pdb/
        # pdb files go inside this folder
    psf/
        ...
    in/
        ...
    out/
        ...
```

**Comment by amjjbonvin** [comment]
Then you need to change a lot of things… not sure it is worth it.

We also need a cleaning module that will remove/compress unnecessary stuff (should have higher priority than this).
