### ISSUE TITLE
Add a list of the non-clustered structures to `clustfcc`

### ISSUE THREAD

**Issue by joaomcteixeira** [haddocking/haddock3#480]
Does it make sense to add the list of the non-clustered structures and their respective h-scores to the end of the `clustfcc.txt` file? I vote for that. Let me know.

**Comment by amjjbonvin** [comment]
May-be rather a separate file to avoid confusions

**Comment by mgiulini** [comment]
It makes sense in my opinion. Maybe only for the top (five? ten?) unclustered structures? Or only if these unclustered structures possess a score comparable to that of the top clusters?

**Comment by joaomcteixeira** [comment]
imho, I suggest adding the list of all unclustered structures sorted by haddock score. I found that information useful while evaluating the CAPRI results. I agree with Alexandre that it should be a separate file. Like that, it is also easier to parse. We can always then use the first 5 or 10 structures with the `head` command.

**Comment by mgiulini** [comment]
Yeah, I guess you're right, the simpler the better

**Comment by amjjbonvin** [comment]
Simplest option would be to rerun the cluster with the minimum number of cluster member set to 1 - then you get a sorted list of both the clustering and non-clustering models. And I would write that in a separate file.
