### ISSUE TITLE
Add stop/exit option within a workflow

### ISSUE THREAD

**Issue by amjjbonvin** [haddocking/haddock3#492]
When executing complex / long workflows, it could be handy to have a stop or exit option to make the workflow stop after a given step. This would avoid having to delete or comment out the remaining of the workflow.

Could be useful for debugging or to check things before extending the workflow.

Could be something as simple as a `Exit` module.

**Comment by joaomcteixeira** [comment]
Going for it. :+1:
FYI, `crtl+c` will stop the workflow in a controlled manner.
