### ISSUE TITLE
correct bug in caprieval chains

### ISSUE THREAD

**Issue by mgiulini** [haddocking/haddock3#506]
an input file whose chains are A and E is not accepted by caprieval.

```
Process Worker-13:
Traceback (most recent call last):
  File "/trinity/login/mgiulini/anaconda3/envs/haddock3/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/trinity/login/mgiulini/haddock3/src/haddock/libs/libparallel.py", line 28, in run
    task.run()
  File "/trinity/login/mgiulini/haddock3/src/haddock/modules/analysis/caprieval/capri.py", line 429, in run
    self.calc_lrmsd()
  File "/trinity/login/mgiulini/haddock3/src/haddock/modules/analysis/caprieval/capri.py", line 148, in calc_lrmsd
    l_start, l_end = chain_ranges[self.l_chain]
KeyError: 'B'
```

The root of this error lies in the parameters `self.r_chain`,` self.l_chain` of caprieval, which, by default, are A and B. Given the wide spectrum of haddock3 scenarios that can be run, the solution is not trivial. My suggestion here is to check if the default chain is present and, if not, use the available chain IDs.

@rvhonorato let me know if you have comments on this

**Comment by rvhonorato** [comment]
I think I left this A/B hardcoded there because there's no chain-matching and no support for multi-body analysis (#164) so it was expected for the model and reference to always be A/B.

> My suggestion here is to check if the default chain is present and, if not, use the available chain IDs.

For me makes more sense to always use the available chainIDs instead of A/B and raise an error if there's no correspondence between the chains until we do #179

**Comment by mgiulini** [comment]
uh, I read just now sorry, I already implemented that solution in the PR above.. I see your point, the problem is that we would like to give the (expert) user the freedom to define the receptor and ligand chain IDs (for ex. using B as `receptor_chain` and A as `ligand_chain`), right?
My implementation checks if the input parameters `receptor_chain` and `ligand_chain` do actually exist and, if not, uses the available ones. What do you think?
