### ISSUE TITLE
Uniform file extensions in result files

### ISSUE THREAD

**Issue by joaomcteixeira** [haddocking/haddock3#528]
Apart from the PDBs and CNS files, modules sometimes write tables or extra files with information. Currently, these files have different extensions; some are `txt`, and some are `tsv`. When in a step folder with thousands of files, using the command `ls *.tsv`, for example, is useful to see which files the module has created. However, users have to try at least two attempts with the different extensions before getting the desired list.

I suggest that all files created by modules that refer to tables, summaries, notes, reports, whatever, have all the same extension. For example, `txt` is a good one. But we can come up with a haddock3-specific extension. Even if the file is a tab-separated table, it is best to have a uniform extension, IMHO.

Suggestions are:

- `txt`
- `hd3`

Finally, deciding on a uniform extension ensures that if haddock3 globally produces five or six different types of files in the future, we don't have all that many extensions.

**Comment by amjjbonvin** [comment]
I would not use a haddock-specific extension. This is confusing.

.txt .tsv .csv are standard formats

Note that .tsv and .csv and also text files. So if we have to choose one I would go simply for .txt

**Comment by joaomcteixeira** [comment]
I agree with `txt` throughout.

**Comment by amjjbonvin** [comment]
What we should avoid is a mixture of csv and tsv
> I agree with txt throughout.
> 
> —
