### ISSUE TITLE
Add support for 3-hydroxyproline (HY3)

### ISSUE THREAD

**Issue by joaomcteixeira** [haddocking/haddock3#532]
Following https://github.com/haddocking/haddock/issues/535

This is the first time we try to add a new molecule after #144.

Steps to perform:

1. add the `molecule.top` and `molecule.param` to `cns/toppar` folder.
2. add the file to the `supported_molecules` file as done in https://github.com/haddocking/haddock3/pull/508
3. if there's no need to add new `top` and `param` files, if you can add the molecule specifications to the already existing `param` and `top` and haddock3 will take care of the rest. In this case NO need to edit `supported_molecules`.
4. regarding CNS files, need to add them as much as necessary in `cns/` folder or `cns/toppar` folder. Please mind the variable path pointing to that folder in case you need to use it anywhere in the program: https://github.com/haddocking/haddock3/blob/7a60102b6d4f125e02ed54301d7f7a523e667845/src/haddock/__init__.py#L17

looking forward to work on this together @amjjbonvin

**Comment by amjjbonvin** [comment]
> Steps to perform:
> 
> if there's no need to add new top and param files, if you can add the molecule specifications to the already existing param and top and haddock3 will take care of the rest. In this case NO need to edit supported_molecules.
In this particular case they would go in the regular protein topo/param files.
> regarding CNS files, need to add them as much as necessary in cns/ folder or cns/toppar folder. Please mind the variable path pointing to that folder in case you need to use it anywhere in the program:
The CNS scripts are module-dependent. I.e. all relevant modules will have to be updated.

For this particular case, it is simply looking for all CNS scripts that contain HYP (4-hydroxyproline) and add the required info for HY3

**Comment by joaomcteixeira** [comment]
> For this particular case, it is simply looking for all CNS scripts that contain HYP (4-hydroxyproline) and add the required info for HY3

following what you did for haddock2.x?

**Comment by joaomcteixeira** [comment]
> For this particular case, it is simply looking for all CNS scripts that contain HYP (4-hydroxyproline) and add the required info for HY3

following what you did for haddock2.x?

**Comment by joaomcteixeira** [comment]
I agree! :-D
