### ISSUE TITLE
Create a docs page with user friendly supported molecules

### ISSUE THREAD

**Issue by joaomcteixeira** [haddocking/haddock3#534]
I am happy this addition went through so smoothly.
The documentation has that information, but it is very technical and is extracted automatically from the `supported_molecules.py` file. Surely, we should work out a more user-friendly way. I will try to address it.

_Originally posted by @joaomcteixeira in https://github.com/haddocking/haddock3/pull/533#pullrequestreview-1063378697_

**Comment by Jameel9** [comment]
Hi @joaomcteixeira 

I hope this comment finds you well.
I am planning to introduce 2 new modified amino acids into a local installation of Haddock3. My goal it make Hd3 treats them like a standard amino acids. Is it possible? 
If yes, Could you please mention the files I need to edit other than the protein-allhdg5-4.tpo and the protein-allhdg5-4.param files, if any?

Thanks in advance!

Regards,
Jameel

**Comment by amjjbonvin** [comment]
Yes indeed you will have to edit the top and param files, but also the linkage file to make sure your modified amino acid get connected to its neighbours - not so simple.

You will probably have to debug things to figure out missing parameters and such.
For this run a simple test, e.g. only topoaa + emscoring with debug=true

In that way you can check the out files for errors.

**Comment by Jameel9** [comment]
Thank you so much professor @amjjbonvin !

I still have a question about the designations in those linkage files. The remark section doesn't give a clue.
Could you please clarify what do these abbreviations mean:
ppgp
ppgg
ppg1
ppg2
pepp
pept 
pctn

Thank you in advance!

Regards,
Jameel

**Comment by amjjbonvin** [comment]
These are patches that are applied to the two amino acids forming the peptide.

The patches themselves are defined in the top file 

This is CNS topology/parameter stuff, not specific to HADDOCK.

`pept` is the default patch to create peptide bonds. But some amino acids do require some special patches (e.g. Pro and Gly)

**Comment by Jameel9** [comment]
Dear @amjjbonvin 

Thank you for your support and sorry to bother you with this again.

If I need to introduce a new cyclization bonding into Haddock3 using 2 residues not supported yet, I need to do the following:
  1. Add the topology and parameter details of the new residues into the protein-allhdg5-4.top and protein-allhdg5-4.param files.
  2. Add a presidue into the protein-allhdg5-4.top to specify the cyclization topology.
  3. Add the linkage details into the .link files
  4. Create a .cns script in the modules/topology/topoaa/cns directory 
  5. Refere to this .cns file in the generate-topology.cns script so that the patch is read.
If those steps were done correctly, the cyclization is expected after the distance restraints pulled the cyclization atoms closer to each other, right?

Thanks again and regards,
Jameel

**Comment by amjjbonvin** [comment]
That sounds indeed like the correct steps


> If I need to introduce a new cyclization bonding into Haddock3 using 2 residues not supported yet, I need to do the following:
> Add the topology and parameter details of the new residues into the protein .top and .param files.
> Add the linkage details into .link files
> Create a .cns script in the modules/topology/topoaa/cns directory

> Refere to this .cns file in the generate-topology.cns script so that the patch is read.
> If those steps were done correctly, the cyclization is expected after the distance restraints pulled the cyclization atoms closer to each other, right?
> 
Yes - depending of course on the cutoff distance you define to identify the covalent bond

If you manage to make it work, do create a pull request for it so that others can benefit from it.

**Comment by Jameel9** [comment]
Dear professor @amjjbonvin and Haddock3 team,

So, my goal was to create a patch to support RaPID system cyclization (ACE is covalently linked to the SG atom of a modified cysteine). The cyclization is as follow:

<img width="1100" height="580" alt="Image" src="https://github.com/user-attachments/assets/872db36f-ac32-46ce-b0e5-a01048328222" />


For some reason, I want the ACE to be treated as if it's an amino acid (hence I changed the name to ACY). 
I created a topology entry for both (ACY and the modified cysteine - the terminal OH is substituted by NH2, i call it CYY) as follows:

```
residue ACY   ! special ACE for RaPID cyclization
  group
    ATOM CA    TYPE=CH3E CHARge= 0.000 end  ! RaPID cyclization atom
    ATOM HA1   TYPE=HA   CHARge= 0.000 end
    ATOM HA2   TYPE=HA   CHARge= 0.000 end
    ATOM HA3   TYPE=HA   CHARge= 0.000 end
    ATOM C     TYPE=C    CHARge= 0.500 end
    ATOM O     TYPE=O    CHARge=-0.500 end

  BOND C  CA     BOND CA HA1     BOND CA HA2   BOND CA HA3
  BOND C  O
  
  IMPRoper HA1 HA2 CA HA3  !methyl CA
  
  ACCE O    C
end
```

then CYY
```
residue CYY             ! special for RaPID cyclization
  group
    ATOM N    TYPE=NH1    CHARge=-0.570 end
    ATOM HN   TYPE=H      CHARge= 0.370 end
    ATOM CA   TYPE=CH1E   CHARge= 0.200 end
    ATOM HA   TYPE=HA     CHARge= 0.000 end
    ATOM CB   TYPE=CH2E   CHARge= 0.180 end
    ATOM HB1  TYPE=HA     CHARge= 0.000 end
    ATOM HB2  TYPE=HA     CHARge= 0.000 end
    ATOM SG   TYPE=SH1E   CHARge=-0.163 end ! Gasteiger charge of sulfur in Diethyl sulfide.
    ATOM HG   TYPE=H      CHARge= 0.270 end 
    ATOM NH1  TYPE=NC2    CHARge=-0.800 end ! similar to NH2 groups in ARG side chain
    ATOM HH11 TYPE=HC     CHARge= 0.460 end
    ATOM HH12 TYPE=HC     CHARge= 0.460 end
    ATOM C    TYPE=C      CHARge= 0.500 end
    ATOM O    TYPE=O      CHARge=-0.500 end

  BOND N  HN
  BOND N  CA     BOND CA HA
  BOND CA CB     BOND CB HB1      BOND CB HB2
  BOND CB SG     BOND SG HG
  BOND CA C
  BOND C  NH1    BOND NH1 HH11    BOND NH1 HH12
  BOND C  O
  
  ANGLe CA  C  NH1  

  IMPRoper HA  N   C   CB      !chirality CA
  IMPRoper HB1 HB2 CA  SG      !stereo CB
  IMPRoper CA  C   O   NH1      
  
  DIHEdral SG CB  CA  N
  DIHEdral C  CA  CB  SG
  DIHEdral CB CA  C   N
  DIHEdral CB CA  C   O

  DONO HN   N
  DONO HH11 NH1
  DONO HH12 NH2
  DONO HG  SG
  ACCE O    C
end
```

and because ACE has only 2 carbon atoms, hence no room for an atom equivalent to CB for the dihedrals in the pept patch, I had to create a special connectivity patch
```
PRESidue NACY                   ! N-ter ACY for RaPID cyclization 

  add BOND -C +N

  add ANGLe -CA -C +N
  add ANGLe -O  -C +N
  add ANGLe -C  +N +CA
  add ANGLe -C  +N +HN

  add IMPRoper  -C -CA +N -O                 ! planar -C
  add IMPRoper  +N -C +CA +HN                ! planar +N
  add IMPRoper -CA -C  +N  +CA               ! ANGLe across peptide plane

! phi/psi related topology UCL 05-JUL-01

  add DIHEdral  -C +N +CA +C  mult 6


  ! CB-related dihedrals are omitted because ACY has none.

end
``` 
and edited the .link files (specifically, protein-allhdg5-4.link and protein-allhdg5-4-noter.link only) using the nacy patch.

The patch to create the cyclization was created as:

```
presidue ACYS                         ! RaPID cyclization to connect ACY CA to CYY SG 
  group
    delete    ATOM 1HA3              end
    MODIfy    ATOM 1CA  TYPE=CH2E    CHARge=0.235 end
  
  group
    delete    ATOM 2HG               end
    MODIfy    ATOM 2SG               CHARge=-0.470  end 
    MODIfy    ATOM 2CB               CHARge= 0.235  end
    
  add BOND 1CA 2SG
  
  add ANGLe 1C  1CA  2SG 
  add ANGLe 1CA 2SG  2CB 
  add ANGLe 1HA1 1CA 2SG 
  add ANGLe 1HA2 1CA 2SG 
  add ANGLe 1HA2 1CA 1HA1 

  add IMPRoper 1HA1 1HA2 1CA 2SG   
  add DIHEdral 2C  2CA 2CB 2SG
  add DIHEdral 1C  1CA 2SG 2CB
  add DIHEdral 1CA 2SG 2CB 2CA  

end
```

and the parameters in the .param as follow (the values here were taken from only one structure.. will be updated later):

```
!for RaPID cyclization 
 ANGLe     CH1E  C     NC2         500.000 {sd=     0.031}     109.4570
 ANGLe     CH1E  CH2E  SH1E        500.000 {sd=     0.031}     109.4570
 ANGLe     C     CH2E  SH1E        500.000 {sd=     0.031}     104.4570
 ANGLe     CH2E  SH1E  CH2E        500.000 {sd=     0.031}      98.4570
 IMPRoper  CH1E  C     O    NC2    500.000 {sd=     0.031}   0 180.0000
 DIHEdral  C    CH1E  CH2E   SH1E    1.000                   3 -56.0000
 DIHEdral  CH2E CH1E  C   NH1        1.000                   3 128.0000
```


and finally the rapid-cyc.cns script in the topoaa dir
```
! RaPID cyclization

for $id1 in id ( name CA and resn ACY ) loop acy

    show (segid) (id $id1)
    evaluate ($segid1=$result)
    show (resid) (id $id1)
    evaluate ($resid1=$result)

    evaluate ($mindis = 4.0)  
    evaluate ($minid  = 0)
    
    for $id2 in id ( name SG and (id $id1) around 4.0 and resn CYY ) loop search
        pick bond (id $id1) (id $id2) geometry
        
        if ( $result < $mindis ) then
            evaluate ($mindis = $result)
            evaluate ($minid = $id2)
        end if
    end loop search
     
    if ($minid > 0) then
        patch acys 
            reference=1=(resid $resid1 and segid $segid1) 
            reference=2=(byres (id $minid)) 
        end
        
        display RAPID-CYC: LINKED ACY-CA ($resid1) TO CYY-SG (via $minid)
    end if

end loop acy
```
and finally referred to this script in the generate-topology.cns as follows:
```
! check for RaPID cyclization
inline @MODULE:rapid-cyc.cns
 
```

Could you please help by pointing out where things went wrong.
Thanks in advance!

Regards,
Jameel

**Comment by amjjbonvin** [comment]
Can you create a branch of your implementation, push it to GitHub (your clone or this repo), together with an example containing all data the test it?

Please send us the link to your branch

Also this should rather be a new issue.

**Comment by amjjbonvin** [comment]
Actually what you want to do is already implemented in HADDOCK3…

You simply need an ACE on the N-ter and keep the CYS as CYS

But in the config file you will have to define in the topoaa module that your molecule is cyclic, e.g.:

```
[topoaa]
[topoaa.mol1]
cyclicpept = True
```

And this should work provided the ACE and the CYS atoms to be connected are within the cutoff distance.

This is implemented in:  https://github.com/haddocking/haddock3/blob/main/src/haddock/modules/topology/topoaa/cns/coval-ace-cys.cns

Check also the peptide-cyclisation example for a workflow that will first bring the termini together and then create the cyclic bond (this one if however for a cyclic peptide bond).

**Comment by Jameel9** [comment]
Thank you professor @amjjbonvin for your quick reply.

I did try that before (after I read the cyclization paper and its example tutorials). 
The input I am using and the cfg are attached. The distance restraints to bring the termini were defined as: 
```
assign (resid 1 and name CA) (resid 16 and name SG) 1.7 0.1 0.1
assign (resid 1 and name CA) (resid 16 and name CB) 2.7 0.1 0.1
``` 
but it didn't cyclize. Moreover, the cysteine in RaPID is modified at the C-ter end. That was the reason I planned to add new entries.

[input_plus_cfg.zip](https://github.com/user-attachments/files/27043672/input_plus_cfg.zip)

**Comment by amjjbonvin** [comment]
Ok found the problem - a too distance distance cutoff for detection.

I opened a new issue about this - see https://github.com/haddocking/haddock3/issues/1535
