### ISSUE TITLE
create alpha version of optint module

### ISSUE THREAD

**Issue by mgiulini** [haddocking/haddock3#545]
related to #515. The idea is to create a module that optimizes an interface (provided in input) by properly minimizing the haddock score of the complex.

The first, preliminary step is to implement it as a simple simulated annealing optimization, possibly with some mdref step from time to time to improve the refinement.

Big caveat: if this ever becomes a proper haddock3 module, its execution should be accompanied by clear warning messages that this is very experimental and (so far) untested.

Discussed with @amjjbonvin and @rvhonorato

**Comment by joaomcteixeira** [comment]
Friendly reminder, there's a structure to hold/store modules under development (experimental) -> https://github.com/haddocking/haddock3/pull/520

Cheers,
