### ISSUE TITLE
handle single chain models in caprieval

### ISSUE THREAD

**Issue by mgiulini** [haddocking/haddock3#547]
single chain models can reach the caprieval stage for several reasons.
The module should be able to correctly report the "problem" to the user without aborting the run.

**Comment by joaomcteixeira** [comment]
Does that happen even when using `preprocess=true` ? This is a good example to test also the `preprocess` functionality :wink:
Cheers!

**Comment by mgiulini** [comment]
> Does that happen even when using `preprocess=true` ? This is a good example to test also the `preprocess` functionality 😉 Cheers!

Anna tried this option, but she didn't notice any apparent change since the previous run. I think these single chain files should not be spotted as problematic by the preprocessing, as they can be relevant in many modules. It's just in `caprieval` that they make little sense :)

**Comment by joaomcteixeira** [comment]
Understood :wink: thanks for clarifying
