### ISSUE TITLE
update refine-complex example

### ISSUE THREAD

**Issue by mgiulini** [haddocking/haddock3#549]
currently the .cfg example file `refine-complex-test.cfg` refines two chains of the same complex.

https://github.com/haddocking/haddock3/blob/ee9b4d56fd554e82ec587cc49df5fe9c4db42204/examples/refine-complex/refine-complex-test.cfg#L11-L14
Let's update it by using a complex in input, so that it can be refined and compared to the ground truth with `caprieval`

**Comment by amjjbonvin** [comment]
The script actually refines the complex provided as two chains. I.e. the caprieval module should not give problems with this example.

**Comment by mgiulini** [comment]
I am afraid this is not the case currently..the two molecules are refined independently by mdref (each one gives rise to `sampling_factor`(10) refined structures) and then fed to the caprieval module. The two chains are never merged. I think this is reasonable, and this is why I would update the example with a complex in input..

**Comment by amjjbonvin** [comment]
Then this is a bug!

**Comment by mgiulini** [comment]
I am closing this as this is not relevant anymore. #553 reverted the logic to the haddock2.4 one, in which a model to be refined must be provided in two separate chains.
