### ISSUE TITLE
remove sampling parameter from emref

### ISSUE THREAD

**Issue by mgiulini** [haddocking/haddock3#550]
we currently accept the `sampling` parameter in the defaults.yaml of `emref`, without using it to my knowledge. The `sampling_factor` parameter should be used instead
https://github.com/haddocking/haddock3/blob/ee9b4d56fd554e82ec587cc49df5fe9c4db42204/src/haddock/modules/refinement/emref/defaults.yaml#L1334-L1343
I would remove it so that it doesn't generate confusion.

**Comment by amjjbonvin** [comment]
This must also apply to `mdref` and `flexref` 

I guess the `seletop` module defines the number of models to sample.

But what if there is no `seletop` module defined in the workflow and we go directly from `rigidbody` to e.g. `emref`

Will it then refine all models from the rigid body stage or limit it to 200?

**Comment by mgiulini** [comment]
> This must also apply to `mdref` and `flexref` 

mdref and flexref do not have the sampling parameter in their defaults.yaml

> I guess the `seletop` module defines the number of models to sample. But what if there is no `seletop` module defined in the workflow and we go directly from `rigidbody` to e.g. `emref` Will it then refine all models from the rigid body stage or limit it to 200?

Yes, currently every refinement module refines all the models retrieved from the previous step. Should we add a `max_nmodels` parameter limiting the number of models to refine? It might be useful especially for flexref and mdref.

**Comment by amjjbonvin** [comment]
But without a `seletop` step, the order of the models will not match their score/rank…

So dangerous to add a max_nmodels since you might then select a random selection

**Comment by mgiulini** [comment]
It would not be that difficult, since each model has the score attribute. but yes, I guess that this check would fall far away from the scope of a refinement module..
