### ISSUE TITLE
haddock-copy issues when dealing with empty data folders

### ISSUE THREAD

**Issue by mgiulini** [haddocking/haddock3#559]
Currently the `haddock-copy` cli display an error message when one of the modules to be copied does not have a corresponding folder in the `run/data` directory.

Example: the docking-protein-protein-test example generates the following directories:
`0_topoaa 1_rigidbody 2_caprieval 3_seletop 4_flexref 5_caprieval 6_emref 7_caprieval 8_clustfcc`
running the following command
`haddock3-copy -r run1-test -m 0 1 3 4 -o run1-test-new`
causes an error
`FileNotFoundError: [Errno 2] No such file or directory: 'run1-test/data/3_seletop'`
because `seletop` does not produce a `data` folder (like `caprieval` and many other modules).

**Comment by joaomcteixeira** [comment]
```python
from contextlib import suppress

with suppress(FileNotFoundError):
    # do the copy
```

This in the correct place might be enough :wink: :+1:
