### ISSUE TITLE
reduce filename length in docking-protein-peptide

### ISSUE THREAD

**Issue by mgiulini** [haddocking/haddock3#561]
one of the molecules in the example `docking-protein-peptide` (`DAIDALSSDFT_3conformations.pdb`) has a quite long filename, which may cause troubles to cns (exceeding maximum filename length) if the haddock3 installation is a bit nested.

**Comment by mgiulini** [comment]
Yes, I am using them. The point is that it seems that when an ensemble is provided the machinery converts the relative paths to full paths, thus causing potential problems to CNS topology generation. Check for example the cns input files in the `docking-protein-peptide/run1-mdref-test/0_topoaa` or in `docking-protein-protein/run1-clt-test/0_topoaa/`. I think the splitting operated here https://github.com/haddocking/haddock3/blob/aa68fd3abf3ebe9e3c7c34812639761c7be9d69c/src/haddock/modules/topology/topoaa/__init__.py#L160-L163
provides full paths by default

**Comment by amjjbonvin** [comment]
There should be an option in the config file to set it to use relative paths.

self_contained = True

But if this not solves this issue, then that part of the code must be changed.

The length of the filename is not the issue here, more the length of the path


> Yes, I am using them. The point is that it seems that when an ensemble is provided the machinery converts the relative paths to full paths, thus causing potential problems to CNS topology generation. Check for example the cns input files in the docking-protein-peptide/run1-mdref-test/0_topoaa or in docking-protein-protein/run1-clt-test/0_topoaa/. I think the splitting operated here https://github.com/haddocking/haddock3/blob/aa68fd3abf3ebe9e3c7c34812639761c7be9d69c/src/haddock/modules/topology/topoaa/__init__.py#L160-L163 <https://github.com/haddocking/haddock3/blob/aa68fd3abf3ebe9e3c7c34812639761c7be9d69c/src/haddock/modules/topology/topoaa/__init__.py#L160-L163>
> provides full paths by default
>

**Comment by mgiulini** [comment]
Yes, that option does not solve the issue, it just copies the cns executables to the folder, but here the problem resides in the file paths. I will correct this asap :)
