### ISSUE TITLE
Booleans with capitals

### ISSUE THREAD

**Issue by amjjbonvin** [haddocking/haddock3#575]
**Describe the bug**

Booleans write with a capital letter cause an error when running haddock3.
It seems to come from the toml support that requires only small letters.
This is however not consistent with what we have in the default yaml files.

**To Reproduce**
Steps to reproduce the behavior, if relevant, provide the input that triggered the error:

Define a boolean starting with a capital letter, e.g.

randomremoval = False

**Expected behavior**

It is a rather trivial thing - I would think that raising an error for this is not necessary and the booleans can be transformed internally to lower case.

**Comment by joaomcteixeira** [comment]
The thing to be careful about is for example, if some path is named `true`. That should not be changed, for example: `/home/user/calc/True/`. I think this is the only tricky part.

**Comment by amjjbonvin** [comment]
Those would be between double quote, right?

**Comment by joaomcteixeira** [comment]
I think so. I think we can't avoid using some `regex` :smiling_imp: . with `str.replace` in python won't be enough.

**Comment by amjjbonvin** [comment]
In principle HADDOCK itself doesn’t care. Same thing for the CNS engine.

This is thus only a requirement for third party software that would read our config files (such as the iVRESSE workflow builder).
