### ISSUE TITLE
Adding the config file to the data dir of a run

### ISSUE THREAD

**Issue by amjjbonvin** [haddocking/haddock3#578]
**Is your feature request related to a problem? Please describe.**

It would be nice and useful to copy the original config file of a run to the data dir of the run.
Currently we don't store it in the run which is not optimal for reproducibility.

**Describe the solution you'd like**

Simply copy the original cfg file to the run/data directory

**Comment by joaomcteixeira** [comment]
Correct.
For the note: each module's folder contains the config file for that module.

**Comment by amjjbonvin** [comment]
But we don’t save the config of the full workflow, which would be handy to have for reproducibility

**Comment by VGPReys** [comment]
At which point do we want to have reproducibility ?
- From the raw user input file ?
- From the cleaned user input file ?
- From the toml parsed input file ?
- From the Haddock3 enhanced input file ?
- From all of the above ?

**Comment by amjjbonvin** [comment]
In principle from all of the above, BUT…

you can only ensure reproducibility by running on the same hardware...
