### ISSUE TITLE
check for the existence of restraints defined in tbl files

### ISSUE THREAD

**Issue by mgiulini** [haddocking/haddock3#595]
it is possible that one or more distance restraints defined in .tbl files do not exist, namely at least one of the two residues does not exist in the reference structure.

It would be nice to implement a python-based check such that the execution

- **stops** if all the restraints do not exist
- **raises a warning** if at least one restraint cannot be defined

Where to place it? at the beginning of the workflow? before each CNS execution?

**Comment by amjjbonvin** [comment]
As we might have different restraints for different modules we might need such a check for each modules

**Comment by mgiulini** [comment]
exactly.
Moreover, each module can in principle process different models, so the check should be run for each model. Probably better to place it at the beginning of the workflow then, to reduce the computational burden..
