### ISSUE TITLE
haddock3-analyse: export image, matplotlib vs plotly

### ISSUE THREAD

**Issue by SarahAlidoost** [haddocking/haddock3#624]
Currently, the command `haddock3-analyse` takes `png` and `dpi` arguments, see [here](https://github.com/haddocking/haddock3/blob/492b6b07924d7a8912c320d447dfc7bfe0b70b51/src/haddock/clis/cli_analyse.py#L102-L116). The module [libplots.py](https://github.com/haddocking/haddock3/blob/main/src/haddock/libs/libplots.py) uses `matplotlib` if `png` otherwise `plotly`. Note that `matplotlib` has not been added to the package dependencies. 

However, `plotly` supports exporting images to different formats if the package `kaleido` is installed, see [Static Image Export in Python](https://plotly.com/python/static-image-export/). As explained in doc, with only one function `fig.write_image(f"fig.{format}")`, it is possible to export image to different formats. 

The definitions of figure size and dpi are also different:
-  `matplotlib`: `dpi` for resolution, figure size in inches
-  `plotly`:  `scale` for resolution, figure size in px

Here, I show two examples provided in the documentation of each tool with default values.

```python
import numpy as np
np.random.seed(1)

N = 100
x = np.random.rand(N)
y = np.random.rand(N)
colors = np.random.rand(N)
area = (30 * np.random.rand(N))
```

**[Example: plotly scatter](https://plotly.com/python/static-image-export/)**
```python
import plotly.graph_objects as go
plotly_fig = go.Figure() 
plotly_fig.add_trace(go.Scatter(
    x=x,
    y=y,
    mode="markers",
    marker=go.scatter.Marker(
        size=area, #Sets the marker size (in px).
        color=colors,
        opacity=0.6,
        colorscale="Viridis"
    )
))
plotly_fig.write_image("plotly_fig.png") # scale=1 default: [700, 450] width, height in px
plotly_fig.show()
```
![plotly_fig](https://user-images.githubusercontent.com/55081872/220636506-5f70d40a-2310-4cb8-a31b-cbbcb1cbf703.png)

**[Example: matplotlib scatter](https://matplotlib.org/stable/gallery/shapes_and_collections/scatter.html#sphx-glr-gallery-shapes-and-collections-scatter-py)**
```python
import matplotlib.pyplot as plt
matplotlib_fig = plt.figure() #default: [6.4, 4.8]: Width, height in inches ~ [614.4, 460.8] Width, height in inches in px
plt.scatter(x, y, s=area**2, c=colors, alpha=0.6)
plt.savefig("matplotlib_fig.png") # dpi =100
```

![matplotlib_fig](https://user-images.githubusercontent.com/55081872/220636462-ee134341-dbeb-4dc6-a859-e01fb2da5f92.png)

File size:
```bash
76K	matplotlib_fig.png
60K	plotly_fig.png
```

**Comment by SarahAlidoost** [comment]
@mgiulini following our previous discussion, here are examples of exporting images using matplotlib and plotly :blush:

**Comment by mgiulini** [comment]
Hi @SarahAlidoost , thank you very much for the suggestion! I remember trying to do this export in plotly and having all sorts of problems, but using kaleido is pretty easy and works fine
I will open a PR with this change and delete the matplotlib part, less chances to have bugs/problems in the future :)

**Comment by joaomcteixeira** [comment]
I suggest exporting in vectorial format, hence `.pdf`, because the file size will be minimal, and users can amplify plots to infinity or convert later to `png` if needed.

**Comment by mgiulini** [comment]
that is possible as well.. @SarahAlidoost @sverhoeven would you prefer to have pdf files in output from` haddock3-analyse`?

**Comment by amjjbonvin** [comment]
PDF format (or eps) are probably best indeed. 
In principle we could even generate both png and PDF (or eps).

**Comment by mgiulini** [comment]
I like @SarahAlidoost 's suggestion to put a `format` keyword in the command line, so that the user can decide the format (among the many available, including png, pdf, svg..). Unfortunately the .eps extension seems to require an additional library
