### ISSUE TITLE
Got all results irmsd,fnat,lrmsd,dockq in nan

### ISSUE THREAD

**Issue by hanzhiz** [haddocking/haddock3#641]
Hello,

I tested antibody-antigen docking using the testing example and my data. But I always get irmsd,fnat,lrmsd,dockq in nan in the final capri_clt and Capri_ss file. But I got the final score, but I don't know whether this score haddock score or capri score. If it is the capri score, how it got calculated without irmsd,fnat,lrmsd,dockq. Whether this score still reliable? And how to solve this issue. 

Thanks,

Hanzhi

# ====================================================================
# Protein-protein docking example with NMR-derived ambiguous interaction restraints

# directory in which the scoring will be done
run_dir = "/data/haddock3/abag/run1"

# compute mode
mode = "mpi"
#  5 nodes x 8 tasks = ncores = 20
ncores = 80

# molecules to be docked
molecules =  [
    "data/ab.pdb",
    "data/ag.pdb"
    ]

# ====================================================================
# Parameters for each stage are defined below, prefer full paths
# ====================================================================
[topoaa]

[rigidbody]
# CDR to surface ambig restraints
ambig_fname = "data/ab-ag-ambig.tbl"
# turn on random definiton of AIRs
ranair = false
# for antibody sample only CDR loops
nrair_1 = 3
rair_sta_1_1 = 30
rair_end_1_1 = 33
rair_sta_1_2 = 51
rair_end_1_2 = 59
rair_sta_1_3 = 96
rair_end_1_3 = 107

sampling = 10000

[caprieval]
reference_fname = "data/ag.pdb"

[clustfcc]
threshold = 4

[seletopclusts]
## select the best 4 models of each cluster
top_models = 20
##select all the models
#top_models = NaN

#[seletop]
#select = 500

[caprieval]
reference_fname = "data/ag.pdb"

[flexref]
tolerance = 50
# CDR to surface ambig restraints
ambig_fname = "data/ab-ag-ambig.tbl"

[caprieval]
reference_fname = "data/ag.pdb"

[emref]
# CDR to surface ambig restraints
ambig_fname = "data/ab-ag-ambig.tbl"

[caprieval]
reference_fname = "data/ag.pdb"

[clustfcc]

[seletopclusts]

[caprieval]
reference_fname = "data/ag.pdb"

# ====================================================================

**Comment by amjjbonvin** [comment]
If testing with your own data you probably need to remove the reference lines in the caprieval module or make sure you have a properly formatted PDB) and with chains matching your docking system)

=================================
 Prof. A.M.J.J. Bonvin | Faculty of Science
 Scientific Director Bijvoet Centre
 Utrecht University | bonvinlab.org 
 ***@***.*** | T: +31 30 2533859 
=================================

**Comment by mgiulini** [comment]
Hi there! yes, try to remove the `reference_fname` line: here you are using the antigen structure (`ag.pdb`) as a reference, so no CAPRI quantities can be calculated (the reference should be a complex itself, ideally the experimental complex). The score you get in the table should be correct though.

**Comment by hanzhiz** [comment]
Yes thanks for your help!
