### ISSUE TITLE
CNS can't be downloaded or requested 

### ISSUE THREAD

**Issue by Archit01** [haddocking/haddock3#651]
CNS can't be downloaded or requested from the link provided in install document. 
That page doesn't exist.
So is there anything alternative to compile Haddock or download precompiled one along with CNS.

**Comment by amjjbonvin** [comment]
Can you be more specific about which link you are referring to?

Installation instructions can be found at: https://www.bonvinlab.org/haddock3/INSTALL.html
And for the CNS installation at: https://www.bonvinlab.org/haddock3/CNS.html

**Comment by Archit01** [comment]
This link for requesting CNS i.e [Request for Cns](http://cns-online.org/cns_request/)is not working.
![IMG_20230514_130929](https://github.com/haddocking/haddock3/assets/39849184/f478e9e0-45c9-4c23-9781-bc7c2716694b)

**Comment by Archit01** [comment]
Looks like issue is fixed I just checked it again and form is now available.
Thank you

**Comment by Joseph-Vineland** [comment]
The link is down again and CNS is unavailable.

**Comment by amjjbonvin** [comment]
Works for me... And not under our control.

**Comment by Joseph-Vineland** [comment]
![CNS_not_available](https://github.com/haddocking/haddock3/assets/39279329/c6ec9192-c808-4246-89ad-930701d0aac5)

Thank you for the reply.  The link for requesting/downloading CNS is not working for me.  See image.  Is there any other place one can download CNS?  I can't find any.  Since I can't download CNS from anywhere, I can not use haddock3.

**Comment by amjjbonvin** [comment]
Try simply http://cns-online.org/v1.3/ and click on the download menu on the left

The instructions have been updated. But also not this is a http and not https link and some browsers might block it.
This CNS site is not under our control.
