### ISSUE TITLE
Update to glycan linkage support introduced a bug in 1-6 linkages

### ISSUE THREAD

**Issue by amjjbonvin** [haddocking/haddock3#659]
**Describe the bug**

A wrong atom selection for the beta 1-6 linkage detection in the topoaa module caused wrong connectivity of the generated glycans.
The affected CNS file is `bondglycans.cns`

**Expected behavior**

Correct connectivity

Note that this is not present in haddock2.X as the beta 1-6 linkage was not added (yet)

**Comment by rvhonorato** [comment]
for the record: Issue was reported by a community member via our slack communication channel.
