### ISSUE TITLE
Add rank info to interactive graphs

### ISSUE THREAD

**Issue by amjjbonvin** [haddocking/haddock3#665]
In the nice graphical analysis of results, it would be nice to add the rank of a model (or cluster) in the info provided when hovering over a point in the graph. This should be the caprieval_rank

**Comment by SarahAlidoost** [comment]
`caprieval_rank` is added in #666 . Here are screenshots for "Unclustered", "clusters" and "Other" for both scatter and box plots.
**"Unclustered", scatter:**
![plots_5](https://github.com/haddocking/haddock3/assets/55081872/f2d585ed-08e3-4713-a5bd-e20e8fbab7ce) 
**"Unclustered", box:**
![plots_6](https://github.com/haddocking/haddock3/assets/55081872/1a612851-6692-422f-83c5-165b3460ff6e)

**"clusters", scatter:**
![plots_7](https://github.com/haddocking/haddock3/assets/55081872/b552c1d2-c54c-40de-bfe2-d64b247b9f55)
**"clusters", box:**
![plots_9](https://github.com/haddocking/haddock3/assets/55081872/e857cfc5-4e45-49bb-8a3f-f0b909ad2e02)

**"Other", scatter:**
![plots_8](https://github.com/haddocking/haddock3/assets/55081872/5c4d9396-994f-48e7-accc-7bf9377370bf)
