### ISSUE TITLE
Structure viewer in report.html show multiple pdbs

### ISSUE THREAD

**Issue by sverhoeven** [haddocking/haddock3#670]
**Describe the bug**
The structure viewer in report.html produced by the haddock3-analyse is showing multiple pdbs at the same time. 

**To Reproduce**
Steps to reproduce the behavior, if relevant, provide the input that triggered the error:
1. I took copy of https://github.com/haddocking/haddock3/blob/main/examples/docking-antibody-antigen/docking-antibody-antigen-ranairCDR-full.cfg
2. Set sampling of rigidbody to 1000 and select to 50
3. Ran haddock3 and haddock3-analyse
4. Open analysis/11_caprieval_analysis/report.html in browser
5. View best structure 1 in cluster 1
6. Close it
7. View best structure 2 in cluster 1
8. Both cluster_1_model_1.pdb & cluster_1_model_2.pdb are shown in viewer.

**Expected behavior**
To only see structures from cluster_1_model_2.pdb

**Screenshots**
![localhost_3000_jobs_6_files_output_analysis_11_caprieval_analysis_report html](https://github.com/haddocking/haddock3/assets/1713488/99a54891-6230-4a59-8640-945e5cb09a4a)

**Comment by VGPReys** [comment]
Closed by https://github.com/i-VRESSE/haddock3-analysis-components/pull/5
