### ISSUE TITLE
No rigidbody runs complete

### ISSUE THREAD

**Issue by EvanKomp** [haddocking/haddock3#676]
**Describe the bug**
_My use case_: I have a protein-DNA complex PDB structure. I am superimposing variants of this protein unto the original, and splitting the two structures into two PDBs. As I already have the approximate binding pose, I am most interested in the downstream modules of HADDOCK, but am starting from the beginning to get a grasp on it
_Issue_: Rigid body module. I am running part of the example in protein-DNA binding on my system:

```
# ====================================================================
# protein-DNA docking example

# directory in which the scoring will be done
run_dir = "run1-full"

# ###
mode = "local"
# in which queue the jobs should run, if nothing is defined
#  it will take the system's default
# queue = "short"
# concatenate models inside each job, concat = 5 each .job will produce 5 models
concat = 5
#  Limit the number of concurrent submissions to the queue
queue_limit = 100
# cns_exec = "path/to/bin/cns" # optional
# ###

# postprocess caprieval folders with haddock3-analyse
postprocess = true

# molecules to be docked
molecules =  [
    "./protein.pdb",
    "./dna.pdb"
    ]

# ====================================================================
# Parameters for each stage are defined below, prefer full paths
# ====================================================================
[topoaa]
autohis = true

[rigidbody]
# ambig_fname = "./data/cro_air.tbl"
sampling = 1000
epsilon = 78
dielec = "cdie"
randremoval = false
ranair = true
```

I have commented out the AIRS file and turned on ranair. I understand AIRS at a high level but am unsure how to compute them for my system, so have commented it out in hopes of triggering the 'ab initio' mode, which if I am reading the docs correctly, tries many random surface airs ones out.

The error it produces on stdout is the outer error:
```
RuntimeError: 100.00% of output was not generated for this module and tolerance was set to 0.00%.
[2023-08-09 09:29:37,868 libutil ERROR] 100.00% of output was not generated for this module and tolerance was set to 0.00%.
[2023-08-09 09:29:37,868 libutil ERROR] An error has occurred, see log file. And contact the developers if needed.
[2023-08-09 09:29:37,868 libutil INFO] Finished at 09/08/2023 09:29:37. For any help contact us at https://github.com/haddocking/haddock3/issues. Adéu-siau! Au revoir! Agur!.
```

Looking at #565 I have done the following:
- Checked CNS install, at the very least it is running smoothly at the command line. I get no errors for to topoaa module so I believe it is running fine.
- Checked one of the bad output files:

```
... Continues upward for a while
 %NEXTCD-ERR: Symbol not found:
             if ($mol_fix_origin_$maxid 
                 ^^^^^^^^^^^^^^^^^^^^^^
 %NEXTCD-ERR: Symbol not found:
             if ($mol_fix_origin_$maxid 
                 ^^^^^^^^^^^^^^^^^^^^^^
 %NEXTCD-ERR: Symbol not found:
             if ($mol_fix_origin_$maxid 
                 ^^^^^^^^^^^^^^^^^^^^^^
 %NEXTCD-ERR: Symbol not found:
             if ($mol_fix_origin_$maxid 
                 ^^^^^^^^^^^^^^^^^^^^^^
 %PARSER error encountered: Encountered too many parsing errors.
   (CNS is in mode: SET ABORT=NORMal END)
 *****************************************************
 ABORT mode will terminate program execution. 
 *****************************************************
 Program will stop immediately.
          ============================================================
           Maximum dynamic memory allocation:  2889948472 bytes
           Maximum dynamic memory overhead:          1392 bytes
           Program started at: 09:29:15 on 09-Aug-2023
           Program stopped at: 09:29:15 on 09-Aug-2023
           CPU time used:       0.1220 seconds
          ============================================================
```

**To Reproduce**
Steps to reproduce the behavior, if relevant, provide the input that triggered the error:
1. Run the above workflow. I can provide my PDBs if desired

Thanks for any insight and thanks for the work.

**Comment by amjjbonvin** [comment]
A few things:

1. If you are interested in the downstream modules, e.g. to refine the interface, simply discard the rigidbody module. But I would then turn set `contactairs = true` for the flexref module. And also define for it `dnarest_on = true`
2. We do need your input PDB and the cfg file in order to figure out what is wrong (you can also share those via haddock.support@gmail.com
3. Commenting out the air file will not trigger automatically the ab-initio mode. For that you would need to define the random air mode by adding to the rigid body module:
```
# turn on random definiton of AIRs
ranair = true
```

4. Make sure to have the latest version of haddock3 as the code is still evolving (and still in beta release)

**Comment by amjjbonvin** [comment]
PS: Sorry I do realise now you turned on ranair in the rigidbody module. 
PPS: When sharing the PDB/cfg files, please also include the output file where you extracted the error messages

**Comment by EvanKomp** [comment]
Thanks! Sent some files. What is the recommended usage of the refinement modules if I were to skip rigidbody given that I have an approximate protein-DNA complex structure already. I went into h2.4 documentation a bit but was having a hard time figuring out how to define AIRS for this use case.

**Comment by amjjbonvin** [comment]
No issues running your system on my side... Make sure to have the latest version of haddock3 installed.
I emailed you the results of a limited sampling run. Here is the config file I used in this case:

```
# ====================================================================
# protein-DNA docking example

# directory in which the scoring will be done
run_dir = "run1-full"

# ###
mode = "local"

# postprocess caprieval folders with haddock3-analyse
postprocess = true

# molecules to be docked
molecules =  [
    "./protein.pdb",
    "./dna.pdb"
    ]

# ====================================================================
# Parameters for each stage are defined below, prefer full paths
# ====================================================================
[topoaa]
autohis = true

[rigidbody]
randorien = false
sampling = 100
epsilon = 78
dielec = "cdie"
surfrest = true

[seletop]
select = 20

[flexref]
epsilon = 78
dielec = "cdie"
dnarest_on = true
contactairs = true

[emref]
dnarest_on = true
dielec = "cdie"


# ====================================================================
```

You can probably remove the rigidbody stage. In that case the workflow would look like:

```
...

# ====================================================================
# Parameters for each stage are defined below, prefer full paths
# ====================================================================
[topoaa]
autohis = true

[flexref]
sampling_factor = 20
epsilon = 78
dielec = "cdie"
dnarest_on = true
contactairs = true

[emref]
dnarest_on = true
dielec = "cdie"

# ====================================================================
```
