### ISSUE TITLE
Add version number in the log file

### ISSUE THREAD

**Issue by amjjbonvin** [haddocking/haddock3#679]
It would be good to print out in the log file at the start the version number of the used haddock3 installation
Will help in supporting users.

**Comment by VGPReys** [comment]
As we are doing continuous integration with (+-) daily merges, should we somehow add the full last merge git SHA (or just the first 6 characters) next to the version ?
Because for now, the 3.0.0 is kind of hard coded, and never automatically updated.

**Comment by mgiulini** [comment]
that would be nice..even better would be to have the commit ID..but I honestly don't know whether it's doable

**Comment by sverhoeven** [comment]
Could use https://pypi.org/project/setuptools-scm/ to determine the version from git (tags).

**Comment by VGPReys** [comment]
Indeed !
an other branch [autamatic-patch-update2](https://github.com/haddocking/haddock3/tree/autamatic-patch-update2) is using this `setuptools-scm` approach.
But it generate natsy patch identifiers !

**Comment by VGPReys** [comment]
Closing this issue as stable versions are coming soon, and we will point to specific tags!
