### ISSUE TITLE
[2023-08-22 17:53:52,205 defaults ERROR] CNS executable `bin/cns` not found. Please check the install instructions.

### ISSUE THREAD

**Issue by liusfore** [haddocking/haddock3#680]
I have been used "mkdir -p bin/" and "ln -s cns_solve_1.3/intel-x86_64bit-linux/source/cns_solve-2308221630.exe bin/cns" to make a CNS binary shortcut. But the error report is also given when using haddock3.

**Comment by amjjbonvin** [comment]
When creating the link define the full path to the CNS executable

**Comment by liusfore** [comment]
Starting HADDOCK 3.0.0 on 2023-08-24 11:47:00

Python 3.9.17 | packaged by conda-forge | (main, Aug 10 2023, 07:02:31) 
[GCC 12.3.0]

[2023-08-24 11:47:25,403 libutil ERROR] No module named 'fcc.scripts'
Traceback (most recent call last):
  File "/mnt/e/code/docking/haddock3/src/haddock/libs/libutil.py", line 310, in log_error_and_exit
    yield
  File "/mnt/e/code/docking/haddock3/src/haddock/clis/cli.py", line 135, in main
    params, other_params = setup_run(
  File "/mnt/e/code/docking/haddock3/src/haddock/gear/prepare_run.py", line 208, in setup_run
    check_if_modules_are_installed(modules_params)
  File "/mnt/e/code/docking/haddock3/src/haddock/gear/prepare_run.py", line 417, in check_if_modules_are_installed
    module_lib = importlib.import_module(module_import_name)
  File "/mnt/data/anaconda/envs/haddock/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/mnt/e/code/docking/haddock3/src/haddock/modules/analysis/clustfcc/__init__.py", line 6, in <module>
    from fcc.scripts import calc_fcc_matrix, cluster_fcc
ModuleNotFoundError: No module named 'fcc.scripts'
[2023-08-24 11:47:25,404 libutil ERROR] No module named 'fcc.scripts'
[2023-08-24 11:47:25,404 libutil ERROR] An error has occurred, see log file. And contact the developers if needed.

**How to deal with this problem?
when I make install for cns_solve_1.3, there is warning and error as** 

dell@dell-Precision-7920-Tower:/mnt/e/code/docking/cns_solve_1.3$ make install
Installation directory: /mnt/e/code/docking/cns_solve_1.3/intel-x86_64bit-linux
copying files in instlib directory intel-x86_64bit-linux to intel-x86_64bit-linux
0read.me
arch_env
machine_c.c
machine_f.f
Makefile.header.1.ifort
Makefile.header.2.gfortran
Makefile.header.3.ifort_mp
Makefile.header.4.pgf95
Makefile.header.5.ifort_mp_profile
Makefile.header.6.ifort_mp_tcheck
Makefile.header.7.gfortran_mp
Using Makefile template for compiler: gfortran
making test directory in intel-x86_64bit-linux
linking source files to intel-x86_64bit-linux/source
linking machine_f.f to source directory
linking machine_c.c to source directory
linking generic fft file to source directory
making Makefile in source directory
making compiler-test directory in intel-x86_64bit-linux
testing Fortran and C compilers
compiling: gcc -O -DINTEGER='long int' -DCNS_ARCH_TYPE_LINUX 
C compiler passes test
compiling: gfortran -fdefault-integer-8 -w -O3  -funroll-loops -ffast-math  
linking: gfortran -w 
Fortran compiler passes test
making utility programs
make relink
make default
gfortran -o PSmapx -w -O PSmapx.f 
gfortran -o PSmapy -w -O PSmapy.f 
gfortran -o PSmapz -w -O PSmapz.f 
gcc -o to_cns -O to_cns.c -lm
to_cns.c:65:1: warning: return type defaults to ‘int’ [-Wimplicit-int]
   65 | main(int argc, char *argv[]) {
      | ^~~~
to_cns.c: In function ‘read_header’:
to_cns.c:231:5: warning: ignoring return value of ‘fscanf’, declared with attribute warn_unused_result [-Wunused-result]
  231 |     fscanf(stream,"%d",&nindex);
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~
to_cns.c:232:5: warning: ignoring return value of ‘fscanf’, declared with attribute warn_unused_result [-Wunused-result]
  232 |     fscanf(stream,"%d",&ndata);
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~
to_cns.c:233:5: warning: ignoring return value of ‘fgets’, declared with attribute warn_unused_result [-Wunused-result]
  233 |     fgets(line,MAXLINE,stream);
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~
to_cns.c:234:5: warning: ignoring return value of ‘fgets’, declared with attribute warn_unused_result [-Wunused-result]
  234 |     fgets(line,MAXLINE,stream);
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~
to_cns.c:242:5: warning: ignoring return value of ‘fscanf’, declared with attribute warn_unused_result [-Wunused-result]
  242 |     fscanf(stream,"%d %d %d %d\n",&nindex,&ndata,&nextra,&ninfo);
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
to_cns.c:249:7: warning: ignoring return value of ‘fgets’, declared with attribute warn_unused_result [-Wunused-result]
  249 |       fgets(info,MAXLINE,stream);
      |       ^~~~~~~~~~~~~~~~~~~~~~~~~~
to_cns.c:252:7: warning: ignoring return value of ‘fscanf’, declared with attribute warn_unused_result [-Wunused-result]
  252 |       fscanf(stream,"%s",index);
      |       ^~~~~~~~~~~~~~~~~~~~~~~~~
to_cns.c:256:7: warning: ignoring return value of ‘fscanf’, declared with attribute warn_unused_result [-Wunused-result]
  256 |       fscanf(stream,"%s",data);
      |       ^~~~~~~~~~~~~~~~~~~~~~~~
to_cns.c:265:7: warning: ignoring return value of ‘fscanf’, declared with attribute warn_unused_result [-Wunused-result]
  265 |       fscanf(stream,"%s",extra);
      |       ^~~~~~~~~~~~~~~~~~~~~~~~~
to_cns.c: In function ‘read_reflections’:
to_cns.c:282:9: warning: ignoring return value of ‘fscanf’, declared with attribute warn_unused_result [-Wunused-result]
  282 |  if ( ! fscanf(stream,"%d %d %d %lf %lf %lf %lf %lf %lf",
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  283 |         &h, &k, &l,
      |         ~~~~~~~~~~~
  284 |         &mean_i, &mean_s,
      |         ~~~~~~~~~~~~~~~~~
  285 |         &plus_i, &plus_s,
      |         ~~~~~~~~~~~~~~~~~
  286 |         &minus_i, &minus_s) == 9 ) {
      |         ~~~~~~~~~~~~~~~~~~~
to_cns.c:335:9: warning: ignoring return value of ‘fscanf’, declared with attribute warn_unused_result [-Wunused-result]
  335 |  if ( ! fscanf(stream,"%d %d %d %lf %lf",
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  336 |         &h, &k, &l,
      |         ~~~~~~~~~~~
  337 |         &mean_i, &mean_s) == 5 ) {
      |         ~~~~~~~~~~~~~~~~~
to_cns.c: In function ‘get_hkl_refs’:
to_cns.c:431:3: warning: ignoring return value of ‘fgets’, declared with attribute warn_unused_result [-Wunused-result]
  431 |   fgets(line,MAXLINE,stream);
      |   ^~~~~~~~~~~~~~~~~~~~~~~~~~
g++ -o cluster_struc -O cluster_struc.cpp -lm
cluster_struc.cpp: In function ‘int main(int, char**)’:
cluster_struc.cpp:122:10: warning: ignoring return value of ‘char* fgets(char*, int, FILE*)’, declared with attribute warn_unused_result [-Wunused-result]
  122 |     fgets(buf, 1000, f);
      |     ~~~~~^~~~~~~~~~~~~~
lex refloat.l
make[4]：lex：command not found
make[4]: *** [Makefile:34：refloat] error 127
make[3]: *** [Makefile:21：utils] error 2
make[2]: *** [Makefile.header:26：compile-utils] error 2
make[1]: *** [Makefile:60：utils] error 2

**Comment by liusfore** [comment]
I found that the problem is solved by cloning https://github.com/haddocking/fcc.git

**Comment by Rohit-Satyam** [comment]
For those who forgot recursive option like me

```
git submodule update --init --recursive
```
