### ISSUE TITLE
Haddock3 'rigidbody' module ZeroDivisionError during MPI test

### ISSUE THREAD

**Issue by pokeface1812** [haddocking/haddock3#698]
1. When executing “haddock3 docking-antibody-antigen-CDR-accessible-clt-full-mpi.cfg”。
2. Error found with the following details：
------------------------------------------------------------------------------------------------
 [2023-09-20 23:02:31,491 libworkflow INFO] Reading instructions step 5_caprieval
[2023-09-20 23:02:31,491 libworkflow INFO] Reading instructions step 6_flexref
[2023-09-20 23:02:31,492 libworkflow INFO] Reading instructions step 7_caprieval
[2023-09-20 23:02:31,492 libworkflow INFO] Reading instructions step 8_emref
[2023-09-20 23:02:31,492 libworkflow INFO] Reading instructions step 9_caprieval
[2023-09-20 23:02:31,492 libworkflow INFO] Reading instructions step 10_clustfcc
[2023-09-20 23:02:31,492 libworkflow INFO] Reading instructions step 11_seletopclusts
[2023-09-20 23:02:31,493 libworkflow INFO] Reading instructions step 12_caprieval
[2023-09-20 23:02:32,289 base_cns_module INFO] Running [rigidbody] module
[2023-09-20 23:02:32,290 __init__ INFO] [rigidbody] crossdock=true
[2023-09-20 23:02:32,290 libutil ERROR] division by zero
Traceback (most recent call last):
  File "/root/tools/haddock3/haddock3-main/src/haddock/libs/libutil.py", line 310, in log_error_and_exit
    yield
  File "/root/tools/haddock3/haddock3-main/src/haddock/clis/cli.py", line 178, in main
    workflow.run()
  File "/root/tools/haddock3/haddock3-main/src/haddock/libs/libworkflow.py", line 39, in run
    step.execute()
  File "/root/tools/haddock3/haddock3-main/src/haddock/libs/libworkflow.py", line 143, in execute
    self.module.run()
  File "/root/tools/haddock3/haddock3-main/src/haddock/modules/base_cns_module.py", line 59, in run
    self._run()
  File "/root/tools/haddock3/haddock3-main/src/haddock/modules/sampling/rigidbody/__init__.py", line 76, in _run
    sampling_factor = int(self.params["sampling"] / len(models_to_dock))
ZeroDivisionError: division by zero
[2023-09-20 23:02:32,291 libutil ERROR] division by zero
--------------------------------------------------------------------------------------
But everything works fine when I haddock3 docking-antibody-antigen-CDR-accessible-clt-test. cfg。

The following is the specific content of my docking-antibody-antigen-CDR-accessible-clt-full-mpi.cfg file, which is completely the original content in the example, and the PDB file also comes from the data folder in the example and has not changed.：
--------------------------------------------------------------------------------------
# directory in which the scoring will be done
run_dir = "run1-CDR-acc-cltsel-full"

# compute mode
mode = "mpi"
#  5 nodes x 50 tasks = ncores = 250
ncores = 1

# postprocess caprieval folders with haddock3-analyse
postprocess = true

# molecules to be docked
molecules =  [
    "data/4G6K_fv.pdb",
    "data/4I1B-matched.pdb"
    ]

# ====================================================================
# Parameters for each stage are defined below, prefer full paths
# ====================================================================
[topoaa]

[rigidbody]
# CDR to surface ambig restraints
ambig_fname = "data/ambig.tbl"
# Restraints to keep the antibody chains together
unambig_fname = "data/unambig.tbl"
# turn on random definiton of AIRs
ranair = true
# for antibody sample only CDR loops
nrair_1 = 6
rair_sta_1_1 = 26
rair_end_1_1 = 32
rair_sta_1_2 = 55
rair_end_1_2 = 57
rair_sta_1_3 = 101
rair_end_1_3 = 108
rair_sta_1_4 = 146
rair_end_1_4 = 152
rair_sta_1_5 = 170
rair_end_1_5 = 172
rair_sta_1_6 = 212
rair_end_1_6 = 215

sampling = 10000

[caprieval]
reference_fname = "data/4G6M-matched.pdb"

[clustfcc]
threshold = 4

[seletopclusts]
## select the best 4 models of each cluster
top_models = 20
##select all the models
#top_models = NaN

#[seletop]
#select = 500

[caprieval]
reference_fname = "data/4G6M-matched.pdb"

[flexref]
tolerance = 5
# CDR to surface ambig restraints
ambig_fname = "data/ambig.tbl"
# Restraints to keep the antibody chains together
unambig_fname = "data/unambig.tbl"
------------------------------------------------------------------------------------------------
I also suspect it's a PDB problem, but I also tried to use other pdb files and failed, same mistake,My cns execution is normal, and the FCC is considered when compiling,
---------------------------------------------------------------------------------------------------------
(base) root@6thed4fbo8p0k-0:~/tools/haddock3/haddock3-main/bin# ./cns
          ============================================================
          |                                                          |
          |            Crystallography & NMR System (CNS)            |
          |                         CNSsolve                         |
          |                                                          |
          ============================================================
           Version: 1.3 at patch level U
           Status: Special UU release with Rg, paramagnetic
                   and Z-restraints (A. Bonvin, UU 2013)
          ============================================================
           Written by: A.T.Brunger, P.D.Adams, G.M.Clore, W.L.DeLano,
                       P.Gros, R.W.Grosse-Kunstleve,J.-S.Jiang,J.M.Krahn,
                       J.Kuszewski, M.Nilges, N.S.Pannu, R.J.Read,
                       L.M.Rice, G.F.Schroeder, T.Simonson, G.L.Warren.
           Copyright (c) 1997-2010 Yale University
          ============================================================
           Running on machine: hostname unknown (x86_64/Linux,64-bit)
           Program started by: unknown
           Program started at: 23:22:10 on 20-Sep-2023
          ============================================================

 FFT3C: Using FFTPACK4.1

CNSsolve>
-----------------------------------------------------------------------------
My 00_topoaa folder is: 4G6K_fv.inp 4I1B-matched.inp mpi.pkl params.cfg, these are not empty folders@amjjbonvin

**Comment by amjjbonvin** [comment]
Are you actually using MPI to run it?

setting ncores=1 for running in MPI mode does not make much sense.

**Comment by pokeface1812** [comment]
I have a lot of different nodes, I tested on a specific node that has only one CPU, and before that I also tried to calculate on another node with 50 CPUs, setting ncores= 50, but the same error was reported.

**Comment by amjjbonvin** [comment]
Try running on one node in local mode with 50 cores.

If this works, most likely there is an MPI issue. Do you have the python MPI library?

How do you submit your runs for MPI execution?

Check for an example:  https://www.bonvinlab.org/education/HADDOCK3/HADDOCK3-antibody-antigen/#3-mpi-mode <https://www.bonvinlab.org/education/HADDOCK3/HADDOCK3-antibody-antigen/#3-mpi-mode>

**Comment by mgiulini** [comment]
hi there, when running in MPI mode the HADDOCK3 job should be submitted to the batch system requesting the corresponding number of nodes and cores per node. An example job file for your task is `docking-antibody-antigen-CDR-accessible-full-mpi.job`, available in the same directory where you found `docking-antibody-antigen-CDR-accessible-clt-full-mpi.cfg`

A short MPI tutorial can be found [here](https://github.com/haddocking/haddock3/blob/main/docs/tutorials/mpi.md)

**Comment by pokeface1812** [comment]
Thank you for your kindness and the solution provided, this problem has been solved due to some problems with the deployment of mpi4y, thank you again!
