### ISSUE TITLE
Structures in analysis report not showing after clean

### ISSUE THREAD

**Issue by sverhoeven** [haddocking/haddock3#713]
**Describe the bug**
Structures in analyis report are not showing.

**To Reproduce**

1. Run the examples/docking-protein-protein/docking-protein-protein-full.cfg the recipe with 358f39f0bab3d1e75eadb35165b8c914fb95292e checked out. 
2. Start web server on `examples/docking-protein-protein/run1-full` folder.
3. Open the `examples/docking-protein-protein/run1-full/analysis/11_caprieval_analysis/report.html` in a web browser.
4. Click download or view links of best structure

**Expected behavior**

I expected when I downloaded of viewrf astructure it would appear. However I got 404 not found errors.

**Screenshots**
![_home_verhoes_git_vre4imbc_haddock3_examples_docking-protein-protein_run1-full_analysis_11_caprieval_analysis_report html](https://github.com/haddocking/haddock3/assets/1713488/28bcea44-0f3c-4852-b2ba-4a9b3f92e1c4)

**Configuration (optional - remove if not relevant)**

**Additional context (optional - remove if not relevant)**
The `examples/docking-protein-protein/run1-full/11_caprieval/capri_ss.tsv` contains link to `../10_seletopclusts/cluster_1_model_1.pdb`, but only examples/docking-protein-protein/run1-full/10_seletopclusts/cluster_1_model_1.pdb.gz exists.

**Comment by sverhoeven** [comment]
The problem always happened after cleaning, but with #706 implemented the problem now happens a lot more as  cleaning is now done by default.

At https://github.com/haddocking/haddock3/blob/358f39f0bab3d1e75eadb35165b8c914fb95292e/src/haddock/clis/cli.py#L179-L181 the clean is done after postprocess (command that generates report.html). So postprocess step does not know whether clean step will be done.

**Comment by mgiulini** [comment]
hi there, PR #706 indeed sets clean to true by default, with the aim to reduce the disk usage of haddock3. Three options to visualize structures:

- simply set `clean` to false at the beginning of the workflow
- we modify the `clean` option so that it does not compress PDB files

@amjjbonvin what do you say?

**Comment by sverhoeven** [comment]
I think cleaning is a good idea and compressed pdb file also work with the viewer.

In the webapp I added check whether pdb files are gzipped (https://github.com/i-VRESSE/haddock3-webapp/commit/4cb98c542b421ca652dc36168052297ec9ea8dcf) 

I could add a similar check in report.html

**Comment by mgiulini** [comment]
OK then, I misundestood the problem..it is not that the viewer cannot show compressed files, but rather a name issue in the tables! In that case yes, a simple check on the file name would be my favourite solution.

**Comment by amjjbonvin** [comment]
Would the viewer be able to load gzipped PDF files? PyMol can for example.


Currently also the download button does not work since it links to the pdb file and can not handle the pdb.gz files
