### ISSUE TITLE
RuntimeError: 100.00% of output was not generated for this module and tolerance was set to 0.00%.

### ISSUE THREAD

**Issue by yingioi0** [haddocking/haddock3#760]
Hi! I run command 'haddock3 --log-level DEBUG docking-protein-protein-test.cfg' in haddock3-main/examples/docking-protein-protein folder. But the error occurs. I have already checked CNS software  I can't  locate the problem. Anyone help me?
Thanks in advance and the log file attached here.
[log.txt](https://github.com/haddocking/haddock3/files/13670510/log.txt)

**Comment by amjjbonvin** [comment]
What is the content of the 00_topoaa directory?

Are there out files in there? Check those files for error messages starting at the bottom of the file.

My guess is that you have a CNS issue… Is cns present in the bin directory of your haddock3 installation?

**Comment by yingioi0** [comment]
Very thanks!
The log files are in .gz format and I attach one of them here. Indeed, the problem is made by CNS. 
I have downloaded the binary version of CNS_1.3, type 'csh' to enter csh terminal then source cns_solve_1.3/cns_solve_env and link cns_solve_1.3/intel-x86_64bit-linux/bin/cns to haddock3-main/bin/cns.  By the way I run some of .inp file in cns_solve_1.3/test  to check CNS and there is no error occur. Why CNS can't find it's top lib?
[hpr_ensemble_9.out.txt](https://github.com/haddocking/haddock3/files/13671310/hpr_ensemble_9.out.txt)

**Comment by amjjbonvin** [comment]
You need to recompile CNS for use in HADDOCK, providing the additional/modified CNS code provided in the `extras/cns1.3` directory

Or contact us via email and we can provided a compiled executable (let us know your architecture for that)
