### ISSUE TITLE
dnarest_on = false?

### ISSUE THREAD

**Issue by stianale** [haddocking/haddock3#779]
Hi,

I have a protein that interacts with a specific dsDNA motif, but have good reasons to suspect that the DNA "melts" (at least partial dissociation between the DNA strands) in order for buried residues to intercalate in minor grooves, etc. Does it make sense to use HADDOCK in this case, possibly using dnarest_on = false?

I don't know whether the DNA strand dissociation is something that happens almost immediately when the protein encounters the DNA or downstream in the interaction.

**Comment by amjjbonvin** [comment]
You might turn it off, but if the very short refinement stage I won’t expect much to happen with your DNA.

**Comment by stianale** [comment]
Yes, I was thinking to refine a protein-DNA complex, since the max time step for mdref is 100000, to let the output of run 1 be the input of run 2, and the output from run 2 the input for the next, etc. Maybe GROMACS is better for this, I don't know, but I like the logic of mdref in haddock3 and how it is so easily set up.

**Comment by amjjbonvin** [comment]
It is not a very efficient process… You are also refining the complex without any counter ions… A proper MD software would be much better for this.

The HADDOCK3 refinement is meant for short optimisation only
