### ISSUE TITLE
DNA-Protein rigid docking failed

### ISSUE THREAD

**Issue by AlexRizk12** [haddocking/haddock3#795]
Hello, 
I am trying to do rigid docking as per the example provided. The examples works fine but when i provide different pdbs 100 percent of the output is not generated. Here is the log file attached.
[log.txt](https://github.com/haddocking/haddock3/files/14127872/log.txt)

**Comment by mgiulini** [comment]
hi! that typically means that there is something wrong with the input pdb files (e.g clashes, same chain ID, etc.). can you share them together with the other files you used (configuration and restraint files)?

**Comment by AlexRizk12** [comment]
Checked the pdb files, all seems good. The issue must be from the tbl file (i changed the extension to txt in order to be able to upload it ).
[docking.txt](https://github.com/haddocking/haddock3/files/14137806/docking.txt)

**Comment by amjjbonvin** [comment]
You should check which step is failing.

It is the flexible refinement? Look into the corresponding directory of your run, and check the content of one of the *.out.gz file.
Start at the bottom of the file as this is where the error will typically be found.

Also make sure to update your haddock3 version as the code is still evolving fast (only beta releases so far)

**Comment by AlexRizk12** [comment]
Its in the rigid docking step that i encounter this error:

%NEXTCD-ERR: Symbol not found:
         if ($mol_fix_origin_$ncount 
             ^^^^^^^^^^^^^^^^^^^^^^^
SPACING SET TO 120.537 ANGSTROM
 %NEXTCD-ERR: Symbol not found:
     if ($mol_shape_$ncount 
         ^^^^^^^^^^^^^^^^^^
 %PARSER error encountered: Encountered too many parsing errors.
   (CNS is in mode: SET ABORT=NORMal END)
 *****************************************************
 ABORT mode will terminate program execution. 
 *****************************************************
 Program will stop immediately.

**Comment by AlexRizk12** [comment]
Will do ! Thank you so much for the help !
