### ISSUE TITLE
Difficulties in running a docking experiment

### ISSUE THREAD

**Issue by Cucco23** [haddocking/haddock3#796]
Dear all,

I have correctly installed the Haddock3 software and the software is running since the tests work.

I would like to test a simple protein-protein docking experiment.  However, I find very difficult to understand all the variable that are required to run a docking experiment. 
Is there a clearly annotated file that explain the cfg file?
For example: which are the key essential parameters to do a simple initial test?
How can I find the correct synaxis to add the parameters?

I hope you can share with me some simple example to get going. 

Thank you for the terrific work!

**Comment by Cucco23** [comment]
Working on the scripts I can now start the job and get a result. However I find very difficult understanding the following script:
[topoaa]
autohis = false
[topoaa.mol1]
nhisd = 0
nhise = 1
hise_1 = 75
[topoaa.mol2]
nhisd = 1
hisd_1 = 76
nhise = 1
hise_1 = 15

[rigidbody]
tolerance = 20
#ambig_fname = "data/e2a-hpr_air.tbl"
sampling = 20

I do not have the ambig file. How can I obtain it? Where can I find all these information?


Thanks

**Comment by amjjbonvin** [comment]
Do realise that HADDOCK3 is still in beta version

We do have a tutorial online for it at:

https://www.bonvinlab.org/education/HADDOCK3/HADDOCK3-antibody-antigen-bioexcel2023/￼
Low-sampling antibody-antigen modelling tutorial using a local version of HADDOCK3
bonvinlab.org

with the haddock3-cfg command you can get some description of the parameters for each module.
We don’t have a full blow manual yet. But if you have never worked with HADDOCK before you might want to check the HADDOCK2.4 manual at https://www.bonvinlab.org/software/haddock2.4/manual/

Some parameter names are the same

**Comment by amjjbonvin** [comment]
And also check https://www.bonvinlab.org/haddock3/

It is more geared toward developers at this time. But you should still find useful info.

E.g. a description of the workflow examples:

	https://www.bonvinlab.org/haddock3/examples.html#

**Comment by Cucco23** [comment]
Thank you for the prompt answer!
