### ISSUE TITLE
Add interface-specific scores 

### ISSUE THREAD

**Issue by amjjbonvin** [haddocking/haddock3#800]
**Is your feature request related to a problem? Please describe.**

In case of large assemblies it would be useful to be able to score the various interfaces separately. Currently we only have an overall score which might be occluding good and bad interfaces.

**Describe the solution you'd like**

Output the components of the score for each interface separately (either in the header of the PDB file or in a separate `.score` file (but this will increase the number of generated files on disk)

Possibly this should come with a new module to extra/rescore based on specified interfaces.

**Comment by VGPReys** [comment]
Closed by #896
