### ISSUE TITLE
gitlab sync action workflow fails for PR from forked repo

### ISSUE THREAD

**Issue by sverhoeven** [haddocking/haddock3#811]
**Describe the bug**
I have a (Pull Request)[https://github.com/haddocking/haddock3/pull/810] made from a forked repo which mails me about a failed workflow run, but then on PR page the failure is not visible.

**To Reproduce**
Steps to reproduce the behavior, if relevant, provide the input that triggered the error:
1. I created a PR https://github.com/haddocking/haddock3/pull/810 
2. I get a mail with failed worklow run https://github.com/i-VRESSE/haddock3/actions/runs/7972092429
3. In PR conversation I see a red check in the last commit, but once the other workflows have completed everything is green.

**Expected behavior**
For branches in  forked repo that the https://github.com/i-VRESSE/haddock3/blob/main/.github/workflows/github-to-gitlab-push-sync.yml workflow does not run.

**Comment by rvhonorato** [comment]
This is related to the action implemented by @amjjbonvin in https://github.com/haddocking/haddock3/pull/798 which was wrongly done.

It can be safely ignored in forked repos, but the action itself needs to be re-configured

**Comment by amjjbonvin** [comment]
I would not know how to re-configure it. 
It is working for the mirroring to the EU Castiel GitLab (was checked by the reviewers actually)

**Comment by sverhoeven** [comment]
Adding a condition similar to integration test would exclude syncing of branches in forked repos.
See https://github.com/haddocking/haddock3/blob/2550d550a61e3c7b4fe21499804c63f3875962d6/.github/workflows/tests.yml#L61

**Comment by rvhonorato** [comment]
> I would not know how to re-configure it. It is working for the mirroring to the EU Castiel GitLab (was checked by the reviewers actually)

It can be both wrong and working 😉

**Comment by rvhonorato** [comment]
Should be fixed now @sverhoeven 🤞🏽

**Comment by sverhoeven** [comment]
> Should be fixed now @sverhoeven 🤞🏽

Great, that is good for any external contributors.
