### ISSUE TITLE
Remove hard dependency on CNS

### ISSUE THREAD

**Issue by bkmgit** [haddocking/haddock3#82]
**Is your feature request related to a problem? Please describe.**
[CNS](http://cns-online.org/v1.3/) seems not to be under open active development and its license is not as permissive as the rest of Haddock3. 

**Describe the solution you'd like**
Make CNS an optional dependency and program essential engine functionality directly in Haddock3

**Describe alternatives you've considered**
Use another engine that is actively and openly developed and has a more permissive license.

**Comment by amjjbonvin** [comment]
There is no simply alternative to CNS I am afraid... (at least not at this time). Most of the docking happens at the CNS level which has an extremely powerful scripting and selection syntax. It would be a major coding undertaking for which man power is required.  The closest code would be Xplor-NIH, which falls under the same license as CNS. 

We might try to provide some alternatives, at least for some modules, but this will come at the cost of very limited functionality.

**Comment by antonkulaga** [comment]
Unfortunately, building CNS for haddock is a huge pain and there are no instructions on how to do it for haddock3.
My current understanding is that CNS is one of the major blockers for haddock adoptions as it gives so much pain when you switch from using your online server to running haddock locally.

**Comment by amjjbonvin** [comment]
You can follow the 2.4 instructions - it is the same CNS version.

As for adoption, we don’t seem to have too many problems with that :-)

Also note that haddock3 is in heavy development and changing rapidly.
Documentation is still missing, including info on how to compile CNS. 

You might want to check:

	https://github.com/haddocking/haddock3/issues/200
