### ISSUE TITLE
git cloning fails

### ISSUE THREAD

**Issue by pallavi-compchem** [haddocking/haddock3#829]
**Describe the bug**
A clear and concise description of what the bug is. If an error message appeared, please copy/paste it ENTIRELY.

**To Reproduce**
Steps to reproduce the behavior, if relevant, provide the input that triggered the error:
1. When executing '...'
2. Error found with the following details '...'

**Expected behavior**

**Screenshots**

**Configuration (optional - remove if not relevant)**

**Additional context (optional - remove if not relevant)**

**Comment by pallavi-compchem** [comment]
"git clone --recursive https://github.com/haddocking/haddock3.git" fails with the following error:

error: RPC failed; result=18, HTTP code = 200iB | 147.00 KiB/s   
fatal: The remote end hung up unexpectedly
fatal: early EOF
fatal: index-pack failed

Could you please help fix the issue?

**Comment by mgiulini** [comment]
it sounds like a network issue! please have a look here https://stackoverflow.com/questions/17683295/git-bash-error-rpc-failed-result-18-htp-code-200b-1kib-s (you probably have to increase the cloning time or the size of the http chunks)

**Comment by pallavi-compchem** [comment]
Thanks! Increasing the http postbuffer size did the trick.

**Comment by mgiulini** [comment]
super, enjoy haddocking then!
