### ISSUE TITLE
libutil ERROR

### ISSUE THREAD

**Issue by pallavi-compchem** [haddocking/haddock3#832]
**Describe the bug**
A clear and concise description of what the bug is. If an error message appeared, please copy/paste it ENTIRELY.

**To Reproduce**
Steps to reproduce the behavior, if relevant, provide the input that triggered the error:
1. When executing '...'
2. Error found with the following details '...'

**Expected behavior**

**Screenshots**

**Configuration (optional - remove if not relevant)**

**Additional context (optional - remove if not relevant)**

**Comment by pallavi-compchem** [comment]
Hi, 

Upon running haddock3 on a sample config file in the examples/ folder, the following error shows up in the log file:
"libutil ERROR] 100.00% of output was not generated for this module and tolerance was set to 20.00%"

Could someone help resolve the issue?

**Comment by mgiulini** [comment]
hi, does this happen already at the `topoaa` step? there is probably something wrong with your CNS installation: please make sure you followed the installation instructions provided here https://github.com/haddocking/haddock3/blob/main/docs/INSTALL.md

**Comment by pallavi-compchem** [comment]
CNS seems to run fine though. The jobs in topoaa have successfully run. The error occurs during the "rigidbody" docking process. I'm using the "docking-protein-protein-test.cfg" file in the "examples" folder.

**Comment by amjjbonvin** [comment]
What is in your rigidbody directory?

Any .out files?

If present, check for error messages in those.

And what is the content of the topoaa directory? How are you sure the jobs successfully ended?

**Comment by pallavi-compchem** [comment]
The rigidbody directory contains inp, seed and out files numbered from 1 to 20. 

The topoaa directory contains psf, pdb and out files named with the prefix "hpr_*" and numbered from 1 to 10. There are psf, pdb and out files with prefix "e2aP_1F3G* . I see no error messages in the out files.

I do not see any error messages in the out files inside the rigidbody folder either, so maybe the issue is something else? 

The log file shows "Module [topoaa] finished" with no error messages until here. 

Please have a look at the attached snapshot showing the error. 

<img width="1269" alt="haddock_error" src="https://github.com/haddocking/haddock3/assets/98699451/0a497d62-9f7b-4a76-8fdc-540976de58af">

**Comment by pallavi-compchem** [comment]
Yes, there are no pdb files in the rigidbody folder. I am sharing one of the out files. Could you please have a look to see what went wrong? Thankss..

[rigidbody_1.txt](https://github.com/haddocking/haddock3/files/14720191/rigidbody_1.txt)

**Comment by amjjbonvin** [comment]
the file is incomplete. Are you running things locally? It this error reproducible?

**Comment by amjjbonvin** [comment]
Where did you get CNS from?

Are you running under Linux?

How many cores are you using?

Is this happening when using only one core (as a test)? May-be you have a memory issue…

**Comment by pallavi-compchem** [comment]
I downloaded CNS from the website: http://cns-online.org/v1.3/

Yes, I'm running under Linux.

The same error occurs when running the program on the headnode and also while running it on the cluster through slurm.

Upon running "haddock3 docking-protein-protein-test.cfg", I see the following messages in the log file:
"[2024-03-25 11:58:56,111 libutil INFO] Selected 11 cores to process 11 jobs, with 128 maximum available cores.
[2024-03-25 11:58:56,111 libparallel INFO] Using 11 cores
[2024-03-25 11:58:57,325 libparallel INFO] 11 tasks finished"

"[2024-03-25 11:58:58,305 __init__ INFO] [rigidbody] Running CNS Jobs n=20
[2024-03-25 11:58:58,305 libutil INFO] Selected 20 cores to process 20 jobs, with 128 maximum available cores.
[2024-03-25 11:58:58,305 libparallel INFO] Using 20 cores
"

It looks like the program takes up cores as required by default. I do not allocate a number of cores to it.

**Comment by amjjbonvin** [comment]
You need to recompile CNS as explained in the installation instructions.

https://www.bonvinlab.org/haddock3/CNS.html#5-Check-installation￼

**Comment by pallavi-compchem** [comment]
It works now, after recompiling CNS! Thanks for the advice :)
