### ISSUE TITLE
Documentation for nested parameters has incorrect expertise level

### ISSUE THREAD

**Issue by sverhoeven** [haddocking/haddock3#835]
**Describe the bug**
On https://www.bonvinlab.org/haddock3/modules/topology/haddock.modules.topology.topoaa.html#mol1-hisd-1 the `mol1.hisd_1` parameter has explevel of expert while it is shown in the easy section.

**To Reproduce**
Steps to reproduce the behavior, if relevant, provide the input that triggered the error:
1. Goto https://www.bonvinlab.org/haddock3/modules/topology/haddock.modules.topology.topoaa.html#mol1-hisd-1

**Expected behavior**
I expected the `mol1.hisd_1` parameter to be shown in the expert section.

**Screenshots**

**Configuration (optional - remove if not relevant)**

**Additional context (optional - remove if not relevant)**
At https://github.com/haddocking/haddock3/blob/cb472a857625bc05f09f94e02291a9103e3f1b25/src/haddock/modules/topology/topoaa/defaults.yaml#L89 the `mol1` parameter has explevel easy. Which is I think is the reason the hisd_1 is rendered in the easy section.

**Comment by amjjbonvin** [comment]
It is the indented behaviour. 

Some subparameters of it have easy level (e.g. cyclicpept), while the others have expert level (e.g. hisd_1).

This might be happening if several modules for other parameters/subparameters combinations
