### ISSUE TITLE
 Unable to obtain cns_solve_1.3

### ISSUE THREAD

**Issue by xiaoxinbioinfo** [haddocking/haddock3#842]
**Describe the bug**
The software cns_solve can not obtain.

**To Reproduce**
The website [Crystallography and NMR System (CNS)](http://cns-online.org/v1.3/) can not access.

I am following the instructions on the [website](https://github.com/haddocking/haddock3/blob/main/docs/CNS.md) to install HADDOCK. However, I found that the core software cns Crystallography and NMR System (CNS) cannot be obtained. When I open the URL[Crystallography and NMR System (CNS)](http://cns-online.org/v1.3/) given in the documentation, I can find nothing. How can I solve this problem?

**Comment by amjjbonvin** [comment]
No issues accessing the site from our side... 
Note that it is http and not https.
Your browser's settings might prevent accessing it.
