### ISSUE TITLE
failing caprieval in protein-ligang-shape workflow

### ISSUE THREAD

**Issue by mgiulini** [haddocking/haddock3#843]
**Describe the bug**
caprieval is failing in the protein-ligang-shape example workflow. The cause is probably PR #828 

**To Reproduce**
Steps to reproduce the behavior, if relevant, provide the input that triggered the error:
1. When executing `haddock3 docking-protein-ligand-shape-test.cfg`
2. Error found with the following details 
```
haddock3/src/haddock/libs/libalign.py", line 465, in load_coords
    chain = model2ref_chain_dict[chain]
KeyError: 'S'
```

**Expected behavior**
Nothing wrong about chain S. Caprieval should work

**Comment by VGPReys** [comment]
Nice discovery !
Fixing it asap
