### ISSUE TITLE
CNS compilation failed

### ISSUE THREAD

**Issue by rescuz** [haddocking/haddock3#844]
**Describe the bug**
My os system is rockylinux, and the version of cns installed is 3.0， I compiled the CNS according to https://www.bonvinlab.org/haddock3/CNS.html#troubleshooting， but I still get the error.

I download the cns_solve_1.3_all.tar.gz, then
 gunzip cns_solve_1.3_all.tar.gz
tar -xvf cns_solve_1.3_all.tar,
after that, I modified the cns_solve_env and .cns_solve_env_sh. 
However, when I run "make install", the error was found.

the error information is listed below:

error: Type mismatch in argument ‘fobavg’ at (1); passed INTEGER(8) to REAL(8)
xtarget.f:1437:72:

 1437 |      &              HEAP(FOBAVG),HEAP(FCAAVG),HEAP(NUMAVG))
      |                                                                        1
error: Type mismatch in argument ‘fobavg’ at (1); passed INTEGER(8) to REAL(8)
xtarget.f:1658:72:

 1658 |      &               HEAP(DERAVG),HEAP(DERIV))
      |                                                                        1
error: Type mismatch in argument ‘fobavg’ at (1); passed INTEGER(8) to REAL(8)
xtarget.f:2406:72:

 2406 |      &               HEAP(DERIV))
      |                                                                        1
error: Type mismatch in argument ‘deriv’ at (1); passed INTEGER(8) to REAL(8)

make[3]: *** [Makefile:64：xtarget.o] error 1
compiling: xutil.f
compiling: xyzparse.f

compiling: dmemory.c

compiling: machine_c.c
make[3]: Target '../bin/cns_solve' not remade because of errors.
make[2]: *** [Makefile:59：cns_solve] error 2
make[1]: *** [Makefile:80：cns_solve] error 2.

I would appreciate it if you could provide us with detailed steps to resolve the problem.
Thank again!

**Comment by amjjbonvin** [comment]
Which compiler are you using?

Did you copy the cns files provided with haddock3 to the cns source directory?
