### ISSUE TITLE
CNS install Error

### ISSUE THREAD

**Issue by abiotik** [haddocking/haddock3#860]
I got this error after "make install"
I have followed all the install steps described above in the instruction.
make install
Installation directory: /home/nikola/Desktop/tik/haddock3/cns_solve_1.3//intel-x86_64bit-linux
copying files in instlib directory intel-x86_64bit-linux to intel-x86_64bit-linux
0read.me
arch_env
machine_c.c
machine_f.f
Makefile.header.1.ifort
Makefile.header.2.gfortran
Makefile.header.3.ifort_mp
Makefile.header.4.pgf95
Makefile.header.5.ifort_mp_profile
Makefile.header.6.ifort_mp_tcheck
Makefile.header.7.gfortran_mp
Using Makefile template for compiler: gfortran
removing old source files
linking source files to intel-x86_64bit-linux/source
ln: failed to create symbolic link './cns_solve_env.sh': File exists
removing old object files
linking machine_f.f to source directory
linking machine_c.c to source directory
linking generic fft file to source directory
making Makefile in source directory
/bin/sh: 1: ../../bin/objects: Permission denied
/bin/sh: 12: ../../bin/depend: Permission denied
make[2]: *** [Makefile.proto:67: makefiles] Error 126
make[1]: *** [Makefile:131: makefiles] Error 2
testing Fortran and C compilers
compiling: gcc -O -DINTEGER='long int' -DCNS_ARCH_TYPE_LINUX
C compiler passes test
compiling: gfortran -fdefault-integer-8 -w -O3  -funroll-loops -ffast-math
linking: gfortran -w
Fortran compiler passes test
making utility programs
make relink
make default
gfortran -o PSmapx -w -O PSmapx.f
gfortran -o PSmapy -w -O PSmapy.f
gfortran -o PSmapz -w -O PSmapz.f
gcc -o to_cns -O to_cns.c -lm
to_cns.c:65:1: warning: return type defaults to ‘int’ [-Wimplicit-int]
   65 | main(int argc, char *argv[]) {
      | ^~~~
g++ -o cluster_struc -O cluster_struc.cpp -lm
lex refloat.l
gcc -O -o refloat lex.yy.c -lm -lfl
make clean

flags:
 fortran -> [gfortran] -fdefault-integer-8 -w -O3  -funroll-loops -ffast-math
       c -> [gcc] -O -DINTEGER='long int' -DCNS_ARCH_TYPE_LINUX
    link -> [gfortran] -w

compiling: dmemory.c

compiling: machine_c.c

linking: cns_solve

/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/12/../../../x86_64-linux-gnu/Scrt1.o: in function `_start':
(.text+0x17): undefined reference to `main'
collect2: error: ld returned 1 exit status
problems with new executable - old version retained
(base) nikola@rack2:~/Desktop/tik/haddock3/cns_solve_1.3$ ^C
(base) nikola@rack2:~/Desktop/tik/haddock3/cns_solve_1.3$ ^C
(base) nikola@rack2:~/Desktop/tik/haddock3/cns_solve_1.3$ make install compilet=gfortran
Installation directory: /home/nikola/Desktop/tik/haddock3/cns_solve_1.3//intel-x86_64bit-linux
copying files in instlib directory intel-x86_64bit-linux to intel-x86_64bit-linux
0read.me
arch_env
machine_c.c
machine_f.f
Makefile.header.1.ifort
Makefile.header.2.gfortran
Makefile.header.3.ifort_mp
Makefile.header.4.pgf95
Makefile.header.5.ifort_mp_profile
Makefile.header.6.ifort_mp_tcheck
Makefile.header.7.gfortran_mp
Using Makefile template for compiler: gfortran
removing old source files
linking source files to intel-x86_64bit-linux/source
ln: failed to create symbolic link './cns_solve_env.sh': File exists
removing old object files
linking machine_f.f to source directory
linking machine_c.c to source directory
linking generic fft file to source directory
making Makefile in source directory
/bin/sh: 1: ../../bin/objects: Permission denied
/bin/sh: 12: ../../bin/depend: Permission denied
make[2]: *** [Makefile.proto:67: makefiles] Error 126
make[1]: *** [Makefile:131: makefiles] Error 2
testing Fortran and C compilers
compiling: gcc -O -DINTEGER='long int' -DCNS_ARCH_TYPE_LINUX
C compiler passes test
compiling: gfortran -fdefault-integer-8 -w -O3  -funroll-loops -ffast-math
linking: gfortran -w
Fortran compiler passes test
making utility programs
make relink
make default
gfortran -o PSmapx -w -O PSmapx.f
gfortran -o PSmapy -w -O PSmapy.f
gfortran -o PSmapz -w -O PSmapz.f
gcc -o to_cns -O to_cns.c -lm
to_cns.c:65:1: warning: return type defaults to ‘int’ [-Wimplicit-int]
   65 | main(int argc, char *argv[]) {
      | ^~~~
g++ -o cluster_struc -O cluster_struc.cpp -lm
lex refloat.l
gcc -O -o refloat lex.yy.c -lm -lfl
make clean

flags:
 fortran -> [gfortran] -fdefault-integer-8 -w -O3  -funroll-loops -ffast-math
       c -> [gcc] -O -DINTEGER='long int' -DCNS_ARCH_TYPE_LINUX
    link -> [gfortran] -w

compiling: dmemory.c

compiling: machine_c.c

linking: cns_solve

/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/12/../../../x86_64-linux-gnu/Scrt1.o: in function `_start':
(.text+0x17): undefined reference to `main'
collect2: error: ld returned 1 exit status
problems with new executable - old version retained

**Comment by amjjbonvin** [comment]
Which instructions are you following exactly? And on which system are you installing it?

Check: https://www.bonvinlab.org/haddock3/CNS.html

And make sure to edit the Makefile to have the proper options as described in the link above

**Comment by abiotik** [comment]
I am using debial linux
I have modified the path variable on cns_solve_env file and changed it to .cns_colve_env_sh and got this error while doing make install
make install
CNS_SOLVE=/home/nikola/Desktop/tik/haddock3/cns_solve_1.3/: Command not found.
Installation directory: /home/nikola/Desktop/tik/haddock3/cns_solve_1.3//intel-x86_64bit-linux
copying files in instlib directory intel-x86_64bit-linux to intel-x86_64bit-linux
0read.me
arch_env
machine_c.c
machine_f.f
Makefile.header.1.ifort
Makefile.header.2.gfortran
Makefile.header.3.ifort_mp
Makefile.header.4.pgf95
Makefile.header.5.ifort_mp_profile
Makefile.header.6.ifort_mp_tcheck
Makefile.header.7.gfortran_mp
Using Makefile template for compiler: gfortran
removing old source files
linking source files to intel-x86_64bit-linux/source
ln: failed to create symbolic link './cns_solve_env.sh': File exists
removing old object files
linking machine_f.f to source directory
linking machine_c.c to source directory
linking generic fft file to source directory
making Makefile in source directory
/bin/sh: 1: ../../bin/objects: Permission denied
/bin/sh: 12: ../../bin/depend: Permission denied
make[2]: *** [Makefile.proto:67: makefiles] Error 126
make[1]: *** [Makefile:131: makefiles] Error 2
testing Fortran and C compilers
compiling: gcc -O -DINTEGER='long int' -DCNS_ARCH_TYPE_LINUX
C compiler passes test
compiling: gfortran -fdefault-integer-8 -w -O3  -funroll-loops -ffast-math
linking: gfortran -w
Fortran compiler passes test
making utility programs
make relink
make default
gfortran -o PSmapx -w -O PSmapx.f
gfortran -o PSmapy -w -O PSmapy.f
gfortran -o PSmapz -w -O PSmapz.f
gcc -o to_cns -O to_cns.c -lm
to_cns.c:65:1: warning: return type defaults to ‘int’ [-Wimplicit-int]
   65 | main(int argc, char *argv[]) {
      | ^~~~
g++ -o cluster_struc -O cluster_struc.cpp -lm
lex refloat.l
gcc -O -o refloat lex.yy.c -lm -lfl
make clean

flags:
 fortran -> [gfortran] -fdefault-integer-8 -w -O3  -funroll-loops -ffast-math
       c -> [gcc] -O -DINTEGER='long int' -DCNS_ARCH_TYPE_LINUX
    link -> [gfortran] -w


compiling: dmemory.c

compiling: machine_c.c

linking: cns_solve

/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/12/../../../x86_64-linux-gnu/Scrt1.o: in function `_start':
(.text+0x17): undefined reference to `main'
collect2: error: ld returned 1 exit status
problems with new executable - old version retained

**Comment by abiotik** [comment]
Maybe after seting path variable I should delete all the "setenv" as I am using bash?

**Comment by amjjbonvin** [comment]
What about the questions I asked: 

Which instructions are you following? 

Check: https://www.bonvinlab.org/haddock3/CNS.html

Did you edit the Makefile to have the proper options as described in the link above?

**Comment by abiotik** [comment]
@amjjbonvin  Here's what I did.
I have gained the license and downloaded cns_1.3.
I have copied the files from Haddock to /source of cns
I have modified the  .cns_solve_env_sh file's first line to the path that the cns is installed.
Then I run make install and got this error
make install compiler=gfortran
environmental variable $CNS_SOLVE has been defined incorrectly
this variable is set in cns_solve_env - modify this file
make: *** [Makefile:38: install] Error 1



I have created Makefile.header.6.gfortran file in instlib/machine/supported/linux/ with the according codes and still got the same error

**Comment by amjjbonvin** [comment]
Check that there is not another already present Makefile.header.2.gfortran file - if that is the case it will be used first instead of your newly created one

**Comment by abiotik** [comment]
There are indeed Makefile.header.2 and 5 present.
I have tried to install both with and without creating the new file, still the same error.
BTW thanks for quick response!

**Comment by amjjbonvin** [comment]
Delete the old files and only use your new version

Alternatively go into the intel…/source directory and check/edit the content of the makefile there and then type in the same directory “make cns_solve”

**Comment by abiotik** [comment]
the/cns_solve_1.3/intel-x86_64bit-linux/source/ is empty

**Comment by amjjbonvin** [comment]
What about deleting this intel.. dir and trying again?And otherwise try simply to use the following for non-profit use executable: SURFdrivesurfdrive.surf.nl
