### ISSUE TITLE
Chain matching error in `examples/scoring/emscoring-test.cfg`

### ISSUE THREAD

**Issue by VGPReys** [haddocking/haddock3#863]
**Describe the bug**
There is an un-handled python error raised while running `examples/scoring/emscoring-test.cfg`

**To Reproduce**
```bash
haddock3 examples/scoring/emscoring-test.cfg
```

**Comment by amjjbonvin** [comment]
There should not be a caprieval module in this example. Does not make sense since the scoring is applied to a mixture of complexes (protein-DNA, protein dimer, timer...).
