### ISSUE TITLE
creating tbl file 

### ISSUE THREAD

**Issue by pallavi-compchem** [haddocking/haddock3#873]
Hi there, 

I am unable to find an explanation of the tbl file for imposing interaction restraints. Could you please help understand the format of the tbl file and how to create such files?

Thanks.

Best,
Pallavi

**Comment by VGPReys** [comment]
Hi Pallavi,

Please refer to the [Nature Protocols](https://www.nature.com/articles/nprot.2010.32) and [Nature Protocols Correspondence](https://www.nature.com/articles/s41596-018-0017-6.epdf?author_access_token=PCOdao9At6UPBnGnXKot19RgN0jAjWel9jnR3ZoTv0OMpdiCTExLiiIVHnJ_GM9iTFHQzhmzv8TQRpN4UoHo_SftIscahWHWSW2Cs2suSVugc9yUnz0hK1botwaQ0W5FoANSwLHc7l2f0LB1mRH94g%3D%3D) paper where everything is well described.
Also, you can use our [GenTBL online tool](https://wenmr.science.uu.nl/gentbl/) to generate a restraints file based on residues ids.

Cheers

**Comment by pallavi-compchem** [comment]
Hi, 

Thanks for the links! I have now an understanding of the general syntax, but I still have one question. In the protein-DNA docking example, the cro_air.tbl shows:

assign ( resid 27  and segid A)
       (
        ( resid 32  and segid B and (name O2 or name O4 or name H3 or name C2 or name C4 or name C5 or name C6 or name C7))
     or
        ( resid 33  and segid B and (name O2 or name O4 or name H3 or name C2 or name C4 or name C5 or name C6 or name C7))
     or
        ( resid 34  and segid B and (name N3 or name N7 or name O6 or name H1 or name H22 or name H21 or name C2 or name C4 or name C5 or name C6 or name C8))
       )  2.0 2.0 0.0

Does this imply that center of mass of the residues connected by "or"  (residues 32, 33, 34) is used for the distance restraint?

**Comment by amjjbonvin** [comment]
No - it does not. The effective distance is calculated as:

  [Sum (1/r**6) ]**(-1/6)

over all pairwise distances between all atoms in the selections.

**Comment by VGPReys** [comment]
The first selection is called `active` residue, while the second selection is called `passive` residue.

Restraints penalties only apply on `active` residues.

Therefore having the reverse (in the "HADDOCK AIR restraints for 2nd partner"), allows to define previously described `passive` (from chain B) residues as `active`, and vice-versa.

**Comment by pallavi-compchem** [comment]
Got it! Thanks :)
