### ISSUE TITLE
Origin of models from ensemble

### ISSUE THREAD

**Issue by VGPReys** [haddocking/haddock3#877]
**Is your feature request related to a problem? Please describe.**
It is currently almost impossible (or require substantial scripting) to know the origin of a model when it came from an input ensemble.

**Describe the solution you'd like**
Being able to access this information faster !

**Comment by VGPReys** [comment]
It is doing it until the last module, but not upto the model id in an input ensemble.
For single structure input, it is fine.

**Comment by amjjbonvin** [comment]
Then indeed a nice feature request
