### ISSUE TITLE
raise allowed mdref sampling factor

### ISSUE THREAD

**Issue by mgiulini** [haddocking/haddock3#938]
since in some workflows we're mentioning sampling_factor = 400 at mdref, this should be effectively allowed within the code. Currently the max value of sampling_factor is 200.

**Comment by VGPReys** [comment]
Which workflow is using sampling factor 400 ?

**Comment by amjjbonvin** [comment]
We indeed have to be careful here.

Setting can always be changed locally.

For example, in a standard workflow with 200 models refined, allowing to set the sampling factor to 400 would allow for 80000 models to be generated!

**Comment by mgiulini** [comment]
hi there, a check is already in place here https://github.com/haddocking/haddock3/blob/46e14c5a408949946b7006112e8319957eff68cd/src/haddock/modules/refinement/mdref/__init__.py#L56-L58
that checks the product of sampling factor and number of models
in the case you mention @amjjbonvin the module will stop the execution

**Comment by mgiulini** [comment]
> Which workflow is using sampling factor 400 ?

some pre-docking MD sampling of small molecules and glycans :)
