### ISSUE TITLE
create tbl file

### ISSUE THREAD

**Issue by jh2ee** [haddocking/haddock3#948]
Hi, I'm trying to create a tbl file.

Before, I tried to create act-pass & pass files to make tbl file.

But I don't know how to correctly create act-pass and pass files.

In your [instruction](https://www.bonvinlab.org/education/HADDOCK3/HADDOCK3-antibody-antigen/#defining-restraints-for-docking), running the passive_from_active.py creates the output but don't works to me.

And I wonder how can set the binding site only for antigen too.

**Comment by rvhonorato** [comment]
Hi there, the functionality of this script is rather limited, please have a look at the following for a more comprehensive usage:

https://github.com/haddocking/haddock-restraints // bonvinlab.org/haddock-restraints

and

https://www.wennr.science.uu.nl/gentbl

**Comment by amjjbonvin** [comment]
haddock3 also has command line interface to generate restraint.

And example of restraint generation can be found in the following tutorial:

	https://www.bonvinlab.org/education/HADDOCK3/HADDOCK3-antibody-antigen-bioexcel2024/#defining-ambiguous-restraints

**Comment by mgiulini** [comment]
to follow up on the previous answers: given two actpass files you can use the `active_passive_to_ambig` command (see also https://www.bonvinlab.org/haddock3/clients/haddock.clis.restraints.active_passive_to_ambig.html) as follows:

`haddock3-restraints active_passive_to_ambig actpass_one actpass_two`

provided that you have installed the haddock3 environment correctly. Here `actpass_one` and `actpass_two` refer to the files containing active and passive residues for the two partners.

Hope it helps!
