### ISSUE TITLE
`capri.py` module refactoring not writing all energetic terms

### ISSUE THREAD

**Issue by amjjbonvin** [haddocking/haddock3#949]
**Describe the bug**

Where turning less_io to true, the caprieval module is generating `capri_ss.tsv` files that are missing all the energetics, BSA, ... terms.
They look like:

```
model	md5	caprieval_rank	score	irmsd	fnat	lrmsd	ilrmsd	dockq	cluster_id	cluster_ranking	model-cluster_ranking
../1_rigidbody/rigidbody_5.pdb	-	1	-33.159	2.426	0.361	6.187	5.377	0.430	-	-	-
../1_rigidbody/rigidbody_6.pdb	-	2	-32.457	2.402	0.361	6.344	5.384	0.428	-	-	-
...
```

While they should contain:

```
model   md5 caprieval_rank  score   irmsd   fnat    lrmsd   ilrmsd  dockq   cluster_id  cluster_ranking model-cluster_ranking   air angles  bonds   bsa cdih    coup    dani    desolv  dihe    elec    improper    rdcs    rg  sym total   vdw vean    xpcs
../1_rigidbody/rigidbody_5.pdb  -   1   -33.159 2.426   0.361   6.187   5.377   0.430   -   -   -   78.132  0.000   0.000   1065.650    0.000   0.000   0.000   -14.316 0.000   -8.834  0.000   0.000   0.000   0.000   55.966  -13.332 0.000   0.000
../1_rigidbody/rigidbody_6.pdb  -   2   -32.457 2.402   0.361   6.344   5.384   0.428   -   -   -   92.651  0.000   0.000   1084.890    0.000   0.000   0.000   -13.778 0.000   -8.732  0.000   0.000   0.000   0.000   81.426  -2.494  0.000   0.000
```

The cluster files (`capri_clt.tsv`) are fine.

**To Reproduce**
Steps to reproduce the behavior, if relevant, provide the input that triggered the error:

1) Go into the haddock3/examples/docking-protein-protein directly.
2) Edit the docking-protein-protein-test.cfg and add `less_io=true`
3) Run the docking test with: `haddock3 docking-protein-protein-test.cfg`
4) Check a `capri_ss.tsv` file in one of the caprieval module in `run1-test`
5) Repeat the procedure with `less_io=false` and compare the `capri_ss.tsv` file

**Expected behavior**

The generated `capri_ss.tsv` files should contain all energetic terms:

```
model   md5 caprieval_rank  score   irmsd   fnat    lrmsd   ilrmsd  dockq   cluster_id  cluster_ranking model-cluster_ranking   air angles  bonds   bsa cdih    coup    dani    desolv  dihe    elec    improper    rdcs    rg  sym total   vdw vean    xpcs
../1_rigidbody/rigidbody_5.pdb  -   1   -33.159 2.426   0.361   6.187   5.377   0.430   -   -   -   78.132  0.000   0.000   1065.650    0.000   0.000   0.000   -14.316 0.000   -8.834  0.000   0.000   0.000   0.000   55.966  -13.332 0.000   0.000
../1_rigidbody/rigidbody_6.pdb  -   2   -32.457 2.402   0.361   6.344   5.384   0.428   -   -   -   92.651  0.000   0.000   1084.890    0.000   0.000   0.000   -13.778 0.000   -8.732  0.000   0.000   0.000   0.000   81.426  -2.494  0.000   0.000
```

**Comment by amjjbonvin** [comment]
PS: probably introduced by pull request #927

**Comment by rvhonorato** [comment]
> PS: probably introduced by pull request #927

#927 is an issue, it does not add code, the PR that links to this issue is #928.

Over there I added a `extract_data_from_capri_class` function that was not propating the model's energy terms. Missed that part since the tests were not updated to reflect this propagation; which was added in https://github.com/haddocking/haddock3/commit/f312079e88eaeeb77a96bd694340424a2c7ed146
