### ISSUE TITLE
Where to define the `run` directory?

### ISSUE THREAD

**Issue by joaomcteixeira** [haddocking/haddock3#95]
This is a small question but has profound implications.

Currently the `run_dir` is defined in the configuration file. However, is the run dir really part of the haddock setup? Instead, if we define the `run_dir` defined in the client interface, say `haddock3 CONFIG_PATH --run_dir FOLDER` the run dir becomes more execution specific and not configuration specific. It becomes easier to configure for repeating runs in several different folders, or moving configurations around. Having the parameter in the client also helps some internal implementations, for example the `logging`.

What are your thoughts?

**Comment by amjjbonvin** [comment]
But the config file also contains run-specific input like the files and settings 

Why would repeat the same run with a different dir and the same config file?

You should then also allow to pass other parameters and input data from the command libe 

=================================
 Prof. A.M.J.J. Bonvin | Faculty of Science
 Scientific Director Bijvoet Centre
 Utrecht University | bonvinlab.org 
 ***@***.*** | T: +31 30 2533859 
=================================

**Comment by joaomcteixeira** [comment]
other input can be defined also by absolute paths, for example, or a common parent path. But I understand your point. For me it is also difficult for now to decide. I thought now about this to facilitate the logging configuration, but that can always be arranged to fit the implementation. Perfect, we keep it in the config file for now, and wait to see how the user experience evolves.

**Comment by joaomcteixeira** [comment]
See #97 for a strategy to log without the `run dir` being defined. closing this for now
