### ISSUE TITLE
add ilrmsd to `capri_clt` tables

### ISSUE THREAD

**Issue by mgiulini** [haddocking/haddock3#956]
## **Desired feature/enhancement**
capri_clt file should contain average and std dev of ilrmsd values

## **Motivation**
these value is sometimes used to assess the quality of poses and clusters

**Comment by rvhonorato** [comment]
Still need to add integration tests for this `capri_clt` file

**Comment by mgiulini** [comment]
there is currently no check on capri_clt in the integration tests, please create another issue about that

**Comment by rvhonorato** [comment]
nope, it's related to this issue - don't worry I'll handle it :)
