### ISSUE TITLE
Remove restraints CLIs

### ISSUE THREAD

**Issue by rvhonorato** [haddocking/haddock3#959]
## **Desired feature/enhancement**

Remove all the restraints-related CLIs from the codebase

## **Motivation**

The current implementations of restraint generation routines are a port of an old and limited routines extracted from the web interface -> [`web/app/haddock24/PDBHandler`](https://github.com/haddocking/csbportal/blob/db0e476d15453afcbb6ee97e0e7854792a11d88b/web/app/haddock24/tools/PDBHandler.py). 

Whilist functional, they contribute to the dependencies (freesasa and biopython) and have a limited set of features and are of course subject to code smell and python deprecation.

All functionalities included here and more, have been implemented elsewehere -> https://github.com/haddocking/haddock-restraints. This other implementation can be served as a binary, to multiple architechtures, not requiring any setup. It also has a user-friendly documentation https://bonvinlab.org/haddock-restraints.

## **Description**

Remove all restraint-related CLI interfaces in haddock3 to remove code duplication and mulitple endpoints for the same functionality. For convenience the binary could be shipped here in `src/bin/restraints`

## **Additional context**

Despite being a beta version, there are already several tutorials for haddock3 that use this command line, they need to also be updated:

- https://www.bonvinlab.org/education/HADDOCK3/HADDOCK3-antibody-antigen/
- https://www.bonvinlab.org/education/HADDOCK3/HADDOCK3-antibody-antigen-bioexcel2024/

This will also impact `src/haddock/clis/restraints/webservice.py`

**Comment by VGPReys** [comment]
I am not sure of that one.
I think we could keep it.
We could:
- keep the CLI
- create bindings to `haddock-restraints`
- remove the functions ( in `src/haddock/clis/restraints`)

What do you think about this solution ?

**Comment by amjjbonvin** [comment]
Sounds a reasonable solution to me, but will it make things simpler?

The only real things that need to change are our tutorials.

**Comment by rvhonorato** [comment]
> * keep the CLI

"keeping the CLI" means keeping the API - the way people interact with the code, meaning there will need to be an adapter between the two applications. A lot of extra work for little benefit I think

> * create bindings to `haddock-restraints`

Not sure if that's what you mean, but it would be possible to expose the `haddock-restraints` api directly via [pyo3](https://github.com/PyO3/pyo3) - but that's also quite some work

> * remove the functions ( in `src/haddock/clis/restraints`)

yes, remove and/or move the relevant ones (that are refered in other parts of the code) to some lib

> What do you think about this solution ?

haddock is quickly becoming a software suite rather than a simple collection of scripts, changes like these are bound to happen at some point. It's best if we tackle these "big changes" soon rather than later. haddock3 is still beta/experimental and not released, so this is the best time to make changes 🤓

> The only real things that need to change are our tutorials.

Not realy, simply make it clear in the tutorials that users need to have the `beta5` version of haddock3 to run it, and add instruction on how to get this version. I don't see a reson to make it backwards compatible.

**Comment by VGPReys** [comment]
> > * create bindings to `haddock-restraints`
> 
> Not sure if that's what you mean

The idea was that the `haddock3-restraints` is simply pointing `haddock-restraints`, that comes with the haddock3 installation.
So, as you said before, just create an small adapter (what I was calling bindings) between the two applications.

**Comment by sverhoeven** [comment]
The haddock3-webapp uses [haddock.clis.restraints.webservice](https://github.com/haddocking/haddock3/blob/e297ca6992a8a4631112876789fc6c2fee9f414f/src/haddock/clis/restraints/webservice.py#L1) module as [a webservice](https://github.com/i-VRESSE/haddock3-webapp/blob/87d1d6d6ba9cc92b50822d6eb3e9f92974d71e2f/deploy/arq/docker-compose.yml#L145) to perform restraints calculations and preprocess pdb files using `pdbtools` package.

If the `haddock.clis.restraints` is removed then the haddock3 webapp would need a similar webservice preferable with an openapi specification.

**Comment by rvhonorato** [comment]
> The haddock3-webapp uses [haddock.clis.restraints.webservice](https://github.com/haddocking/haddock3/blob/e297ca6992a8a4631112876789fc6c2fee9f414f/src/haddock/clis/restraints/webservice.py#L1) module as [a webservice](https://github.com/i-VRESSE/haddock3-webapp/blob/87d1d6d6ba9cc92b50822d6eb3e9f92974d71e2f/deploy/arq/docker-compose.yml#L145) to perform restraints calculations and preprocess pdb files using `pdbtools` package.
> 
> If the `haddock.clis.restraints` is removed then the haddock3 webapp would need a similar webservice preferable with an openapi specification.

Good point @sverhoeven - my plan is to use `haddock-restraints` as WA, same as it will be in the GenTBL service. Need to coordinate this removal together with this addition. We will figure out which goes first, but i'll keep this in mind.

> > Not sure if that's what you mean
> 
> The idea was that the `haddock3-restraints` is simply pointing `haddock-restraints`, that comes with the haddock3 installation. So, as you said before, just create an small adapter (what I was calling bindings) between the two applications.

```bash
alias haddock3-restraints="haddock-restraints"
```
?

**Comment by sverhoeven** [comment]
> > The haddock3-webapp uses [haddock.clis.restraints.webservice](https://github.com/haddocking/haddock3/blob/e297ca6992a8a4631112876789fc6c2fee9f414f/src/haddock/clis/restraints/webservice.py#L1) module as [a webservice](https://github.com/i-VRESSE/haddock3-webapp/blob/87d1d6d6ba9cc92b50822d6eb3e9f92974d71e2f/deploy/arq/docker-compose.yml#L145) to perform restraints calculations and preprocess pdb files using `pdbtools` package.
> > If the `haddock.clis.restraints` is removed then the haddock3 webapp would need a similar webservice preferable with an openapi specification.
> 
> Good point @sverhoeven - my plan is to use `haddock-restraints` as WA, same as it will be in the GenTBL service. Need to coordinate this removal together with this addition. We will figure out which goes first, but i'll keep this in mind.
> 
> Then we can also remove `src/haddock/clis/restraints/webservice.py`
> 
> > > Not sure if that's what you mean
> > 
> > 
> > The idea was that the `haddock3-restraints` is simply pointing `haddock-restraints`, that comes with the haddock3 installation. So, as you said before, just create an small adapter (what I was calling bindings) between the two applications.
> 
> ```shell
> alias haddock3-restraints="haddock-restraints"
> ```
> 
> ?

WebAssembly instead of webservice would also work. Would need a nice js wrapper for the WebAssembly though.
