### ISSUE TITLE
gfortran: error: unrecognized command line option `-fallow-argument-mismatch`

### ISSUE THREAD

**Issue by GLking123** [haddocking/haddock3#981]
Hello,：
Thank you for your software. I am currently having some issues with the installation and I am following your tutorial step by step. After executing the command `"make install compiler=gfortran"`, I encountered the following error:
```
Installation directory: /public/home/caijing_lab/gonglei/software/cns/cns_solve_1.3/intel-x86_64bit-linux
copying files in instlib directory intel-x86_64bit-linux to intel-x86_64bit-linux
0read.me
arch_env
machine_c.c
machine_f.f
Makefile.header.1.ifort
Makefile.header.2.gfortran
Makefile.header.3.ifort_mp
Makefile.header.4.pgf95
Makefile.header.5.ifort_mp_profile
Makefile.header.6.ifort_mp_tcheck
Makefile.header.7.gfortran_mp
Using Makefile template for compiler: gfortran
removing old source files
linking source files to intel-x86_64bit-linux/source
linking machine_f.f to source directory
linking machine_c.c to source directory
linking generic fft file to source directory
making Makefile in source directory
testing Fortran and C compilers
compiling: gcc -O -DINTEGER='long int' -DCNS_ARCH_TYPE_LINUX 
C compiler passes test
compiling: gfortran -fdefault-integer-8 -w  -fallow-argument-mismatch -O3  -funroll-loops -ffast-math -static   
gfortran: error: unrecognized command line option ‘-fallow-argument-mismatch’
linking: gfortran -w  -static-libgfortran
gfortran: error: test_f.o: No such file or directory
/bin/sh: line 5: ./test_f: No such file or directory
***** ERROR: problem with Fortran compiler *****
make[3]: *** [fortran-test] Error 2
make[2]: *** [compiler-test] Error 2
make[1]: *** [compiler-test] Error 2
compiler problems - stopping installation
please check compilers before retrying installation
make: *** [install] Error 1
```
I checked the version of gfortran.`gfortran --version` 
```
GNU Fortran (GCC) 4.8.5 20150623 (Red Hat 4.8.5-39)
Copyright (C) 2015 Free Software Foundation, Inc.
```

For the above question, could you provide some debugging suggestions? Thank you for your valuable time and assistance. I sincerely look forward to your response！

**Comment by rvhonorato** [comment]
I think `-fallow-argument-mismatch` was introduced in fortran 10 - could you update your version?

**Comment by GLking123** [comment]
Because the server is not connected to the internet, the upgrade is more difficult. What should be done in this situation?

**Comment by GLking123** [comment]
Okay, I'll give it a try.

**Comment by GLking123** [comment]
I have tried the same mistake and the cluster environment is unable to upgrade.

I have downloaded the pre-compiled version of `CNS Solve 1.3 for Intel-Mac Linux.tar`. This should work, but how do I combine it with the other files?

`cns
OMP: Warning #72: KMP_AFFINITY: affinity only supported for Intel(R) processors.
OMP: Warning #71: KMP_AFFINITY: affinity not supported, using "none".
          ============================================================
          |                                                          |
          |            Crystallography & NMR System (CNS)            |
          |                         CNSsolve                         |
          |                                                          |
          ============================================================
           Version: 1.3
           Status: General release
          ============================================================
           Written by: A.T.Brunger, P.D.Adams, G.M.Clore, W.L.DeLano,
                       P.Gros, R.W.Grosse-Kunstleve,J.-S.Jiang,J.M.Krahn,
                       J.Kuszewski, M.Nilges, N.S.Pannu, R.J.Read,
                       L.M.Rice, G.F.Schroeder, T.Simonson, G.L.Warren.
           Copyright (c) 1997-2010 Yale University
          ============================================================
           Running on machine: hostname unknown (x86_64/Linux,64-bit)
                               with  1 threads
           Program started by: gonglei
           Program started at: 22:44:13 on 27-Aug-2024
          ============================================================

 FFT3C: Using FFTPACK4.1`


`haddock3 -h
[2024-08-27 22:33:59,932 defaults ERROR] CNS executable `bin/cns` not found. Please check the install instructions.
`

**Comment by mgiulini** [comment]
you have to create a symlink to your CNS executable as explained here https://github.com/haddocking/haddock3/blob/main/docs/INSTALL.md#4-make-a-cns-binary-shortcut-to-the-expected-path

**Comment by amjjbonvin** [comment]
If you drop us an email we can provide a pre-compiled CNS version that includes the haddock additions - the one you got now most likely does not have it have will give problems

**Comment by Rohit-Satyam** [comment]
Doing the following works:

```bash
sudo apt-get install gfortran-10

## Removing the oldgfortran since it will not be automatically picked up. See issue: https://stackoverflow.com/questions/60107426/gfortran-9-installed-but-getting-no-fortran-compiler-found-error-ubuntu-serv
sudo rm /usr/bin/gfortran
sudo ln -s /usr/bin/gfortran-10 /usr/bin/gfortran
```

**Comment by jacknicoludis** [comment]
I was able to get around this by changing the flag from `-fallow-argument-mismatch` to `-Wno-argument-mismatch` in `cns_solve_1.3/instlib/machine/supported/intel-x86_64bit_linux/Makefile.header.2.gfortran`, which was suggested by `claude-3.7-sonnet`
