### ISSUE TITLE
Add global backbone RMSD to caprieval

### ISSUE THREAD

**Issue by amjjbonvin** [haddocking/haddock3#989]
## **Desired feature/enhancement**

Add a global RMSD metric calculated over the entire backbone of all chains.

## **Motivation**

Currently `caprieval` only calculate RMSDs if there are more than one chain present.
It would be nice to add a global RMSD metric, i.e. calculate over the entire backbone of all chains. In that way also when using haddock in single molecule mode (e.g. for sampling conformations) we could still compare the models to a reference.

## **Description**

Add a new column to the output of caprieval with the global RMSD.
Alternatively, the ligand RMSD could be calculated over the entire backbone (or a defined region) when only one molecule is present.

**Comment by VGPReys** [comment]
I will try to do something about it

**Comment by VGPReys** [comment]
I guess, in the case of single chain analysis, we want to add the CASP metric ?
- LDDT
- RMSD
- TM-score
- ICS
- IPS
- z-score

what about a `[caspeval]` module ?

**Comment by VGPReys** [comment]
At least of some of them:
- RMSD and LDDT can be computed at the atom level (but could be limited to the backbone ones if needed)
- TM-score is at the residue level.
- I still have to figure out what are ICS and IPS, and why they are on my notes.

Maybe I should first add a new column in `[caprieval]` with full structure RMSD, and we can see later if we should place it somewhere else.

**Comment by amjjbonvin** [comment]
Simplest solution indeed.

> Maybe I should first add a new column in [caprieval] with full structure RMSD, and we can see later if we should place it somewhere else.
>
