### ISSUE TITLE
How to get cns.exe ?

### ISSUE THREAD

**Issue by aniketmoha9** [haddocking/haddock3#99]
Can you tell me from where and how can i download cns.exe file

**Comment by aniketmoha9** [comment]
Can you tell me from where and how can i download cns.exe file

**Comment by joaomcteixeira** [comment]
Dear @aniketmoha9 to have access to CNS you should contact @amjjbonvin (A.M.J.J.Bonvin@uu.nl)
Thanks, and welcome. Let us know your experience once you install and try HADDOCK3 :relaxed:

**Comment by rvhonorato** [comment]
Actually you need to compile it yourself, we do not distribute it. 

Please refer to the instructions in the [alpha1 branch](https://github.com/haddocking/haddock3/tree/alpha1):

```
Crystallography & NMR System (CNS)
- Make a request on the CNS website - http://cns-online.org/v1.3/
- Compiled with the contents of `cns1.3/`(provided)
```
