### ISSUE TITLE
Logic inconsistency when checking if file exists

### ISSUE THREAD

**Issue by rvhonorato** [haddocking/haddock3#993]
## **Module/Workflow/Library affected**

All modules that use CNS's `fileexist` function;
- `emref`
- `flexref`
- `mdref`
- `rigidbody`
- `emscoring`
- `mdscoring`
- `topoaa`

## **Expected behavior**

After checking checking if a file exists, update the value of the `$result` variable

## **Actual behavior**

After checking if an empty file exists, CNS will evaluate that a file with an empty string also exists.

### CNS logic
1. Create an empty file; `touch empty-file.txt`
2. Create a non-empty file `echo 00 > non-empty-file.txt`
3. Run the following `file.cns`
```fortran
set message=off echo=off end
eval ($empty_file = "empty-file.txt")
eval ($empty_string = "")
eval ($non_existing_file = "non-existing-file.txt")
eval ($non_empty_file = "non-empty-file.txt")

! Check if the `empty_string` exists as a file
fileexist $empty_string end
display RESULT=$result ! should be FALSE, `empty_string` is not a file

! Check if the `empty_file` exists as a file
fileexist $empty_file end
display RESULT=$result ! should be TRUE, `empty_file` is a file

! Check if the `empty_string` exists as a file
fileexist $empty_string end
display RESULT=$result ! should be FALSE, `empty_string` is not a file

! Check if the `non_empty_file` file exists as a file
fileexist $non_empty_file end
display RESULT=$result ! should be TRUE, `non_empty_file` is a file

! Check if the `non_existing_file` file exists as a file
fileexist $non_existing_file end
display RESULT=$result ! should be FALSE, `non_existing_file` is not a file

! Check if the `empty_string` exists as a file
fileexist $empty_string end
display RESULT=$result ! should be FALSE, `empty_string` is not a file

stop
```

Execute:
```bash
0] $ ~/cns.linux < file.cns | grep -E 'TRUE|FALSE'
1] RESULT=FALSE ! should be FALSE, `empty_string` is not a file
2] RESULT=TRUE ! should be TRUE, `empty_file` is a file
3] RESULT=TRUE ! should be FALSE, `empty_string` is not a file
4] RESULT=TRUE ! should be TRUE, `non_empty_file` is a file
5] RESULT=FALSE ! should be FALSE, `non_existing_file` is not a file
6] RESULT=FALSE ! should be FALSE, `empty_string` is not a file
```

In the demonstration above you can see that the proper evaluation of `empty_string` being a file or not, depends on what happened before - lines [3] and [6]

### haddock side

The way this affects haddock is that, if an user passes an empty file as one of the `fname` parameters the subsequent evaluations will be wrong.

1. Go to the `examples` directory
2. Create an empty file
`touch empty-file.txt`
3. Run the following configuration file:
```toml
run_dir = "tt"
mode = "local"
molecules =  [
    "data/e2aP_1F3G.pdb",
    "data/hpr_ensemble.pdb"
    ]
[topoaa]
[rigidbody]
ambig_fname = "data/e2a-hpr_air.tbl"
unambig_fname = "empty-file.txt"
sampling = 10
log_level = "verbose"
```
4. The run will fail because it will not generate any models;

5. Inspect the .out file;
```
gunzip tt/1_rigidbody/rigidbody_1.out.gz
```
``` 
cat tt/1_rigidbody/rigidbody_1.out
```

```
 CNSsolve>fileexist $unambig_fname end 
 MISCOM: file exists
 CNSsolve>if ($result eq true) then 
 NEXTCD: condition evaluated as true
 CNSsolve>     noe class dist @@$unambig_fname end 
 ASSFIL: file empty-file.txt opened.
 CNSsolve>end if 
 CNSsolve> 
 CNSsolve>fileexist $hbond_fname end 
 MISCOM: file exists
 CNSsolve>if ($result eq true) then 
 NEXTCD: condition evaluated as true
 CNSsolve>    noe @@$hbond_fname end 
 %ASSFIL-ERR: error opening file 
 %ASSFIL error encountered: Error accessing file
```

The error shown in the `.out` file is the one caused by the fileexist logic demonstrated above; here it will try to load `hbond_fname` which is set to `""`

## **Suggestions on how to fix it**

Either make a check on the python layer to not pass empty files as arguments in the the `.inp` files (will not fix the error and this issue might happen again) OR refactor the logic in the CNS scripts to reset the state of this `$result` variable (better)

The CNS scripts could be refactored to check wether it's an empty string or not using the not-equal (`#`) operator
```fortran
eval ($empty_string = "")

if ($empty_string # "") then
    display EMPTY_STRING is not empty, check if it is a file
else
    display EMPTY_STRING is empty, skip fileexist
end if

stop
```

## **Version**

`d26f0733cd48c75cce98b7085ee283133a632c02`

**Comment by amjjbonvin** [comment]
An empty file on the system is still a file... CNS does not check for content.

**Comment by rvhonorato** [comment]
Please read the description above

**Comment by amjjbonvin** [comment]
I did :-) 
But I proposed another possible solution that would work as well.

**Comment by rvhonorato** [comment]
> CNS does not check for content.
> So the behaviour is correct in principle.

This is not the issue, the issue is that it marks `""` exist files, depending on the order in which the command were executed

**Comment by amjjbonvin** [comment]
> This is incompatible with the parameter file design - why not change the CNS code?

So changing:

```
ambig_fname:
  default: ''
```

to:

```
ambig_fname:
  default: ’NONE'
```

would not work?

Then it is best to change the CNS code indeed.

**Comment by amjjbonvin** [comment]
I know.

**Comment by rvhonorato** [comment]
` default: ’NONE'` would introduce type polymorphism in the python/CNS interface and complicate things a bit

**Comment by amjjbonvin** [comment]
Ok - will work on the CNS code then
