### ISSUE TITLE
How to generate ambig.tbl for blind docking

### ISSUE THREAD

**Issue by zhouzheng2000zzbera** [haddocking/haddock3#998]
Dear HADDOCK3 Development Team,

I hope this message finds you well. I am currently looking to perform batch docking between various proteins and peptides to identify candidate proteins. However, I am working with completely unknown proteins. Could you please guide me on how to generate the ambiguous interface constraints (ambig.tbl) for blind docking?

I would greatly appreciate your assistance.

Thank you very much for your time and help!

Best regards,

**Comment by VGPReys** [comment]
Hi there,

Thanks for your interest in using haddock3 for your research !

Basically three options can do ab-initio docking.

- **Center of mass restraints**: for this, turn `cmrest = true` in `[rigidbody]` and `[flexref]` modules and `contactairs = true` in subsequent CNS modules.
- **Random airs**: for this, turn `ranair = true` in `[rigidbody]` and `contactairs = true` in subsequent CNS modules.
- **Surface restraints**: for this, turn `surfrest = true` in `[rigidbody]`, either `contactairs = true` or `cmrest = true` in `[flexref]` and `contactairs = true` subsequent CNS modules.

We have been performing small benchmarks (on HADDOCK2.5) on what is the best ab-initio solution, and it seems that the 2nd option was giving slight better results, but not significant.

Do not forget to increase the sampling in `[rigidbody]` as the it basically relies on trials and errors to find a good solution.

Hope this helps,

Cheers

**Comment by zhouzheng2000zzbera** [comment]
Hi there,

Thank you so much for the detailed and helpful response! I really appreciate the guidance on the different options for ab-initio docking. I'll make sure to increase the sampling in [rigidbody] as you suggested.

Thanks again for your support!

Cheers
